- generic [ref=f284e1]:
  - generic [ref=f284e2]:
    - generic:
      - generic:
        - heading "To view keyboard shortcuts, press question mark View keyboard shortcuts" [level=2] [ref=f284e3]:
          - generic [ref=f284e4]: To view keyboard shortcuts, press question mark
          - link "View keyboard shortcuts" [ref=f284e5] [cursor=pointer]:
            - /url: /i/keyboard_shortcuts
        - generic:
          - generic:
            - button "Grok" [ref=f284e6] [cursor=pointer]
            - button "Chat" [ref=f284e10] [cursor=pointer]
          - generic:
            - generic:
              - generic:
                - dialog:
                  - group [ref=f284e14]:
                    - dialog [ref=f284e16]:
                      - generic [ref=f284e19]:
                        - progressbar [ref=f284e20]
                        - generic [ref=f284e26]:
                          - button "Close" [ref=f284e28] [cursor=pointer]
                          - button "Drafts" [ref=f284e36] [cursor=pointer]
                        - generic [ref=f284e45]:
                          - generic [ref=f284e46]:
                            - generic [ref=f284e54]:
                              - generic:
                                - generic:
                                  - generic:
                                    - generic "ChaosmagickLabs":
                                      - img "ChaosmagickLabs"
                            - generic [ref=f284e75]:
                              - generic [ref=f284e76]: What’s happening?
                              - textbox "Post text" [active] [ref=f284e79]
                          - generic [ref=f284e83]:
                            - button "Everyone can reply" [ref=f284e87] [cursor=pointer]
                            - generic [ref=f284e96]:
                              - navigation [ref=f284e97]:
                                - generic [ref=f284e98]:
                                  - generic:
                                    - button "Previous" [disabled]
                                  - tablist [ref=f284e100]:
                                    - generic [ref=f284e103]:
                                      - button "Add photos or video" [ref=f284e104] [cursor=pointer]
                                      - button "Choose File" [ref=f284e110]
                                    - button "Add a GIF" [ref=f284e113] [cursor=pointer]
                                    - button "Generate image" [ref=f284e121] [cursor=pointer]
                                    - button "Add poll" [ref=f284e128] [cursor=pointer]
                                    - button "Add emoji" [ref=f284e136] [cursor=pointer]
                                    - button "Schedule post" [ref=f284e144] [cursor=pointer]
                                    - button "Tag location" [disabled] [ref=f284e151]
                                    - button "Content disclosure" [ref=f284e158] [cursor=pointer]
                                  - generic:
                                    - button "Next" [disabled]
                              - button "Post" [disabled] [ref=f284e165]
        - generic [ref=f284e169]:
          - button [ref=f284e170] [cursor=pointer]
          - button [ref=f284e172] [cursor=pointer]
          - banner [ref=f284e174]:
            - generic [ref=f284e176]:
              - generic [ref=f284e177]:
                - heading [level=1] [ref=f284e179] [cursor=pointer]:
                  - link [ref=f284e180]:
                    - /url: /home
                - navigation [ref=f284e186]:
                  - link [ref=f284e187] [cursor=pointer]:
                    - /url: /home
                    - generic [ref=f284e188]: Home
                  - link [ref=f284e194] [cursor=pointer]:
                    - /url: /explore
                    - generic [ref=f284e195]: Explore
                  - link [ref=f284e201] [cursor=pointer]:
                    - /url: /notifications
                    - generic [ref=f284e202]: Notifications
                  - link [ref=f284e208] [cursor=pointer]:
                    - /url: /i/connect_people
                    - generic [ref=f284e209]: Follow
                  - link [ref=f284e215] [cursor=pointer]:
                    - /url: /i/chat
                    - generic [ref=f284e216]: Chat
                  - link [ref=f284e222] [cursor=pointer]:
                    - /url: /i/grok
                    - generic [ref=f284e223]: Grok
                  - link [ref=f284e230] [cursor=pointer]:
                    - /url: /Cha0smagickLABS
                    - generic [ref=f284e231]: Profile
                  - button [ref=f284e237] [cursor=pointer]:
                    - generic [ref=f284e238]: More
                - link [ref=f284e245] [cursor=pointer]:
                  - /url: /compose/post
                  - generic [ref=f284e246]: Post
              - button [ref=f284e254] [cursor=pointer]:
                - generic [ref=f284e266]:
                  - generic [ref=f284e267]: ChaosmagickLabs
                  - generic [ref=f284e271]: "@Cha0smagickLABS"
          - main [ref=f284e279]:
            - generic [ref=f284e282]:
              - generic [ref=f284e284]:
                - generic [ref=f284e285]:
                  - generic [ref=f284e288]:
                    - navigation [ref=f284e290]:
                      - generic [ref=f284e291]:
                        - generic:
                          - button [disabled]
                        - tablist [ref=f284e293]:
                          - tab [selected] [ref=f284e294] [cursor=pointer]:
                            - generic [ref=f284e295]: For you
                          - tab [ref=f284e299] [cursor=pointer]:
                            - generic [ref=f284e300]: Following
                          - tab [ref=f284e303] [cursor=pointer]:
                            - generic [ref=f284e304]: Movies & TV
                          - tab [ref=f284e307] [cursor=pointer]:
                            - generic [ref=f284e308]: Memes
                          - tab [ref=f284e311] [cursor=pointer]:
                            - generic [ref=f284e312]: Pets
                        - generic:
                          - button [disabled]
                    - button [ref=f284e316] [cursor=pointer]
                  - generic:
                    - generic:
                      - status:
                        - button:
                          - generic: See new posts
                - generic [ref=f284e327]:
                  - link [ref=f284e336] [cursor=pointer]:
                    - /url: /Cha0smagickLABS
                  - generic [ref=f284e339]:
                    - generic [ref=f284e357]:
                      - generic [ref=f284e358]: What’s happening?
                      - textbox [ref=f284e361]
                    - generic [ref=f284e368]:
                      - navigation [ref=f284e369]:
                        - generic [ref=f284e370]:
                          - generic:
                            - button [disabled]
                          - tablist [ref=f284e372]:
                            - generic [ref=f284e375]:
                              - button [ref=f284e376] [cursor=pointer]
                              - button [ref=f284e382]
                            - button [ref=f284e385] [cursor=pointer]
                            - button [ref=f284e393] [cursor=pointer]
                            - button [ref=f284e400] [cursor=pointer]
                            - button [ref=f284e408] [cursor=pointer]
                            - button [ref=f284e416] [cursor=pointer]
                            - button [disabled] [ref=f284e423]
                            - button [ref=f284e430] [cursor=pointer]
                          - generic:
                            - button [disabled]
                      - button [disabled] [ref=f284e437]:
                        - generic [ref=f284e438]: Post
                - region [ref=f284e515]:
                  - heading [level=1] [ref=f284e516]: Your Home Timeline
                  - generic [ref=f284e518]:
                    - article [ref=f284e522] [cursor=pointer]:
                      - generic [ref=f284e528]:
                        - link [ref=f284e540]:
                          - /url: /spooky_nature
                        - generic [ref=f284e543]:
                          - generic [ref=f284e545]:
                            - generic [ref=f284e548]:
                              - link [ref=f284e551]:
                                - /url: /spooky_nature
                                - generic [ref=f284e552]: ⛆ ⛆
                              - generic [ref=f284e562]:
                                - link [ref=f284e564]:
                                  - /url: /spooky_nature
                                  - generic [ref=f284e565]: "@spooky_nature"
                                - generic [ref=f284e566]: ·
                                - link [ref=f284e568]:
                                  - /url: /spooky_nature/status/2082339031174799493
                                  - time [ref=f284e569]: 13h
                            - generic [ref=f284e571]:
                              - button [ref=f284e573]
                              - button [ref=f284e584]
                          - generic [ref=f284e591]: nothing feels better than this weather.
                          - button [ref=f284e619]
                          - group [ref=f284e626]:
                            - button [ref=f284e628]:
                              - generic [ref=f284e629]: "20"
                            - button [ref=f284e639]:
                              - generic [ref=f284e640]: "180"
                            - button [ref=f284e650]:
                              - generic [ref=f284e651]: 1.2K
                            - link [ref=f284e661]:
                              - /url: /spooky_nature/status/2082339031174799493/analytics
                              - generic [ref=f284e662]: 18K
                            - button [ref=f284e672]
                            - button [ref=f284e681]
                    - article [ref=f284e691] [cursor=pointer]:
                      - generic [ref=f284e697]:
                        - link [ref=f284e709]:
                          - /url: /cabinsmountain
                        - generic [ref=f284e712]:
                          - generic [ref=f284e714]:
                            - generic [ref=f284e717]:
                              - link [ref=f284e720]:
                                - /url: /cabinsmountain
                                - generic [ref=f284e721]: Mountain Cabins
                              - generic [ref=f284e730]:
                                - link [ref=f284e732]:
                                  - /url: /cabinsmountain
                                  - generic [ref=f284e733]: "@cabinsmountain"
                                - generic [ref=f284e734]: ·
                                - link [ref=f284e736]:
                                  - /url: /cabinsmountain/status/2082247732035510314
                                  - time [ref=f284e737]: 19h
                            - generic [ref=f284e739]:
                              - button [ref=f284e741]
                              - button [ref=f284e752]
                          - button [ref=f284e785]
                          - group [ref=f284e792]:
                            - button [ref=f284e794]:
                              - generic [ref=f284e795]: "66"
                            - button [ref=f284e805]:
                              - generic [ref=f284e806]: "370"
                            - button [ref=f284e816]:
                              - generic [ref=f284e817]: 4.9K
                            - link [ref=f284e827]:
                              - /url: /cabinsmountain/status/2082247732035510314/analytics
                              - generic [ref=f284e828]: 278K
                            - button [ref=f284e838]
                            - button [ref=f284e847]
                    - article [ref=f284e857] [cursor=pointer]:
                      - generic [ref=f284e863]:
                        - link [ref=f284e875]:
                          - /url: /Switzerland_aib
                        - generic [ref=f284e878]:
                          - generic [ref=f284e880]:
                            - generic [ref=f284e883]:
                              - link [ref=f284e886]:
                                - /url: /Switzerland_aib
                                - generic [ref=f284e887]: SwitzerlandBest
                              - generic [ref=f284e896]:
                                - link [ref=f284e898]:
                                  - /url: /Switzerland_aib
                                  - generic [ref=f284e899]: "@Switzerland_aib"
                                - generic [ref=f284e900]: ·
                                - link [ref=f284e902]:
                                  - /url: /Switzerland_aib/status/2082473721701306722
                                  - time [ref=f284e903]: 4h
                            - generic [ref=f284e905]:
                              - button [ref=f284e907]
                              - button [ref=f284e918]
                          - generic [ref=f284e925]: Switzerland
                          - button [ref=f284e954]
                          - group [ref=f284e961]:
                            - button [ref=f284e963]:
                              - generic [ref=f284e964]: "1"
                            - button [ref=f284e974]:
                              - generic [ref=f284e975]: "8"
                            - button [ref=f284e985]:
                              - generic [ref=f284e986]: "79"
                            - link [ref=f284e996]:
                              - /url: /Switzerland_aib/status/2082473721701306722/analytics
                              - generic [ref=f284e997]: 1.2K
                            - button [ref=f284e1007]
                            - button [ref=f284e1016]
              - generic [ref=f284e454]:
                - search [ref=f284e459]:
                  - combobox [ref=f284e471]
                - complementary [ref=f284e475]:
                  - generic [ref=f284e476]: Subscribe to Premium
                  - generic [ref=f284e478]: Get rid of ads, see your analytics, boost your replies and unlock 20+ features.
                  - link [ref=f284e479] [cursor=pointer]:
                    - /url: /i/premium_sign_up
                    - generic [ref=f284e480]: Subscribe
                - generic [ref=f284e1026]:
                  - heading [level=2] [ref=f284e1028]:
                    - generic [ref=f284e1029]: Today’s News
                    - button [ref=f284e1032] [cursor=pointer]
                  - generic [ref=f284e1037]:
                    - link [ref=f284e1038] [cursor=pointer]:
                      - generic [ref=f284e1041]:
                        - generic [ref=f284e1042]: "Zendaya and Tom Holland Shine at Spider-Man: Brand New Day UK Premiere"
                        - generic [ref=f284e1043]: Trending now · Entertainment · 12.4K posts
                    - link [ref=f284e1082] [cursor=pointer]:
                      - generic [ref=f284e1085]:
                        - generic [ref=f284e1086]: BTS 'Aliens' Tops iTunes in 51 Countries After Grammy Boycott
                        - generic [ref=f284e1087]: Trending now · Entertainment · 15.9K posts
                    - link [ref=f284e1126] [cursor=pointer]:
                      - generic [ref=f284e1129]:
                        - generic [ref=f284e1130]: Heated Rivalry Stars Storrie and Williams Spotted Together in Toronto
                        - generic [ref=f284e1131]: Trending now · Entertainment · 8,478 posts
                - region [ref=f284e1170]:
                  - heading [level=1] [ref=f284e1171]: Trending now
                  - generic [ref=f284e1173]:
                    - heading [level=2] [ref=f284e1177]:
                      - generic [ref=f284e1178]: What’s happening
                    - link [ref=f284e1181] [cursor=pointer]:
                      - generic [ref=f284e1182]:
                        - generic [ref=f284e1183]: Siente La Pasión
                        - generic [ref=f284e1184]: Apuesta por tu equipo favorito
                        - generic [ref=f284e1185]: Promoted by BetPlay
                        - button [ref=f284e1193]
                    - link [ref=f284e1202] [cursor=pointer]:
                      - generic [ref=f284e1203]:
                        - generic [ref=f284e1204]: Sports · Trending
                        - generic [ref=f284e1206]: Osorio
                        - button [ref=f284e1209]
                    - link [ref=f284e1218] [cursor=pointer]:
                      - generic [ref=f284e1219]:
                        - generic [ref=f284e1220]: Only on X · Trending
                        - generic [ref=f284e1222]: Japón
                        - button [ref=f284e1225]
                    - link [ref=f284e1234] [cursor=pointer]:
                      - generic [ref=f284e1235]:
                        - generic [ref=f284e1236]: Trending in Colombia
                        - generic [ref=f284e1238]: Grammys
                        - button [ref=f284e1241]
                    - link [ref=f284e1250] [cursor=pointer]:
                      - /url: /explore/tabs/for-you
                      - generic [ref=f284e1251]: Show more
                - complementary [ref=f284e1252]:
                  - heading [level=2] [ref=f284e1254]:
                    - generic [ref=f284e1255]: Who to follow
                  - list [ref=f284e1256]:
                    - listitem [ref=f284e1257] [cursor=pointer]:
                      - generic [ref=f284e1258]:
                        - link [ref=f284e1268]:
                          - /url: /Marvel
                        - generic [ref=f284e1272]:
                          - generic [ref=f284e1274]:
                            - link [ref=f284e1276]:
                              - /url: /Marvel
                              - generic [ref=f284e1277]: Marvel Entertainment
                            - link [ref=f284e1290]:
                              - /url: /Marvel
                              - generic [ref=f284e1291]: "@Marvel"
                          - button [ref=f284e1294]:
                            - generic [ref=f284e1295]: Follow
                    - listitem [ref=f284e1298] [cursor=pointer]:
                      - generic [ref=f284e1299]:
                        - link [ref=f284e1309]:
                          - /url: /ParamountPics
                        - generic [ref=f284e1313]:
                          - generic [ref=f284e1315]:
                            - link [ref=f284e1317]:
                              - /url: /ParamountPics
                              - generic [ref=f284e1318]: Paramount Pictures
                            - link [ref=f284e1331]:
                              - /url: /ParamountPics
                              - generic [ref=f284e1332]: "@ParamountPics"
                          - button [ref=f284e1335]:
                            - generic [ref=f284e1336]: Follow
                    - listitem [ref=f284e1339] [cursor=pointer]:
                      - generic [ref=f284e1340]:
                        - link [ref=f284e1350]:
                          - /url: /DCOfficial
                        - generic [ref=f284e1354]:
                          - generic [ref=f284e1356]:
                            - link [ref=f284e1358]:
                              - /url: /DCOfficial
                              - generic [ref=f284e1359]: DC
                            - link [ref=f284e1372]:
                              - /url: /DCOfficial
                              - generic [ref=f284e1373]: "@DCOfficial"
                          - button [ref=f284e1376]:
                            - generic [ref=f284e1377]: Follow
                  - link [ref=f284e1380] [cursor=pointer]:
                    - /url: /i/connect_people?user_id=2082185111257194496
                    - generic [ref=f284e1381]: Show more
                - navigation [ref=f284e493]:
                  - generic [ref=f284e494]:
                    - link [ref=f284e495] [cursor=pointer]:
                      - /url: https://x.com/tos
                      - text: Terms
                    - generic [ref=f284e496]: ·
                  - generic [ref=f284e497]:
                    - link [ref=f284e498] [cursor=pointer]:
                      - /url: https://x.com/privacy
                      - text: Privacy
                    - generic [ref=f284e499]: ·
                  - generic [ref=f284e500]:
                    - link [ref=f284e501] [cursor=pointer]:
                      - /url: https://support.x.com/articles/20170514
                      - text: Cookies
                    - generic [ref=f284e502]: ·
                  - generic [ref=f284e503]:
                    - link [ref=f284e504] [cursor=pointer]:
                      - /url: https://help.x.com/resources/accessibility
                      - text: Accessibility
                    - generic [ref=f284e505]: ·
                  - generic [ref=f284e506]:
                    - link [ref=f284e507] [cursor=pointer]:
                      - /url: https://business.x.com/help/troubleshooting/how-twitter-ads-work.html?ref=web-twc-ao-gbl-adsinfo&utm_source=twc&utm_medium=web&utm_campaign=ao&utm_content=adsinfo
                      - text: Ads Info
                    - generic [ref=f284e508]: ·
                  - button [ref=f284e509] [cursor=pointer]:
                    - generic [ref=f284e510]: More
                  - generic [ref=f284e514]: © 2026 X Corp.
  - region "Notifications alt+T"