ARTICLES_J = [
    {
        "slug": "paranormal-phenomena-types",
        "title": "Types of Paranormal Phenomena: A Complete Guide",
        "index_title": "Types of Paranormal Phenomena: A Complete Guide",
        "desc": "Explore the diverse categories of paranormal activity and experiences.",
        "keywords": "paranormal phenomena, types of paranormal, ghost types, poltergeist, hauntings",
        "og_alt": "A mysterious paranormal scene with orbs and shadows",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 8,
        "category": "paranormal",
        "excerpt": "From hauntings to apparitions, here is the complete taxonomy of paranormal phenomena.",
        "cta_apps": ["apps.parapsychology", "apps.ghost-hunting"],
        "related": [{"slug": "history-of-ghost-hunting", "title": "The History of Ghost Hunting"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}, {"title": "Paranormal Database", "url": "https://paranormaldatabase.com"}],
        "howto": "Use this guide as a framework for understanding different types of paranormal experiences.",
        "toc": ["Introduction", "Hauntings", "Apparitions", "Poltergeists", "Ephemeral Phenomena", "Physical Manifestations", "Psychic Phenomena", "Classifying Experiences"],
        "sections": [{"name": "Introduction", "content": "Paranormal phenomena encompass experiences that lie outside current scientific explanation."}, {"name": "Hauntings", "content": "Hauntings are recurring paranormal events associated with a specific location."}, {"name": "Apparitions", "content": "Apparitions are visual manifestations of deceased individuals appearing to the living."}, {"name": "Poltergeists", "content": "Poltergeists are disruptive spirits associated with physical disturbances."}, {"name": "Ephemeral Phenomena", "content": "Shadows, orbs, mists, and other transient paranormal visuals."}, {"name": "Physical Manifestations", "content": "Objects moving, unexplained sounds, and temperature changes."}, {"name": "Psychic Phenomena", "content": "Clairvoyance, clairaudience, telepathy, and other psychic capacities."}, {"name": "Classifying Experiences", "content": "Most experiences contain elements of multiple categories and require careful analysis."}],
        "faq": [{"q": "Are all hauntings malevolent?", "a": "No, many hauntings involve benign or unaware spirits."}],
    },
    {
        "slug": "ghost-hunting-methods",
        "title": "Ghost Hunting Methods and Equipment Guide",
        "index_title": "Ghost Hunting Methods and Equipment Guide",
        "desc": "Professional methods and tools for investigating paranormal phenomena.",
        "keywords": "ghost hunting, paranormal investigation, EMF meter, spirit box",
        "og_alt": "A paranormal investigation team using ghost hunting equipment",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 9,
        "category": "paranormal",
        "excerpt": "From EMF readers to spirit boxes, learn the essential tools and methods for paranormal investigation.",
        "cta_apps": ["apps.ghost-hunting", "apps.parapsychology"],
        "related": [{"slug": "paranormal-phenomena-types", "title": "Types of Paranormal Phenomena"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}],
        "howto": "Follow established investigation protocols and always prioritize safety and ethics.",
        "toc": ["Introduction", "Preparation and Research", "Basic Equipment", "Advanced Equipment", "Investigation Techniques", "Data Collection", "Analysis and Documentation", "Ethical Guidelines"],
        "sections": [{"name": "Introduction", "content": "Paranormal investigation combines scientific methodology with open-minded exploration."}, {"name": "Preparation and Research", "content": "Research the location's history and prior paranormal reports before investigating."}, {"name": "Basic Equipment", "content": "EMF meters, digital thermometers, audio recorders, and cameras form the basic toolkit."}, {"name": "Advanced Equipment", "content": "Spirit boxes, infrared cameras, and motion detectors add investigative depth."}, {"name": "Investigation Techniques", "content": "Use structured sessions with baseline readings, controlled provocations, and systematic sweeps."}, {"name": "Data Collection", "content": "Document everything — audio, video, environmental readings, and witness statements."}, {"name": "Analysis and Documentation", "content": "Review and correlate data, ruling out conventional explanations before considering paranormal causes."}, {"name": "Ethical Guidelines", "content": "Respect the location, its history, and any spirits encountered during investigations."}],
        "faq": [{"q": "Can ghost hunting prove ghosts exist?", "a": "While compelling evidence can be gathered, paranormal proof remains elusive due to the nature of the phenomena."}],
    },
    {
        "slug": "poltergeist-cases",
        "title": "Famous Poltergeist Cases in History",
        "index_title": "Famous Poltergeist Cases in History",
        "desc": "Examining the most well-documented poltergeist cases from around the world.",
        "keywords": "poltergeist cases, famous hauntings, paranormal cases, Enfield poltergeist",
        "og_alt": "Historical images from famous poltergeist investigation sites",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 8,
        "category": "paranormal",
        "excerpt": "The Enfield poltergeist and other famous cases challenge our understanding of the paranormal.",
        "cta_apps": ["apps.parapsychology", "apps.ghost-hunting"],
        "related": [{"slug": "ghost-hunting-methods", "title": "Ghost Hunting Methods and Equipment Guide"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}, {"title": "Enfield Investigation Files", "url": "https://spr.org/enfield"}],
        "howto": "Study these cases to understand the complexity and variety of poltergeist phenomena.",
        "toc": ["Introduction", "The Enfield Poltergeist", "The Rosenheim Poltergeist", "The Borley Rectory", "The Amityville Case", "Modern Poltergeist Reports", "Patterns in Poltergeist Activity", "The RSPK Theory"],
        "sections": [{"name": "Introduction", "content": "Famous poltergeist cases have been studied for decades, providing invaluable insights."}, {"name": "The Enfield Poltergeist", "content": "The 1977-78 Enfield case in London involved a young girl and extensive physical phenomena."}, {"name": "The Rosenheim Poltergeist", "content": "A 1967 German case involving electrical disturbances attributed to poltergeist activity."}, {"name": "The Borley Rectory", "content": "The 'most haunted house in England' documented by Harry Price in the early 20th century."}, {"name": "The Amityville Case", "content": "The 1974 DeFeo murders and subsequent haunting claims at 112 Ocean Avenue."}, {"name": "Modern Poltergeist Reports", "content": "Contemporary cases continue to document poltergeist activity in the digital age."}, {"name": "Patterns in Poltergeist Activity", "content": "Recurring patterns include focus on adolescents, stress-related triggers, and physical manifestations."}, {"name": "The RSPK Theory", "content": "Recurrent Spontaneous Psychokinesis explains poltergeist phenomena as unconscious psychokinetic energy."}],
        "faq": [{"q": "What causes poltergeist activity?", "a": "The leading theory suggests it is related to psychological stress and unconscious psychokinesis."}],
    },
    {
        "slug": "cryptozoology-introduction",
        "title": "Cryptozoology: The Search for Hidden Animals",
        "index_title": "Cryptozoology: The Search for Hidden Animals",
        "desc": "An introduction to cryptozoology, the study of hidden or unknown animals.",
        "keywords": "cryptozoology, cryptids, bigfoot, lake monster, unknown animals",
        "og_alt": "A misty forest scene with traces of an unknown creature",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 7,
        "category": "paranormal",
        "excerpt": "From Bigfoot to the Loch Ness Monster, cryptozoology explores creatures that science has not confirmed.",
        "cta_apps": ["apps.parapsychology", "apps.cryptozoology"],
        "related": [{"slug": "paranormal-phenomena-types", "title": "Types of Paranormal Phenomena"}],
        "references": [{"title": "International Society of Cryptozoology", "url": "https://cryptozoology-isc.org"}],
        "howto": "Approach cryptozoology with scientific rigor while remaining open to the possibility of unknown species.",
        "toc": ["Introduction", "What is Cryptozoology?", "Famous Cryptids", "Bigfoot and Sasquatch", "The Loch Ness Monster", "The Chupacabra", "The Jersey Devil", "Evidence and Skepticism", "The Science Behind Cryptozoology"],
        "sections": [{"name": "Introduction", "content": "Cryptozoology is the study of hidden animals whose existence is suggested by folklore or partial evidence."}, {"name": "What is Cryptozoology?", "content": "Unlike pseudoscience, cryptozoology operates at the boundary of zoology and field investigation."}, {"name": "Famous Cryptids", "content": "Cryptids like Bigfoot, the Loch Ness Monster, and the Chupacabra capture global imagination."}, {"name": "Bigfoot and Sasquatch", "content": "North American hominid legends with thousands of reported sightings across North America."}, {"name": "The Loch Ness Monster", "content": "The most famous lake creature, investigated for over a century with mixed results."}, {"name": "The Chupacabra", "content": "The 'goat sucker' first reported in Puerto Rico, now reported worldwide."}, {"name": "The Jersey Devil", "content": "A regional creature of the New Jersey Pine Barrens with centuries of reported sightings."}, {"name": "Evidence and Skepticism", "content": "Cryptozoology walks a fine line between genuine research and wishful thinking."}, {"name": "The Science Behind Cryptozoology", "content": "Genuine cryptozoology relies on field evidence, DNA analysis, and zoological methodology."}],
        "faq": [{"q": "Is cryptozoology a science?", "a": "It is a pseudoscience in some circles but a legitimate field of inquiry in others, depending on methodology."}],
    },
    {
        "slug": "near-death-experiences-science",
        "title": "Near-Death Experiences: Science Meets the Paranormal",
        "index_title": "Near-Death Experiences: Science Meets the Paranormal",
        "desc": "Exploring the science and phenomenology of near-death experiences (NDEs).",
        "keywords": "near-death experiences, NDE, out-of-body experience, afterlife",
        "og_alt": "A cosmic tunnel of light representing a classic NDE",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 8,
        "category": "paranormal",
        "excerpt": "NDEs challenge our understanding of consciousness, the brain, and what happens after death.",
        "cta_apps": ["apps.parapsychology", "apps.nde-research"],
        "related": [{"slug": "paranormal-phenomena-types", "title": "Types of Paranormal Phenomena"}],
        "references": [{"title": "IANDS", "url": "https://iands.org"}, {"title": "AWARE Study", "url": "https://awarestudy.org"}],
        "howto": "Review peer-reviewed research from organizations like IANDS for evidence-based NDE analysis.",
        "toc": ["Introduction", "What Are NDEs?", "The Core NDE Experience", "The AWARE Study", "Veridical Out-of-Body Experiences", "The Tunnel and Light", "Life Review", "Peace and Comfort", "Scientific Theories", "Implications for Consciousness"],
        "sections": [{"name": "Introduction", "content": "Near-death experiences represent one of the most compelling areas where science meets the paranormal."}, {"name": "What Are NDEs?", "content": "NDEs are profound personal experiences associated with impending death or severe trauma."}, {"name": "The Core NDE Experience", "content": "Common elements include leaving the body, traveling through a tunnel, encountering light, and meeting deceased relatives."}, {"name": "The AWARE Study", "content": "The AWARE study investigated whether consciousness can continue during cardiac arrest."}, {"name": "Veridical Out-of-Body Experiences", "content": "Some NDErs report accurately observing events from their OBE perspective during cardiac arrest."}, {"name": "The Tunnel and Light", "content": "The tunnel of light is one of the most universally reported NDE elements."}, {"name": "Life Review", "content": "Many NDErs experience a panoramic life review where they relive their experiences from others' perspectives."}, {"name": "Peace and Comfort", "content": "Overwhelming feelings of peace, love, and comfort are hallmarks of genuine NDEs."}, {"name": "Scientific Theories", "content": "Hypotheses range from neurotranschemical brain processes to consciousness existing independent of the brain."}, {"name": "Implications for Consciousness", "content": "NDEs challenge materialist views of consciousness and suggest deeper aspects of mind."}],
        "faq": [{"q": "Are NDEs just brain chemistry?", "a": "While brain chemistry plays a role, veridical OBEs and consistent elements across cultures pose challenges to this explanation."}],
    },
    {
        "slug": "paranormal-investigation-history",
        "title": "The History of Paranormal Investigation",
        "index_title": "The History of Paranormal Investigation",
        "desc": "A comprehensive timeline of paranormal investigation from ancient times to the modern era.",
        "keywords": "paranormal history, ghost hunting history, SPR history, paranormal timeline",
        "og_alt": "A historical timeline of paranormal investigation tools and methods",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 9,
        "category": "paranormal",
        "excerpt": "From ancient oracles to modern EMF meters, the history of paranormal investigation is rich and fascinating.",
        "cta_apps": ["apps.parapsychology", "apps.ghost-hunting"],
        "related": [{"slug": "ghost-hunting-methods", "title": "Ghost Hunting Methods and Equipment Guide"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}],
        "howto": "Use this historical overview to understand how paranormal investigation evolved.",
        "toc": ["Introduction", "Ancient Divination", "Medieval Supernatural Beliefs", "The Spiritualist Movement", "The Society for Psychical Research", "Early 20th Century Investigations", "The Ghost Hunting Era", "Modern Paranormal Research", "Digital Age Investigation"],
        "sections": [{"name": "Introduction", "content": "The human fascination with the supernatural has driven investigation methods for millennia."}, {"name": "Ancient Divination", "content": "Ancient cultures used oracles, omens, and divination to interpret paranormal phenomena."}, {"name": "Medieval Supernatural Beliefs", "content": "Medieval Europe saw elaborate theories about demons, hauntings, and the spirit world."}, {"name": "The Spiritualist Movement", "content": "The 19th-century Spiritualist movement brought systematic attempts to contact the dead."}, {"name": "The Society for Psychical Research", "content": "Founded in 1882, the SPR established scientific protocols for paranormal investigation."}, {"name": "Early 20th Century Investigations", "content": "Harry Price and others pioneered scientific ghost investigation techniques."}, {"name": "The Ghost Hunting Era", "content": "Television and popular culture brought ghost hunting into mainstream consciousness."}, {"name": "Modern Paranormal Research", "content": "Contemporary research combines scientific methodology with technological innovation."}, {"name": "Digital Age Investigation", "content": "Digital recording, social media, and online databases have transformed paranormal research."}],
        "faq": [{"q": "Who founded the SPR?", "a": "The Society for Psychical Research was founded in 1882 by Henry Sidgwick, Frederick Myers, and Edmund Gurney."}],
    },
    {
        "slug": "electronic-voice-phenomena",
        "title": "Electronic Voice Phenomena (EVP): The Science of Spirit Voices",
        "index_title": "Electronic Voice Phenomena (EVP): The Science of Spirit Voices",
        "desc": "Understanding Electronic Voice Phenomena and how EVP is captured and analyzed.",
        "keywords": "EVP, electronic voice phenomena, spirit voices, audio paranorma",
        "og_alt": "An EVP audio waveform with spectral analysis",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 7,
        "category": "paranormal",
        "excerpt": "EVP research has provided some of the most debated evidence in paranormal investigation.",
        "cta_apps": ["apps.ghost-hunting", "apps.parapsychology"],
        "related": [{"slug": "ghost-hunting-methods", "title": "Ghost Hunting Methods and Equipment Guide"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}],
        "howto": "Record in quiet environments, use proper session protocols, and analyze with audio software.",
        "toc": ["Introduction", "What is EVP?", "History of EVP", "Classes of EVP", "Recording Methods", "Analysis Techniques", "Skeptical Perspectives", "EVP in Modern Investigation"],
        "sections": [{"name": "Introduction", "content": "Electronic Voice Phenomena are unexpected voices or sounds captured on electronic recording devices."}, {"name": "What is EVP?", "content": "EVP refers to voices or sounds recorded on devices that were not audible during recording."}, {"name": "History of EVP", "content": "EVP gained prominence in the 1930s-40s through the work of Friedrich Jürgensen and others."}, {"name": "Classes of EVP", "content": "EVP is classified as Class A (clearly audible), Class B (audible with amplification), and Class C (faint, needs heavy processing)."}, {"name": "Recording Methods", "content": "Use digital recorders with external microphones in quiet, controlled environments."}, {"name": "Analysis Techniques", "content": "Spectral analysis, noise reduction, and waveform inspection help validate or debunk EVP findings."}, {"name": "Skeptical Perspectives", "content": "Skeptics attribute EVP to auditory pareidolia, radio interference, and equipment artifacts."}, {"name": "EVP in Modern Investigation", "content": "Despite skepticism, EVP remains a widely used tool in paranormal investigation."}],
        "faq": [{"q": "Is EVP real?", "a": "EVP remains debated. Some researchers report convincing evidence, while skeptics attribute findings to artifacts."}],
    },
    {
        "slug": "supernatural-teleportation",
        "title": "Supernatural Teleportation: Cases and Theories",
        "index_title": "Supernatural Teleportation: Cases and Theories",
        "desc": "Exploring reports of supernatural teleportation, object displacement, and bilocation.",
        "keywords": "teleportation, supernatural transport, bilocation, object displacement, poltergeist transport",
        "og_alt": "A mysterious scene of objects displaced in space",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 7,
        "category": "paranormal",
        "excerpt": "From bilocation to objects that seem to teleport, supernatural displacement defies explanation.",
        "cta_apps": ["apps.parapsychology", "apps.ghost-hunting"],
        "related": [{"slug": "paranormal-phenomena-types", "title": "Types of Paranormal Phenomena"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}],
        "howto": "Examine reported cases carefully and consider all conventional explanations before concluding supernatural cause.",
        "toc": ["Introduction", "Types of Supernatural Transport", "Bilocation", "Object Displacement", "The Bell Witch Case", "The Rosenheim Case", "Quantum Theories", "Conclusion"],
        "sections": [{"name": "Introduction", "content": "Reports of objects or people moving instantaneously from one location to another have persisted throughout history."}, {"name": "Types of Supernatural Transport", "content": "Supernatural transport includes teleportation, bilocation, levitation, and object displacement."}, {"name": "Bilocation", "content": "The ability to be in two places simultaneously, often reported by mystics and saints."}, {"name": "Object Displacement", "content": "Objects that appear in different locations without a discernible physical mechanism."}, {"name": "The Bell Witch Case", "content": "The Bell Witch of Tennessee reportedly moved objects and attacked visitors across distances."}, {"name": "The Rosenheim Case", "content": "Electrical and mechanical disruptions in a German law office defied conventional explanation."}, {"name": "Quantum Theories", "content": "Some researchers speculate about quantum entanglement or wormholes as mechanisms for teleportation."}, {"name": "Conclusion", "content": "Supernatural teleportation remains one of the most fascinating and least understood phenomena."}],
        "faq": [{"q": "Has anyone scientifically proven teleportation?", "a": "No, while quantum teleportation exists at the particle level, macroscopic supernatural teleportation remains unproven."}],
    },
    {
        "slug": "urban-legends-paranormal",
        "title": "Urban Legends and Their Paranormal Origins",
        "index_title": "Urban Legends and Their Paranormal Origins",
        "desc": "The intersection of urban legends and paranormal folklore around the world.",
        "keywords": "urban legends, paranormal folklore, creepypasta, paranormal stories",
        "og_alt": "A dark alleyway with shadowy figures representing urban paranormal folklore",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 7,
        "category": "paranormal",
        "excerpt": "Urban legends often have roots in genuine paranormal folklore, evolving with each retelling.",
        "cta_apps": ["apps.parapsychology", "apps.ghost-hunting"],
        "related": [{"slug": "paranormal-phenomena-types", "title": "Types of Paranormal Phenomena"}],
        "references": [{"title": "SPR Proceedings", "url": "https://spr.org"}, {"title": "Creepypasta Wiki", "url": "https://creepypasta.wikia.com"}],
        "howto": "Analyze urban legends by distinguishing their folkloric origins from modern creative embellishments.",
        "toc": ["Introduction", "What Are Urban Legends?", "Paranormal Folklore", "The Hookman", "The Vanishing Hitchhiker", "Black-Eyed Children", "Creepypasta and Digital Folklore", "Folkloric vs. Creative Legends", "Why Urban Legends Persist"],
        "sections": [{"name": "Introduction", "content": "Urban legends and paranormal folklore share a deep, intertwined history."}, {"name": "What Are Urban Legends?", "content": "Urban legends are modern folklore narratives that circulate as true stories."}, {"name": "Paranormal Folklore", "content": "Many urban legends have roots in genuine paranormal beliefs and historical events."}, {"name": "The Hookman", "content": "The Hookman legend warns of a killer with a hook for a hand, rooted in 1950s crime stories."}, {"name": "The Vanishing Hitchhiker", "content": "One of the oldest urban legends, involving a ghostly hitchhiker who disappears."}, {"name": "Black-Eyed Children", "content": "Modern urban legends of children with solid black eyes who ask to be let in."}, {"name": "Creepypasta and Digital Folklore", "content": "The internet has created a new genre of horror stories that function as modern urban legends."}, {"name": "Folkloric vs. Creative Legends", "content": "Distinguishing between folkloric origins and pure creative fiction requires careful analysis."}, {"name": "Why Urban Legends Persist", "content": "Urban legends persist because they tap into deep cultural fears and communal anxieties."}],
        "faq": [{"q": "Are all urban legends based on true events?", "a": "Many have kernels of truth or historical basis, but they are heavily embellished over time."}],
    },
]