ARTICLES_H = [
    {
        "slug": "72-goetia-demons-complete-list",
        "title": "The 72 Goetia Demons: Complete List and Meanings",
        "index_title": "The 72 Goetia Demons: Complete List and Meanings",
        "desc": "Explore all 72 demons of the Ars Goetia, their hierarchies, sigils, and the esoteric knowledge they guard.",
        "keywords": "goetia demons, ars goetia, 72 demons, demonology, sigils, occult, grimoire",
        "og_alt": "A mystical sigil glowing with arcane energy, representing the 72 Goetia demons",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 8,
        "category": "goetia",
        "excerpt": "The Ars Goetia, the first part of the Lesser Key of Solomon, contains the names and descriptions of 72 demons. We explore each one in detail.",
        "cta_apps": ["apps.sigils", "apps.runes"],
        "related": [{"slug": "the-book-of-samuels-magick", "title": "The Book of Samuel's Magick"}, {"slug": "goetian-demon-hierarchies", "title": "Goetian Demon Hierarchies"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}, {"title": "Sacred-Texts.com Goetia", "url": "https://sacred-texts.com/gs/goetia.htm"}],
        "howto": "This article serves as a reference guide. Use the sigil images and hierarchies to study each demon's nature and correspondences.",
        "toc": ["Introduction", "What is the Ars Goetia?", "The 72 Demons by Classification", "Sigils and Seals", "Working with Goetian Demons", "Ethical Considerations"],
        "sections": [{"name": "Introduction", "content": "The Ars Goetia forms the foundational grimoire of Western demonology, prescribing the summoning of 72 spirits."}, {"name": "What is the Ars Goetia?", "content": "The Lesser Key of Solomon, written circa 16th century, codifies the 72 demons into a hierarchical structure usable by practitioners."}, {"name": "The 72 Demons by Classification", "content": "The demons are divided into five cabinets: Jet, Eth, Oth, Phe, and Dof, each governed by a president."}, {"name": "Sigils and Seals", "content": "Each demon possesses a unique sigil that serves as a focal point for evocation and meditation."}, {"name": "Working with Goetian Demons", "content": "Traditional methods include evocation, talismanic work, and meditation on their respective seals."}, {"name": "Ethical Considerations", "content": "The Goetia demands respect, discipline, and knowledge. Preparation is essential before any interaction."}],
        "faq": [{"q": "Are Goetia demons real?", "a": "They exist as archetypal forces within the Western occult tradition, whether viewed as literal entities or psychological correspondences."}, {"q": "Can anyone summon a Goetia demon?", "a": "Traditional sources emphasize the need for rigorous preparation, knowledge, and ethical grounding."}],
    },
    {
        "slug": "king-paimon-goetia-demon",
        "title": "King Paimon: The Sixth Spirit of the Goetia",
        "index_title": "King Paimon: The Sixth Spirit of the Goetia",
        "desc": "Deep dive into King Paimon, the first of the four royal demons, his sigil, and his role in Goetian evocation.",
        "keywords": "paimon, king paimon, goetia, sixth spirit, demonology",
        "og_alt": "The royal sigil of King Paimon surrounded by spectral flames",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "King Paimon is the sixth spirit in the Ars Goetia and the first of the four great kings. Here is everything you need to know.",
        "cta_apps": ["apps.sigils", "apps.goetia"],
        "related": [{"slug": "72-goetia-demons-complete-list", "title": "The 72 Goetia Demons: Complete List and Meanings"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Study Paimon's sigil and characteristics. Meditate on his royal imagery to understand his energy.",
        "toc": ["Introduction", "Paimon's Hierarchy", "His Sigil and Symbolism", "Attributes and Powers", "How to Evoke Paimon"],
        "sections": [{"name": "Introduction", "content": "King Paimon stands as the first of the four royal demons in the Goetia, ruling with authority and wisdom."}, {"name": "Paimon's Hierarchy", "content": "As a king, Paimon commands 200 legions of spirits and governs the first cabinet of the Goetia."}, {"name": "His Sigil and Symbolism", "content": "Paimon's sigil depicts a crowned man on a camel, representing his royal dignity and swift movement."}, {"name": "Attributes and Powers", "content": "Paimon is known for revealing secrets, discovering hidden treasures, and bestowing wisdom."}, {"name": "How to Evoke Paimon", "content": "Traditional evocation involves his sigil, specific offerings, and a disciplined ceremonial approach."}],
        "faq": [{"q": "What does Paimon look like?", "a": "He appears as a crowned man riding a dromedary camel, often accompanied by music and trumpets."}],
    },
    {
        "slug": "goetia-cabinet-classification",
        "title": "Goetia Cabinet Classification: The Five Presidents",
        "index_title": "Goetia Cabinet Classification: The Five Presidents",
        "desc": "Understanding the five-cabinet classification of the 72 Goetia demons and their presidential rulers.",
        "keywords": "goetia cabinet, five presidents, jet, eth, oth, phe, dof, demonology",
        "og_alt": "A mystical chart showing the five Goetia cabinets and their presidential sigils",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 7,
        "category": "goetia",
        "excerpt": "The 72 Goetia demons are organized into five cabinets, each ruled by a powerful president. This is the complete classification.",
        "cta_apps": ["apps.runes", "apps.goetia"],
        "related": [{"slug": "72-goetia-demons-complete-list", "title": "The 72 Goetia Demons: Complete List and Meanings"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Use this classification to understand which cabinet and president a demon falls under for organized study.",
        "toc": ["Introduction", "The Five Cabinets", "Cabinet Jet (President Bune)", "Cabinet Eth (President Vine)", "Cabinet Oth (President Bifrons)", "Cabinet Phe (President Balam)", "Cabinet Dof (President Alloc)", "Summary Table"],
        "sections": [{"name": "Introduction", "content": "The five-cabinet system provides the organizational framework of the Ars Goetia."}, {"name": "The Five Cabinets", "content": "Each cabinet contains approximately 14-15 demons and is governed by a president who commands its legions."}, {"name": "Cabinet Jet (President Bune)", "content": "Jet's demons govern fortune, wealth, and material matters under President Bune."}, {"name": "Cabinet Eth (President Vine)", "content": "Eth's demons oversee hidden knowledge, secrets, and the unseen realm under President Vine."}, {"name": "Cabinet Oth (President Bifrons)", "content": "Oth deals with death, transformation, and the mysteries of the underworld under President Bifrons."}, {"name": "Cabinet Phe (President Balam)", "content": "Phe governs wisdom, prophecy, and spiritual insight under President Balam."}, {"name": "Cabinet Dof (President Alloc)", "content": "Dof rules the domains of the mind, dreams, and illusion under President Alloc."}, {"name": "Summary Table", "content": "A comprehensive table mapping all 72 demons to their cabinet, president, and classification."}],
        "faq": [{"q": "Why five cabinets?", "a": "The five-cabinet system mirrors the fivefold structure of many occult traditions, including the elemental and planetary systems."}],
    },
    {
        "slug": "goetia-evocation-basics",
        "title": "Goetia Evocation: A Practitioner's Guide",
        "index_title": "Goetia Evocation: A Practitioner's Guide",
        "desc": "Essential principles of Goetian evocation, from circle-casting to dismissing spirits, based on the Lesser Key of Solomon.",
        "keywords": "goetia evocation, evocation techniques, summoning demons, lesser key of solomon, ritual",
        "og_alt": "A practitioner casting a Goetian evocation circle with ritual implements",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 9,
        "category": "goetia",
        "excerpt": "Evoking Goetian demons requires precise methodology. This guide covers circle-casting, invocations, seals, and dismissals.",
        "cta_apps": ["apps.sigils", "apps.rituals"],
        "related": [{"slug": "72-goetia-demons-complete-list", "title": "The 72 Goetia Demons: Complete List and Meanings"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Follow the traditional steps: prepare your space, cast the circle, use the proper invocation, present the sigil, and dismiss the spirit.",
        "toc": ["Introduction", "Preparing Your Sacred Space", "The Magic Circle", "The Invocation of the Spirit", "Presenting the Sigil", "Receiving the Spirit", "Dismissal and Closing"],
        "sections": [{"name": "Introduction", "content": "Goetian evocation is a precise art that demands discipline, respect, and thorough preparation."}, {"name": "Preparing Your Sacred Space", "content": "Cleanse the area, set up your altar with appropriate offerings, and arrange your ritual tools."}, {"name": "The Magic Circle", "content": "The circle serves as a boundary between the practitioner and the spirit realm, drawn with a ritual knife or cord."}, {"name": "The Invocation of the Spirit", "content": "Recite the divine injunctions from the Lesser Key, using the correct name, number, and qualities of the demon."}, {"name": "Presenting the Sigil", "content": "Hold or display the demon's sigil as the focal point of the evocation to attract its attention."}, {"name": "Receiving the Spirit", "content": "Remain calm and focused. The spirit may appear in various forms—visual, auditory, or purely sensed."}, {"name": "Dismissal and Closing", "content": "Always dismiss the spirit respectfully and close the circle completely before leaving the working area."}],
        "faq": [{"q": "What if nothing happens?", "a": "Not every evocation produces visible results. Patience, practice, and proper preparation are essential."}],
    },
    {
        "slug": "goetia-vine-president",
        "title": "President Vine of Goetia: King of the West",
        "index_title": "President Vine of Goetia: King of the West",
        "desc": "Exploring President Vine, the ruler of the second cabinet in the Ars Goetia, and his 36 legions.",
        "keywords": "vine, president vine, goetia, king of the west, demonology",
        "og_alt": "The majestic sigil of President Vine standing before a western horizon",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "President Vine rules 36 legions of spirits and governs hidden knowledge, secrets, and the revelation of witches and sorcerers.",
        "cta_apps": ["apps.goetia", "apps.sigils"],
        "related": [{"slug": "goetia-cabinet-classification", "title": "Goetia Cabinet Classification: The Five Presidents"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Meditate on Vine's sigil and attributes when seeking knowledge of hidden matters or secret arts.",
        "toc": ["Introduction", "Vine's Rank and Authority", "His Sigil and Symbolism", "Powers and Abilities", "The 36 Legions"],
        "sections": [{"name": "Introduction", "content": "President Vine is the second of the four Goetian kings, presiding over the western cabinet."}, {"name": "Vine's Rank and Authority", "content": "As a king, Vine commands 36 legions and serves as a powerful ally in uncovering hidden truths."}, {"name": "His Sigil and Symbolism", "content": "Vine's sigil depicts a lion's head with a snake's tail, symbolizing the duality of revelation and concealment."}, {"name": "Powers and Abilities", "content": "Vine reveals hidden things, uncovers witches and sorcerers, and transports souls between worlds."}, {"name": "The 36 Legions", "content": "Vine commands 36 legions of spirits, each with specific domains related to secrets and hidden knowledge."}],
        "faq": [{"q": "What makes Vine unique among Goetian kings?", "a": "Vine's unique power lies in revealing hidden truths and uncovering those who practice secret arts."}],
    },
    {
        "slug": "goetia-bune-president-jet",
        "title": "President Bune of Goetia: Ruler of the First Cabinet",
        "index_title": "President Bune of Goetia: Ruler of the First Cabinet",
        "desc": "Examining President Bune, who governs the first cabinet of the Goetia and commands the legions of Jet.",
        "keywords": "bune, president bune, goetia, jet cabinet, demonology",
        "og_alt": "The sigil of President Bune surrounded by golden wealth symbols",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "President Bune rules the first cabinet of the Ars Goetia and is associated with wealth, honor, and wisdom.",
        "cta_apps": ["apps.goetia", "apps.sigils"],
        "related": [{"slug": "goetia-cabinet-classification", "title": "Goetia Cabinet Classification: The Five Presidents"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Invoke Bune when seeking financial abundance, honor, or wisdom in worldly matters.",
        "toc": ["Introduction", "Bune's Position in the Goetia", "Sigil and Symbolism", "Attributes and Powers", "Working with Bune"],
        "sections": [{"name": "Introduction", "content": "President Bune governs the first cabinet and is closely associated with material abundance and wisdom."}, {"name": "Bune's Position in the Goetia", "content": "Bune commands the first cabinet and presides over the legions of Jet, the element of air and fortune."}, {"name": "Sigil and Symbolism", "content": "Bune's sigil features a crowned head with three crowns, representing his tripartite authority over wealth, honor, and wisdom."}, {"name": "Attributes and Powers", "content": "Bune bestows wealth, honor, and wisdom, making him one of the most sought-after Goetian presidents."}, {"name": "Working with Bune", "content": "Works with Bune involve offerings of gold or wealth-related symbols, combined with focused intention on abundance."}],
        "faq": [{"q": "Is Bune related to wealth magic?", "a": "Yes, Bune is one of the primary Goetian spirits associated with attracting wealth and material abundance."}],
    },
    {
        "slug": "goetia-bifrons-oath-president",
        "title": "President Bifrons: Ruler of Death and Transformation",
        "index_title": "President Bifrons: Ruler of Death and Transformation",
        "desc": "Understanding President Bifrons, the fourth Goetian king who governs the mysteries of death and transformation.",
        "keywords": "bifrons, president bifrons, goetia, death, transformation, demonology",
        "og_alt": "The sigil of President Bifrons standing before a threshold between worlds",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "President Bifrons rules the third cabinet and commands the mysteries of death, transformation, and the passage of souls.",
        "cta_apps": ["apps.goetia", "apps.rituals"],
        "related": [{"slug": "goetia-cabinet-classification", "title": "Goetia Cabinet Classification: The Five Presidents"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Approach Bifrons only with serious intention regarding death, endings, or transformation work.",
        "toc": ["Introduction", "Bifrons' Domain", "His Sigil and Symbolism", "Powers and Responsibilities", "Working with Bifrons"],
        "sections": [{"name": "Introduction", "content": "President Bifrons governs the mysteries of death and transformation in the Goetia."}, {"name": "Bifrons' Domain", "content": "Bifrons rules over the passage of souls, the nature of death, and the alchemical transformation of matter and spirit."}, {"name": "His Sigil and Symbolism", "content": "His sigil depicts a ghastly face with a serpent's body, symbolizing the merger of death and renewal."}, {"name": "Powers and Responsibilities", "content": "Bifrons teaches the art of gems and precious stones, and governs the transformation of bodies and souls."}, {"name": "Working with Bifrons", "content": "Work with Bifrons when undergoing major life transitions, death work, or transformation rituals."}],
        "faq": [{"q": "Is Bifrons dangerous to work with?", "a": "Bifrons deals with profound mysteries of death. Proper preparation and respect are essential."}],
    },
    {
        "slug": "goetia-balam-president-phe",
        "title": "President Balam: Master of Wisdom and Prophecy",
        "index_title": "President Balam: Master of Wisdom and Prophecy",
        "desc": "Exploring President Balam, the third Goetian king who commands wisdom, prophecy, and the third cabinet.",
        "keywords": "balam, president balam, goetia, wisdom, prophecy, demonology",
        "og_alt": "The three-crowned sigil of President Balam emanating prophetic light",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "President Balam rules the third cabinet and is known for bestowing wisdom, understanding, and prophetic sight.",
        "cta_apps": ["apps.goetia", "apps.sigils"],
        "related": [{"slug": "goetia-cabinet-classification", "title": "Goetia Cabinet Classification: The Five Presidents"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Invoke Balam when seeking prophetic insight, wisdom, or understanding of hidden truths.",
        "toc": ["Introduction", "Balam's Hierarchy", "Sigil and Symbolism", "Powers and Gifts", "Working with Balam"],
        "sections": [{"name": "Introduction", "content": "President Balam commands the third cabinet and is revered for his gifts of wisdom and prophecy."}, {"name": "Balam's Hierarchy", "content": "Balam governs 40 legions and presides over the third cabinet of the Goetia."}, {"name": "Sigil and Symbolism", "content": "His sigil shows three crowned heads, representing wisdom, prophecy, and spiritual sight."}, {"name": "Powers and Gifts", "content": "Balam bestows wisdom, understanding, the ability to tame serpents, and the gift of prophecy."}, {"name": "Working with Balam", "content": "Works with Balam focus on meditation, prophetic development, and the cultivation of wisdom."}],
        "faq": [{"q": "What is Balam's gift of prophecy?", "a": "Balam grants the ability to perceive future events and understand hidden truths through prophetic sight."}],
    },
    {
        "slug": "goetia-alloc-president-dof",
        "title": "President Alloc: The Fifth Goetian King",
        "index_title": "President Alloc: The Fifth Goetian King",
        "desc": "Examining President Alloc, who governs the fifth and final cabinet of the Ars Goetia.",
        "keywords": "alloc, president alloc, goetia, fifth cabinet, demonology",
        "og_alt": "The sigil of President Alloc standing before a labyrinth of illusions",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 6,
        "category": "goetia",
        "excerpt": "President Alloc rules the fifth cabinet and commands the legions that govern dreams, illusions, and the mind.",
        "cta_apps": ["apps.goetia", "apps.rituals"],
        "related": [{"slug": "goetia-cabinet-classification", "title": "Goetia Cabinet Classification: The Five Presidents"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Work with Alloc when dealing with dream work, illusion, or mental exploration.",
        "toc": ["Introduction", "Alloc's Domain", "His Sigil and Symbolism", "Powers and Attributes", "Working with Alloc"],
        "sections": [{"name": "Introduction", "content": "President Alloc governs the fifth and final cabinet of the Goetia, overseeing dreams and illusions."}, {"name": "Alloc's Domain", "content": "Alloc rules the realm of dreams, illusions, and the labyrinthine pathways of the mind."}, {"name": "His Sigil and Symbolism", "content": "His sigil features a man riding a strong camel, representing the journey through dream realms."}, {"name": "Powers and Attributes", "content": "Alloc discovers hidden things, knows the thoughts of men, and governs the realm of sleep and dreams."}, {"name": "Working with Alloc", "content": "Invoke Alloc for dream work, lucid exploration, and understanding the nature of illusion and perception."}],
        "faq": [{"q": "What is Alloc's role in dream work?", "a": "Alloc governs the realm of sleep and dreams, making him a key spirit for dream exploration and lucid dreaming."}],
    },
    {
        "slug": "goetia-ethics-and-safety",
        "title": "Goetia Ethics and Safety: A Responsible Practitioner's Guide",
        "index_title": "Goetia Ethics and Safety: A Responsible Practitioner's Guide",
        "desc": "The essential ethical framework and safety protocols for working with Goetian demons responsibly.",
        "keywords": "goetia ethics, demon safety, responsible practice, occult safety, evocation ethics",
        "og_alt": "A protective circle with ethical symbols and safety sigils",
        "date_iso": "2026-09-04",
        "date_display": "September 4, 2026",
        "lastmod": "2026-09-04",
        "read_min": 8,
        "category": "goetia",
        "excerpt": "Working with Goetian demons demands ethical grounding, rigorous preparation, and respect for the spirits involved.",
        "cta_apps": ["apps.rituals", "apps.sigils"],
        "related": [{"slug": "goetia-evocation-basics", "title": "Goetia Evocation: A Practitioner's Guide"}],
        "references": [{"title": "Lesser Key of Solomon", "url": "https://example.com/lesser-key-solomon"}],
        "howto": "Always prepare thoroughly, use proper protections, and approach each Goetian spirit with respect and clear intention.",
        "toc": ["Introduction", "The Principle of Respect", "Preparation and Knowledge", "Protective Measures", "The Divine Injunctions", "Dismissal Protocols", "Psychological Safety", "When to Seek Guidance"],
        "sections": [{"name": "Introduction", "content": "Ethics and safety are foundational to any Goetian practice. Without them, the work becomes dangerous."}, {"name": "The Principle of Respect", "content": "Every Goetian demon is a powerful entity that demands respect, accurate naming, and proper protocol."}, {"name": "Preparation and Knowledge", "content": "Thorough study of the Lesser Key, understanding the spirit's nature, and preparing offerings are non-negotiable."}, {"name": "Protective Measures", "content": "The magic circle, divine injunctions, and proper sigil work provide essential protections for the practitioner."}, {"name": "The Divine Injunctions", "content": "The divine injunctions from the Lesser Key of Solomon are the primary safety mechanism for Goetian evocation."}, {"name": "Dismissal Protocols", "content": "Always dismiss spirits completely before leaving the working space. Never leave a spirit lingering."}, {"name": "Psychological Safety", "content": "Know your mental and emotional state. Do not perform evocations when unsettled, ill, or distracted."}, {"name": "When to Seek Guidance", "content": "If unsure about any aspect of a working, consult experienced practitioners or halt the operation entirely."}],
        "faq": [{"q": "What is the most important safety rule?", "a": "Always use the complete divine injunctions from the Lesser Key of Solomon and never skip the dismissal protocol."}],
    },
]