"""Known-entity dictionary, built from the channel's own titles.

Problem it solves
-----------------
`entity_filter.refine` only finds an entity when the title *announces* it
("Invoking ZORAY: ..."). Several high-value videos instead name a known entity
mid-sentence -- "Complete Guide to Making a Pact with Clauneck for Infinite
Wealth" -- so they fell through to the generic topic path and produced headings
like "a money sigil for Complete Guide Making".

Fix: two passes. Pass 1 collects every entity the parser can already see. Pass 2
re-scans all titles for those names, case- and accent-insensitively, so a video
that merely *mentions* a known entity is treated as an article about it.

Regenerate with:  python build_entities.py
"""
import json
import os
import re
import sys

import titles as T
import entity_filter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
VIDEOS = os.path.join(ROOT, "projects", "research", "yt_videos_classified.json")
OUT = os.path.join(HERE, "entities.py")

# Tokens too generic to anchor an article, even if they are proper nouns.
_GENERIC = {
    "demo", "channel", "video", "videos", "music", "song", "playlist",
    "serie", "series", "parte", "part", "ep", "episodio", "episode",
    "practica", "practice", "resultados", "results", "test", "review",
    "comentarios", "comments", "precio", "price", "gratis", "free", "nuevo",
    "new", "mejor", "best", "top", "guia", "guide", "completo", "complete",
    "parte", "segunda", "parte", "final", "intro", "outro",
}

_MIN_LEN = 4


def _key(s):
    return T.norm_key(s)


def build():
    with open(VIDEOS, "r", encoding="utf-8") as fh:
        videos = json.load(fh)

    # Pass 1: entities the parser already resolves.
    found = {}
    for v in videos:
        e = entity_filter.refine(v["title"])
        if not e:
            continue
        k = _key(e)
        if len(k) < _MIN_LEN or k in _GENERIC or any(ch.isdigit() for ch in k):
            continue
        found.setdefault(k, e)

    # Pass 2: match those names against every title.
    keys = sorted(found, key=len, reverse=True)
    assigned = {}
    for v in videos:
        e = entity_filter.refine(v["title"])
        if e:
            assigned[v["id"]] = (e, "declared")
            continue
        hay = _key(T.clean_title(v["title"]))
        hit = None
        for k in keys:
            if re.search(r"(?<!\w)" + re.escape(k) + r"(?!\w)", hay):
                hit = found[k]
                break
        if hit:
            assigned[v["id"]] = (hit, "mentioned")

    lines = [
        '"""Generated by build_entities.py -- do not edit by hand."""',
        "",
        "# entity name (as it should appear in a heading) -> regex-safe key",
        "KNOWN_ENTITIES = {",
    ]
    for k in sorted(found):
        lines.append("    %r: %r," % (found[k], k))
    lines.append("}")
    lines.append("")
    lines.append("GENERIC_TOKENS = frozenset(%r)" % (sorted(_GENERIC),))
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    return len(found), assigned, videos


_ENTITY_RE = None
_ENTITY_RE_NAMES = {}


def _regex():
    global _ENTITY_RE, _ENTITY_RE_NAMES
    if _ENTITY_RE is None:
        from entities import KNOWN_ENTITIES
        parts = []
        for name, k in sorted(KNOWN_ENTITIES.items(), key=lambda kv: -len(kv[1])):
            parts.append("(?P<e%d>\\w*(?<!\\w)%s(?!\\w)\\w*)" % (len(parts), re.escape(k)))
        _ENTITY_RE = re.compile("|".join(parts)) if parts else None
        _ENTITY_RE_NAMES = KNOWN_ENTITIES
    return _ENTITY_RE


def match(title):
    """Return (entity_name, 'declared'|'mentioned') or (None, None)."""
    e = entity_filter.refine(title)
    if e:
        return e, "declared"
    rx = _regex()
    if rx is None:
        return None, None
    m = rx.search(_key(T.clean_title(title)))
    if m:
        key = m.group(0)
        return _ENTITY_RE_NAMES.get(key, key.title()), "mentioned"
    return None, None


if __name__ == "__main__":
    n, assigned, videos = build()
    declared = sum(1 for v in videos if assigned.get(v["id"], ("", ""))[1] == "declared")
    mentioned = sum(1 for v in videos if assigned.get(v["id"], ("", ""))[1] == "mentioned")
    print("known entities:", n)
    print("declared:", declared, "mentioned:", mentioned,
          "topic:", len(videos) - declared - mentioned)
