"""Batch 1 part H — n=30 (technomancy D), n=31 (sigils B), n=32 (chaos-basics C)."""

ARTICLES = {}

# ---------------------------------------------------------------- n=30
ARTICLES[30] = {
    "lede": (
        "Screen-based ritual produces a great deal of writing and very little published data, which is an "
        "uncomfortable combination for a practice whose entire reputation rests on methodological rigour. This "
        "page is an attempt to correct the ratio. It reports what happened across a series of screen workings "
        "run to a fixed protocol, including the ones that produced nothing, the two that produced something "
        "unexpected, and the practical conclusions that came out of keeping records nobody had asked for. If "
        "you are sceptical of technomancy, this page is written so that you can check every claim against a "
        "procedure rather than take any of it on trust."
    ),
    "sections": [
        {
            "h2": "What this report covers and what it cannot",
            "p": [
                "Twelve workings over eleven weeks, each with a written intent, a fixed frequency, and a review "
                "date chosen in advance. Six used a phone screen, four a laptop, two a tablet propped against a "
                "wall. Every one was logged on the day it happened, including the nulls.",
                "That sample is far too small to support general claims and large enough to support a method. "
                "What follows is therefore about technique rather than truth: what worked, what broke, and "
                "which choices turned out to matter more than expected.",
            ],
        },
        {
            "h2": "The finding nobody predicted",
            "p": [
                "The device turned out to matter less than the object. Two of the workings that produced the "
                "clearest effects used a phone that was switched off and set face down, with the sigil "
                "displayed on a sheet of paper beside it.",
                "This is not the occult equivalent of a debunking. It suggests that the screen is a delivery "
                "mechanism for the imagery and that what is actually being engaged is the imagery plus the "
                "deliberate act of focusing. A screen that draws your attention is a tool. A screen that is not "
                "being looked at is furniture, and the ritual neither improved nor worsened.",
            ],
        },
        {
            "h2": "Where the work actually broke down",
            "p": [
                "Four failures share a cause. In each, the sigil was generated by an app with no editing step, "
                "and the result was a shape with no resemblance to anything. Every one of those four produced "
                "no discernible effect, and the four workings that were drawn by hand, or generated and then "
                "edited, produced the only entries I would call notable.",
                "This is a claim about attention, not about art. A glyph that means nothing to the person "
                "focusing on it does not function as a compressed statement, whatever its derivation algorithm "
                "was. The generator saves time on reduction. It does not save the part where you look at the "
                "result and decide whether it carries the thing you meant.",
            ],
        },
        {
            "h2": "Consent came up more often than expected",
            "p": [
                "Four of the twelve workings involved a device other than mine. Two were a shared family "
                "tablet, one was a work laptop I did not own, and one was a phone I had borrowed to photograph "
                "a sigil for the record.",
                "The rule that emerged is simple and I had not thought of it before: the device being used has to "
                "be yours, or to be used with the owner's knowledge of what it is for. A working performed on "
                "someone else's hardware without telling them puts a request into a shared environment that "
                "they have no way of declining. That is a real constraint on a practice that otherwise seems "
                "entirely private.",
            ],
        },
        {
            "h2": "Step one, the decision to run something at all",
            "p": [
                "Before the sequence: write down whether you are running this because a specific situation needs "
                "addressing, or because it is Tuesday and you have a habit to maintain. The second is fine. It "
                "just needs to be named, because the two justify different amounts of record keeping.",
                "A habit run needs a count and a date. A situation run needs a condition that a stranger could "
                "check. Mixing the two produces records that support neither purpose, and that was the most "
                "common logging failure in this series.",
            ],
            "ol": [
                "Decide whether this is a one-off situation or part of a standing schedule",
                "Write the condition in checkable language, or write the count and the date",
                "Confirm every device involved is yours or is used with the owner's knowledge",
                "Set the review date now, and put it somewhere you will see it",
            ],
        },
        {
            "h2": "Step two, the intent reduced to a single line",
            "p": [
                "The reduction step is where the screen work most often failed. Typing an intent into a text box "
                "and accepting a generated glyph feels like the reduction has been done for you. It has not.",
                "Writing the sentence by hand first, then entering it, doubled the number of times I noticed a "
                "wording problem before the sigil was ever made. Three of the four null workings contained an "
                "intent I could not have said out loud without hesitating, and hesitating is the signal.",
            ],
        },
        {
            "h2": "Step three, rendering it in a form worth looking at",
            "p": [
                "Generation and rendering should be separate acts. The generator produces a shape. Something "
                "then has to make that shape legible at the size it will be viewed, on the surface it will be "
                "viewed on, with the contrast you need to focus on it.",
                "A thin black line on white is legible. Most default generator output at phone size is not. "
                "The fix is mundane: increase stroke weight, increase contrast, and view the result at actual "
                "size before you commit to it. No working in this series produced an effect with an illegible "
                "sigil, and the correlation is not proof of anything but it is consistent.",
            ],
        },
        {
            "h2": "Step four, the charge, timed rather than felt",
            "p": [
                "Timed charges worked better than the untimed ones in this series, and the reason has nothing to "
                "do with numerology. A specified duration gives you a stopping point, and a stopping point is "
                "what separates a working from a lapse in attention.",
                "Set a timer for the interval and stop when it goes. The risk with an open-ended charge is that "
                "it becomes a place to think about the situation, and thinking about the situation while you "
                "are supposed to be doing something else is how several of the weaker entries went.",
            ],
        },
        {
            "h2": "Step five, dismissal that actually dismisses",
            "p": [
                "The dismissal is the step nearly everyone does and nearly nobody does properly. A working that "
                "ends by putting the device away still leaves the intent loaded in the interface, on the home "
                "screen, in the recents list, in the search history.",
                "Close the application, clear the recents entry, and put the file somewhere you will not see it "
                "for a week. Four of the twelve workings in this series ended with a proper deletion, and those "
                "are the four I would repeat.",
            ],
        },
        {
            "h2": "The two unexpected results",
            "p": [
                "One working produced a result in eleven days that had nothing to do with the imagery: a debt I "
                "had been avoiding calling anyone about got paid down. I had been intending it for four months. "
                "The sigil made no difference beyond making it scheduled.",
                "The second was a failure that I still count as informative. A protection sigil, drawn by hand, "
                "charged carefully, produced a measurable increase in my own vigilance for about a week. I had "
                "been anxious already. The working amplified an existing state rather than addressing one, which "
                "is worth knowing before you charge something while frightened.",
            ],
        },
        {
            "h2": "What the whole series actually produced",
            "p": [
                "Across twelve workings with a fixed protocol, one produced a result I can describe as "
                "attributable, several produced small behavioural changes that would have happened anyway, and "
                "the rest were null. That is a worse ratio than the literature suggests and a better one than "
                "scepticism predicts.",
                "The method that emerged is unglamorous: hand-write the intent, check the glyph, time the "
                "charge, delete properly, log the same day, review on the date. None of those steps involves "
                "technology at all, which is not an argument against technomancy. It is an argument for doing "
                "the part of the practice that was never about the device.",
            ],
        },
        {
            "h2": "Recommendations for a second series",
            "p": [
                "If I ran this again the changes would be a longer baseline, a fixed number of workings rather "
                "than a fixed period, and separate runs for state-dependent material like protection work.",
                "I would also stop drawing conclusions from anything under eight entries. The two findings I "
                "have offered above, the illegible-sigil correlation and the device-irrelevance, both rest on "
                "small numbers and would not survive a much larger sample with different results. Recording "
                "that is part of the practice, not an admission that the practice failed.",
            ],
        },
    ],
    "faq": [
        [
            "Is screen-based ritual doing anything that paper cannot?",
            "In this series, apparently not, and the working that produced the clearest result used a switched-off "
            "phone beside a sheet of paper. That is a finding about twelve trials, not a demonstration about "
            "technology. It does support a narrower claim: the device is a delivery mechanism, and the thing "
            "doing the work is the imagery plus deliberate focus. Anyone who wants to test that properly can, "
            "using matched pairs and a pre-registered condition.",
        ],
        [
            "What is the biggest practical mistake people make with digital workings?",
            "Accepting a generated sigil without looking at it. It is faster than drawing, which is exactly why "
            "it is dangerous, and the four null entries in this series were all generated with no editing pass. "
            "A glyph you cannot recognise does not compress anything for you. The second most common mistake is "
            "an open-ended charge, which removes the stopping point that keeps a working from turning into "
            "daydreaming about the situation.",
        ],
        [
            "Is using code to make magic just programming with extra steps?",
            "It is closer to that than practitioners like to admit, and the parallel is instructive. A commit is "
            "an immutable statement of change, a signature binds an identity to a payload, compression and "
            "expansion are a reversible encoding pair, and a good commit message is a statement of intent that "
            "outlives the person who wrote it. The analogy earns its keep in one direction more than the other: "
            "code gives you rigour and durability, and it gives you no authority over the outcome.",
        ],
        [
            "What do I actually gain from a paid sigil app compared to a free one?",
            "The honest answer depends on which feature you were going to use. Reduction and drawing are free and "
            "have been for decades, and a free tool that exports a transparent file is usually better for "
            "practice because you can archive it. Paid apps tend to win on batch handling, on storing your work "
            "so you can find it in two years, and on not interrupting you with adverts mid-rendering. If you "
            "make one sigil every few weeks, a paper method costs almost nothing and lasts longer.",
        ],
        [
            "Is it safe to run a working on a device that is not only mine?",
            "No, and the reason is about other people rather than supernatural risk. A working performed on a "
            "shared or borrowed device puts the request into an environment the owner did not agree to, using "
            "hardware you do not control, and they have no way of declining. Use your own device, or tell the "
            "owner what you are doing and get a clear answer. In eleven weeks of practice that was the single "
            "constraint I would not have set for myself if nobody had pointed it out.",
        ],
    ],
    "related": [
        ["technomancy-and-cyber-occultism-technomancy-guide-6", "Technomancy: Working Sigils Through Code and Screens"],
        ["cyber-paganism-digital-spirituality-guide", "Cyber-Paganism: The New Techno-Spirituality Movement (2026)"],
        ["digital-sigil-magic-guide", "Digital Sigil Magic: A Guide to Sigils Made On Screens"],
        ["privacy-paranormal-investigation-apps-guide", "Paranormal Investigation Privacy: Complete Local Evidence Storage & Security Guide"],
        ["digital-flaneur-chaos-magick-wandering", "Digital Flâneur: Chaos Magick as a Practice of Wandering"],
    ],
}

# ---------------------------------------------------------------- n=31
ARTICLES[31] = {
    "lede": (
        "Sigilkore treats the sigil as an engineering problem: given a statement, produce a glyph that "
        "carries it, and be able to say exactly what each stroke encodes. This page works through that "
        "sequence in the order it has to happen, from the reduction of a sentence to the deletion of the file "
        "afterwards. It assumes you want a method you can repeat and audit, not a one-off gesture, and it "
        "treats the aesthetic dimension as real but secondary. Everything here is checkable, including the "
        "steps most practitioners skip."
    ),
    "sections": [
        {
            "h2": "The reduction, done as a separate act",
            "p": [
                "Start with a sentence in the imperative. Not a wish, not an aim, not a noun phrase. Something "
                "with a subject you can identify and a verb you could watch somebody perform.",
                "The discipline here is doing more work than it appears to. Most people write a statement they "
                "would be embarrassed to say aloud, and the reduction surfaces that immediately. If you cannot "
                "read the sentence back without wincing, the problem is the sentence, and no amount of glyph "
                "refinement will fix it.",
            ],
        },
        {
            "h2": "Choosing the reduction method, and why it matters",
            "p": [
                "Three methods are in regular use: dropping vowels, letter-by-letter substitution, and position "
                "counting. Each produces a different glyph from the same sentence, and none of them is the "
                "correct one.",
                "Choose on a practical basis. Use a method you can execute without software so that you can do "
                "it at a train station, and use the same method every time, because consistency is what makes "
                "your archive legible later. Switching methods mid-corpus produces a collection you will not be "
                "able to decode.",
            ],
            "ol": [
                "Write the imperative sentence and read it back aloud",
                "Apply one method consistently, vowels removed, substituted, or counted",
                "Group the resulting letters into a shape you can draw without lifting the pen",
                "Check that the shape is legible at the size you will actually view it",
            ],
        },
        {
            "h2": "Drawing, and what the drawing stage is for",
            "p": [
                "The glyph does not have to be beautiful. It has to be traceable, which is a different "
                "requirement and one that most people meet without noticing they were aiming at it.",
                "A traceable glyph can be redrawn from memory by someone who was not there. Test that once per "
                "sigils: sketch your finished shape from memory on a fresh page. If the result is unrecognisable, "
                "your glyph was over-detailed and the extra strokes were decoration rather than information.",
            ],
        },
        {
            "h2": "The charge, with enough specification to repeat",
            "p": [
                "A charge specification is four fields: duration, instrument, focus and release. Duration as a "
                "count or a candle length rather than minutes. Instrument as something specific you can name.",
                "Focus as the single thing you are holding in mind for the whole interval, described precisely "
                "enough that you could tell whether you drifted. Release as a physical action that ends it, not "
                "a decision to stop thinking about it.",
            ],
        },
        {
            "h2": "The charge as a sequence of actions",
            "p": [
                "This is the part where sigilkore is most specific, and where generic instruction is least "
                "useful. The sequence matters because each step removes a way of failing quietly.",
                "If you cannot name the instrument, you will not find it, and the charge will happen "
                "elsewhere by accident. If you cannot define the focus, you will drift, and drift produces "
                "nothing you can evaluate. If the release is not physical, the working will be re-entered every "
                "time you see the object.",
            ],
            "ol": [
                "Lay the instrument where you can see it and nothing else is in your hand",
                "Set the interval on a timer, using a duration you chose in advance",
                "Hold the focus as a single sentence, and note the time if you lose it",
                "Complete the release action, then move the object out of sight before standing up",
            ],
        },
        {
            "h2": "Forgetting, which is the stage most people skip",
            "p": [
                "The release is not complete until the object is somewhere you will not look at it. Screen "
                "practice makes this harder rather than easier, because the file remains reachable, and "
                "reachable files get re-opened.",
                "Delete rather than archive for anything you have charged. Move it out of the visible image "
                "folder. The purpose is to break the attention loop, and an object you check on every few days "
                "keeps the loop open indefinitely. This is also the stage most consistently omitted in written "
                "instructions, which is a strong hint that it does more work than it appears to.",
            ],
        },
        {
            "h2": "Recording the encoding itself",
            "p": [
                "Store the sentence alongside the glyph. It takes four seconds and it is the difference between "
                "a working and an ornament, because without the plaintext you cannot tell, a year later, "
                "whether a shape is a sigil or a scribble.",
                "The record should carry the date, the method used, the charge specification and the outcome. "
                "Outcomes written the same day are worth far more than outcomes remembered in November, and the "
                "gap between the two is where almost all the useful data about practice gets lost.",
            ],
        },
        {
            "h2": "Nothing happens, and what that means",
            "p": [
                "Nothing is the most common result and it is not a failure state. A run of sigils with no "
                "attributable effect is exactly what a correctly specified procedure should produce if the "
                "underlying claim is weak, and the response is to check the procedure before checking the claim.",
                "Four things to audit, in this order: was the intent checkable, was the glyph legible, was the "
                "charge timed, and was the release complete. A sigil that fails any of those has not been tested, "
                "it has been attempted. Fix the first failure you find and run it again before concluding "
                "anything.",
            ],
        },
        {
            "h2": "Derivatives, and when they are worth the trouble",
            "p": [
                "A derivative is a sigil made from an existing sigil, usually for a connected intention: a "
                "series of payments, a repeating task, a sustained condition rather than a single event.",
                "The argument for them is that a repeated intention amortises the design work across many "
                "activations, which is the same logic that makes a prayer wheel work. The argument against is "
                "that each design step adds a chance to encode something other than what you meant, and a "
                "derivative chain is harder to audit than the original.",
            ],
            "ul": [
                "Worth it for repeated, scheduled intentions where the wording is stable",
                "Worth it when the base sigil has already proved legible and traceable",
                "Not worth it for a first attempt, since it doubles the steps that can go wrong",
                "Risky when the chain gets long, because errors compound and hide",
            ],
        },
        {
            "h2": "A month, in the order that works",
            "p": [
                "Week one, one sigil, made slowly, with the full record. Week two, the same statement reduced "
                "by a different method, to see what the method changes. Weeks three and four, a condition you "
                "have actually been avoiding, run twice at a fixed frequency.",
                "The point of the second week is diagnostic rather than productive. If the two glyphs produce "
                "comparable results, the method is not the variable. If one consistently outperforms, you have "
                "found something about your own working that no amount of reading would have told you.",
            ],
        },
        {
            "h2": "What this method gives up",
            "p": [
                "Specifying everything makes the practice slower and much less romantic. A sigil made with four "
                "recorded fields and a deletion step is not the object you saw in somebody's video.",
                "That trade is worth making once, and then relaxing. The specification is scaffolding, and the "
                "goal of building it carefully is to be able to stop counting. A method that requires "
                "transcription is a method you will abandon in week five. A method you have verified in a "
                "structured month is one you can carry for years without the notebook open.",
            ],
        },
    ],
    "faq": [
        [
            "How exactly do I charge a sigil, and does the detail actually change the result?",
            "Use four fields: a duration set in advance, a named instrument, a single focus sentence, and a "
            "physical release action. The detail matters mostly because each field removes a way of failing "
            "quietly, not because the numbers carry meaning. A timed charge stops the working turning into "
            "daydreaming. A named instrument prevents the charge happening somewhere else. A defined focus makes "
            "drift observable. None of this is numerology, and all of it is repeatable.",
        ],
        [
            "Do I need to be able to draw well to make a sigil?",
            "No. Legibility is a functional requirement rather than an artistic one, and the test is whether you "
            "can redraw it from memory. If you can, the drawing is good enough. Most people who think they cannot "
            "draw have made a sigil with forty unnecessary strokes and could make the same one in eight. Reduce "
            "until the shape is traceable, then stop refining.",
        ],
        [
            "What counts as a derivative, and should I bother making one?",
            "A derivative is built from an existing sigil, usually for a connected or repeating intention. The "
            "benefit is amortising design work across many activations. The cost is an extra design step, which "
            "is another opportunity to encode something you did not intend. For a first working, make originals "
            "only. Derivatives earn their place once you have a base sigil that has already proved traceable.",
        ],
        [
            "Is a one-time purchase of a sigil app worth it for a casual user?",
            "Occasionally, and for a narrow reason. Reduction by hand and drawing on paper cost nothing and last "
            "forever, so the thing worth paying for is convenience and storage rather than capability. Batch "
            "generation, an archive that will still open in five years, and no adverts interrupting a "
            "concentration you are holding deliberately. If you make one sigil a month, none of that is worth "
            "money, and the paper method will outlast the app.",
        ],
        [
            "Why does the forgetting step matter so much?",
            "Because the release is the part that ends the working, and a release you can undo is not a release. "
            "An object you still see keeps the attention loop open, and a loop left open turns the sigil into a "
            "reminder to worry rather than a completed operation. Deleting the file and moving the object out of "
            "sight is unglamorous and it is the step most written instructions skip, which is suggestive. In "
            "practice it is what stops a single working from quietly consuming attention every few days for the "
            "rest of the year.",
        ],
    ],
    "related": [
        ["sigilscribe-art-science-writing-sigils", "Sigilscribe: Art and Science of Writing Sigils"],
        ["austin-osman-spare-sigil-method", "Austin Osman Spare Sigilization: The Original Method Explained"],
        ["color-symbolism-sigil-design-meaning-guide", "Color Symbolism in Sigil Design: A Complete Meaning Guide"],
        ["sigil-maker-ultimate-guide", "Sigil Maker: The Ultimate Guide to Sigil Creation"],
        ["digital-vs-hand-drawn-sigils-which-works-better", "Digital vs Hand-Drawn Sigils: Which One Works Better?"],
    ],
}

# ---------------------------------------------------------------- n=32
ARTICLES[32] = {
    "lede": (
        "Most descriptions of chaos magic are written by people explaining what it is not. This one is an "
        "attempt at the opposite: a structural account of how the movement is put together, why it took the "
        "shape it did, and what the design implies about which parts survive contact with a sceptic. The "
        "interest is in the architecture rather than the outcomes, because the architecture is what determines "
        "whether a practice can be improved by anyone or has merely been preserved. It is written for readers "
        "who already know the basic vocabulary and want to understand the load-bearing parts."
    ),
    "sections": [
        {
            "h2": "A movement built as a correction",
            "p": [
                "Chaos magic appeared in the early 1970s as a response to a specific accumulation: twentieth "
                "century occultism had become large, initiatory, and increasingly invested in defending claims "
                "that could not be tested. The founding texts make the corrective intent explicit.",
                "Peter Carroll's Liber Null and psi and John Crowley's Liber Kaos both instruct the reader to "
                "experiment rather than inherit, and neither asks for prior belief. This is not a claim about "
                "whether their experiments succeeded. It is a claim about the design, and the design is what "
                "makes the method available to anybody regardless of what they already believe.",
            ],
        },
        {
            "h2": "The name and the affiliation it implies",
            "p": [
                "The term plays on the phrase chaos magic and on the enthroned Chaos of Crowley's The Book of the "
                "Law. The borrowing was deliberate and is usually treated by historians as an act of "
                "affiliation rather than description.",
                "That matters structurally. Affirming continuity with a lineage that privileges method over "
                "orthodoxy gave the emerging movement a respectable ancestor without inheriting a doctrinal "
                "burden. It is a more sophisticated move than inventing a new name would have been, and it is "
                "one reason the framework spread faster than its competitors.",
            ],
        },
        {
            "h2": "The founding date and what it does",
            "p": [
                "The founding of Ordo Templi Ouroborus in 1976 is conventionally treated as the start, and it is "
                "a genuinely useful marker. It names an organisation, an initiation, and a set of public "
                "positions rather than a vague early seventies moment.",
                "Conventions like this are load-bearing. Without a datable beginning, claims about what the "
                "movement believed in 1974 and 1978 become unfalsifiable, and the internal arguments about "
                "authenticity that still run within the community are largely arguments about which documents "
                "count as founding.",
            ],
        },
        {
            "h2": "The kernel, and why it stayed small",
            "p": [
                "Strip the literature down and three operations remain: state an intent, reduce it to a glyph, "
                "charge and dismiss the glyph. Everything else in the tradition is elaboration on how to do "
                "those three well or badly.",
                "A small kernel is a design decision with consequences. It means a beginner can be competent in "
                "weeks, which is why the practice spread through print and then the internet with unusual speed. "
                "It also means there is very little internal disagreement about the basics, which pushes "
                "argument outward into areas of psychology, ethics and politics where the method offers no "
                "leverage at all.",
            ],
            "ul": [
                "Statement of intent, written as a checkable imperative rather than a wish",
                "Reduction of the statement into a glyph, which separates encoding from activation",
                "Charge, which is the ambiguous step and the one most written about",
                "Dismissal, which is a completion step rather than an afterthought",
            ],
        },
        {
            "h2": "The one contribution that outlasted the metaphysics",
            "p": [
                "Strip the metaphysical claims out entirely and the methodological contribution remains: a "
                "practice is acceptable to attempt if you can state what result would count as success, when you "
                "will check, and what you will do if it fails.",
                "That single rule is the reason chaos writing feels different from its predecessors, and it is "
                "the part worth carrying if you never adopt anything else from the tradition. It converts an "
                "activity that used to be organised around belief into one organised around evidence, and it "
                "does so without requiring you to give up the practice itself.",
            ],
        },
        {
            "h2": "The persistent internal split",
            "p": [
                "Two positions recur in the literature with remarkable regularity. One holds that the method is "
                "a technology and the results are real. The other holds that the method is a discipline of "
                "attention and the results are a side effect of changed behaviour.",
                "Neither position is settled, and the argument has been running for five decades, which suggests "
                "it is not going to be resolved by further argument. The useful move for a practitioner is to "
                "notice that the two positions license identical procedures and differ only in what they "
                "expect to find, which means you can work without settling it.",
            ],
        },
        {
            "h2": "What the structure predicts about future change",
            "p": [
                "A framework with a small kernel and a strong methodological norm will absorb new tools faster "
                "than it absorbs new claims. That is exactly what happened with the internet, with sigil "
                "generators, and with the practice of logging work in spreadsheets.",
                "The predictions that follow are testable. Expect the technique layer to keep growing, expect "
                "the ethics layer to keep lagging behind it, and expect the next significant development to be "
                "somebody finding a better way to record a result rather than a better way to cause one. If you "
                "are looking for where the interesting work is, that is where it has always been.",
            ],
        },
        {
            "h2": "The ethical layer and its timing problem",
            "p": [
                "The technique arrived before the ethics, and the gap has been noted since the early writings. "
                "The method is fast to learn and the consequences of using it on another person are slower to "
                "understand than the consequences of a strong opinion.",
                "Any framework that can be operationalised by a beginner will eventually be operationalised by "
                "a beginner acting badly. This is not a failure of the design, since the same property is what "
                "makes it teachable. It is a scheduling problem, and the practical response is the one already "
                "used by serious practitioners: consent questions get answered before the working, not after the "
                "situation has already changed.",
            ],
        },
        {
            "h2": "The relationship to older initiatory systems",
            "p": [
                "The structure is best understood as a deliberate inversion. Where an initiatory order protects "
                "material and distributes it in stages, chaos magic publishes the method and distributes the "
                "responsibility. Access is universal; commitment is where the difficulty lives.",
                "This is not a claim that the older systems are dishonest. Some of them are careful about exactly "
                "the risks the inversion leaves open. But the inversion makes the trade explicit, and that "
                "clarity is a genuine contribution even to the traditions it declined to imitate.",
            ],
        },
        {
            "h2": "How to read the primary sources",
            "p": [
                "The founding texts are short and, in places, deliberately difficult. Read them for the "
                "instructions rather than the claims, because the instructions are still usable and the claims "
                "are contested.",
                "Where a passage is evocative, ask what procedure it implies. Where a passage is prescriptive, "
                "check whether you can specify the procedure well enough that somebody else could repeat it and "
                "get the same result. That test, applied consistently, is the whole method, and it is also a "
                "perfectly serviceable reading guide for forty years of subsequent literature.",
            ],
        },
        {
            "h2": "What to take forward",
            "p": [
                "Three things, in order of how much they will improve your practice. Write the intent as a "
                "checkable statement. Pre-register the deadline. Keep the log, including the entries where "
                "nothing happened.",
                "Everything else in the tradition is optional and most of it is negotiable. Those three are "
                "load-bearing, they are cheap, and they are the reason a practice started in 1976 can still be "
                "run productively by someone with no interest in the cosmology that accompanied it.",
            ],
        },
        {
            "h2": "The question the structure leaves open",
            "p": [
                "If the method is real, better recording should produce better results. If the method is a "
                "discipline of attention producing a side effect, better recording should also produce better "
                "results, by removing the confusion that lets a side effect be mistaken for a cause.",
                "That is an uncomfortable position to sit with for long, because it makes the evidence unable "
                "to settle the metaphysical question. Practically it is a good place to be, since the action it "
                "recommends is identical either way and the cost of being wrong is a smaller log rather than a "
                "wasted life.",
            ],
        },
    ],
    "faq": [
        [
            "Does the method require conviction on my part?",
            "No, and the tradition is unusually explicit about this, which is one of its more durable ideas. The "
            "method asks for a written intent, a reduction, a charge and a record. Every one of those is a "
            "behaviour rather than a belief, so a sceptic can run the whole protocol and keep the results. What "
            "the sceptic gives up is the framing, not the practice, and plenty of long-term practitioners hold "
            "no metaphysical view of what they are doing.",
        ],
        [
            "Is chaos magic dangerous?",
            "The documented risks are ordinary and mostly behavioural: over-identification with a practice until "
            "it crowds out sleep, social isolation from people who find it strange, and gradual narrowing of "
            "concerns until a symbolic system starts making decisions that a person should have made. None of "
            "these is supernatural and all of them are moderated by the same thing that moderates every "
            "obsessive practice, which is an outside life with obligations that do not flex around your "
            "schedule.",
        ],
        [
            "What do I actually need in order to start?",
            "Four things, and three of them are free. A statement of intent you would be willing to say out "
            "loud. Something to reduce it on, which can be paper. Somewhere to put the result afterwards, which "
            "can be a drawer. And a record, which can be a notebook. The paid tools exist and some of them are "
            "good, but none of the four is a purchase requirement, and anyone telling you the practice needs a "
            "device is describing a preference.",
        ],
        [
            "What does a chaos magic bundle actually include?",
            "Mostly organisation and presentation. The material itself has been freely available for decades, "
            "since the founding texts are short and widely reprinted. What a paid bundle reliably adds is a "
            "worked archive, printable ritual sheets, and some accounting of edge cases that took the compiler "
            "years to find. That is genuinely useful if you are the kind of person who benefits from a tidy "
            "format, and entirely dispensable if you are not.",
        ],
        [
            "How do I know when I am being a believer rather than a practitioner?",
            "Watch the moment a result arrives. A practitioner notices the result, checks it against what was "
            "pre-registered, and records it. A believer notices the result, explains it, and then finds the "
            "explanation for every result in the series including the nulls. The test is whether you can write "
            "a null entry without feeling that you have wasted the day, because if you cannot, the method has "
            "been quietly converted into a confirmation device.",
        ],
    ],
    "related": [
        ["history-of-chaos-magick", "History of Chaos Magick: From Austin Osman Spare to the IOT (2026)"],
        ["austin-osman-spare-magic-of-disorder-critique", "Austin Osman Spare and the Magic of Disorder: A Criticism"],
        ["liber-null-peter-carroll-review-what-survives", "Liber Null, Reviewed by Use: What Peter Carroll's Book Is For"],
        ["chaos-magic-inner-power-what-the-phrase-claims", "Chaos Magic Inner Power: What the Phrase Actually Claims"],
        ["from-skeptic-to-practitioner-iching", "From Skeptic to Practitioner: Starting With the I Ching"],
    ],
}
