# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT
ARTICLE = {
    "slug": "iching-career-questions",
    "title": "I Ching for Career Questions: Work Decisions Explained (2026)",
    "index_title": "I Ching Career Guide: Work Decisions Explained",
    "desc": "Use the I Ching to navigate job changes, career decisions, and workplace dilemmas. How to ask about work and read what the hexagram actually says.",
    "keywords": "i ching career, i ching job decision, i ching work, hexagram career guidance, book of changes career",
    "og_alt": "A hexagram consultation for a career decision with notebook and coins",
    "date_iso": "2026-08-16", "date_display": "August 16, 2026", "lastmod": "2026-08-16",
    "read_min": 8, "category": "divination",
    "excerpt": "The I Ching is strongest at timing and direction. Here is how to ask it about career decisions and read the answer honestly.",
    "cta_apps": [["iching-oracle", "I Ching Oracle"]],
    "related": [
        ["iching-for-love-questions", RT["iching-for-love-questions"]],
        ["iching-vs-tarot", RT["iching-vs-tarot"]],
        ["how-to-cast-iching-digitally", RT["how-to-cast-iching-digitally"]],
        ["i-ching-oracle-app-review", RT["i-ching-oracle-app-review"]],
    ],
    "references": ["Wilhelm, H. & Baynes, C.F. (1967). The I Ching or Book of Changes.", "Legge, J. (1882). The Sacred Books of China: The Texts of Confucianism.", "Ritsema, R. & Karcher, S. (1994). I Ching: The Classic Chinese Oracle of Change."],
    "howto": [
        {"name": "Frame a career question", "text": "Ask about your own path, not about someone else's decision."},
        {"name": "Cast and record the hexagram", "text": "Note any changing lines and the transformed hexagram."},
        {"name": "Read the judgment first", "text": "The judgment gives the direct answer to the question asked."},
        {"name": "Read changing lines if present", "text": "Changing lines add specific detail about which part of the situation is moving."},
        {"name": "Act within a defined window", "text": "The I Ching gives direction for a time-limited period. Reassess after 30 days."},
    ],
    "toc": [["why-career", "Why Career Questions Work"], ["phrasing", "How to Phrase"], ["timing", "Timing Questions"], ["changing-lines", "Changing Lines"], ["example", "Example Reading"], ["pitfalls", "Pitfalls"], ["app-support", "App Support"], ["faq", "FAQ"]],
    "sections": [
        {"t": "p", "text": "Career decisions carry high stakes and long timelines. The <a href=\"../apps/iching-oracle.html\">I Ching Oracle</a> app is strongest here because it gives you direction and timing, not just a yes or no. A hexagram tells you what the situation is doing, not what you wish it were doing."},
        {"t": "h2", "id": "why-career", "text": "Why Career Questions Work"},
        {"t": "p", "text": "The I Ching responds best to questions about your own role within a situation. Career questions work because they involve real tradeoffs: security versus growth, autonomy versus stability, this opportunity versus the next one."},
        {"t": "ul", "items": ["Career questions involve genuine tradeoffs", "The answer maps to actions you can actually take", "Timing guidance is meaningful when stakes are high"]},
        {"t": "h2", "id": "phrasing", "text": "How to Phrase Career Questions"},
        {"t": "p", "text": "Bad phrasing: Will I get the promotion? Good phrasing: What is the wisest way to approach this promotion decision? The first asks about someone else's choice. The second asks about your own path."},
        {"t": "h2", "id": "timing", "text": "Timing Questions"},
        {"t": "p", "text": "When should I accept this offer? The I Ching can guide timing. A solid line at the bottom suggests starting now. A solid line at the top suggests waiting. Changing lines add urgency: moving lines say the situation is already in motion."},
        {"t": "h2", "id": "changing-lines", "text": "Changing Lines"},
        {"t": "p", "text": "Changing lines in a career reading often point to specific conditions: line 1 is the starting position, line 3 is the transition point, line 5 is the position of influence. Read them against the specific part of the decision they describe."},
        {"t": "h2", "id": "example", "text": "Example Reading"},
        {"t": "p", "text": "Question: What is the wisest way to approach changing careers? Hexagram 50 Ding (The Cauldron), lines 3 and 5 changing. Judgment says transform through careful preparation. Lines 3 and 5 say: the middle period is uncomfortable (line 3) and the reward comes at the top of the structure (line 5). Transformed hexagram 44 (Coming to Meet) warns against forcing a premature start. Advice: prepare fully, accept the waiting, start when the structure is ready, not when you are impatient."},
        {"t": "h2", "id": "pitfalls", "text": "Pitfalls"},
        {"t": "p", "text": "The biggest pitfall is asking the I Ching to confirm a decision you already made. If you know what you are going to do and ask the I Ching anyway, you are using it as reassurance rather than guidance. Be honest about what you are actually asking."},
        {"t": "h2", "id": "app-support", "text": "App Support"},
        {"t": "p", "text": "The I Ching Oracle app gives you the hexagram text, changing lines, and the transformed hexagram in one view. Keep a career journal: date, question, hexagram, decision made, result 30 days later. After 20 entries the pattern becomes clear."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Should I ask about someone else's job decision?"},
        {"t": "p", "text": "No. Ask about your own response to their decision. The I Ching gives guidance on your role, not theirs."},
        {"t": "h3", "text": "How often should I ask about the same career question?"},
        {"t": "p", "text": "Once is enough if the question is clear. Re-ask only if the situation has materially changed."},
        {"t": "h3", "text": "Can I use the app for a quick check between meetings?"},
        {"t": "p", "text": "Yes. A focused two-minute consultation with the app is often more useful than a lengthy deliberation."},
    ],
    "faq": [
        ["Should I ask about someone else's job decision?", "No. Ask about your own response to their decision."],
        ["How often should I ask about the same career question?", "Once is enough. Re-ask only if the situation has materially changed."],
        ["Can I use the app for a quick check between meetings?", "Yes, a focused two-minute consultation is often more useful than lengthy deliberation."],
    ],
}
