# -*- coding: utf-8 -*-
"""Arcana Goetia spirit browser guide -> arcana-goetia (batch A2 #9)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "arcana-goetia-spirit-browser-guide",
    "title": "Browsing the 72 Spirits: Arcana Goetia App Guide (2026)",
    "index_title": "Arcana Goetia App Guide: Browse the 72 Spirits",
    "desc": "The Arcana Goetia app puts all 72 spirits at your fingertips: seals, ranks, offices, and purpose search. Here is how to use it well.",
    "keywords": "arcana goetia app, goetia 72 spirits, goetia app guide, goetia spirits list, goetia seal app, how to use arcana goetia",
    "og_alt": "The Arcana Goetia app interface showing the 72 spirits grid and seals",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "goetia",
    "excerpt": "The complete reference to all 72 Goetia spirits, browsable on your phone. Seals, ranks, offices, and purpose search in one app.",
    "cta_apps": [["arcana-goetia", "Arcana Goetia"]],
    "related": [
        ["arcana-goetia-app-review", RT["arcana-goetia-app-review"]],
        ["goetia-seals-and-sigils-guide", RT["goetia-seals-and-sigils-guide"]],
        ["which-goetia-spirit-for-love-money-knowledge", RT["which-goetia-spirit-for-love-money-knowledge"]],
        ["best-goetia-app-comparison", RT["best-goetia-app-comparison"]],
    ],
    "references": [
        "Mathers, S.L. & Crowley, A. (1904). The Lesser Key of Solomon.",
        "Peterson, J. (2001). The Lesser Key of Solomon: Detailing the Cryptic Magick of Goetia.",
        "Weyer, J. (1583). Pseudomonarchia Daemonum.",
    ],
    "howto": [
        {"name": "Open the spirit grid", "text": "Launch Arcana Goetia and browse the 72 spirits by rank, number, or name."},
        {"name": "Open a spirit card", "text": "Tap a spirit to see its seal, office, legion count, and conjuration details."},
        {"name": "Search by purpose", "text": "Use the purpose search to find a spirit for love, money, or knowledge."},
        {"name": "Use the seal", "text": "View or render the seal at full size for consecration or ritual use."},
        {"name": "Work one at a time", "text": "Learn one spirit thoroughly before attempting another. Discipline over volume."},
    ],
    "toc": [
        ["why-browse", "Why Browse the 72"],
        ["the-grid", "The Spirit Grid"],
        ["spirit-card", "The Spirit Card"],
        ["purpose-search", "Purpose Search"],
        ["seal-library", "The Seal Library"],
        ["ranks-and-offices", "Ranks & Offices"],
        ["digital-practice", "Digital Practice"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "The Ars Goetia names 72 spirits, each with its own seal, rank, office, and legion count. A printed grimoire forces you to page through all of them. The <a href=\"../apps/arcana-goetia.html\">Arcana Goetia</a> app turns that static list into a browsable, searchable reference you can actually use mid-ritual."},
        {"t": "h2", "id": "why-browse", "text": "Why Browse the 72"},
        {"t": "p", "text": "Most practitioners only ever work a handful of spirits. Browsing the full 72 matters because the right spirit for a given problem is often not the famous one. A purpose-oriented browse beats memorizing by heart."},
        {"t": "ul", "items": [
            "Discover lesser-known spirits suited to your exact situation",
            "Compare seals and ranks before committing to a working",
            "Confirm a spirit's office and legion count before you call it",
            "Build a personal shortlist of spirits you trust",
        ]},
        {"t": "h2", "id": "the-grid", "text": "The Spirit Grid"},
        {"t": "p", "text": "The app opens on a grid of all 72 spirits, sortable by number, rank, or name. Favorites pin your shortlist to the top so your core working set is never more than a tap away."},
        {"t": "h2", "id": "spirit-card", "text": "The Spirit Card"},
        {"t": "p", "text": "Each spirit card carries the essential working data: the seal, rank, office, legion count, and any notes on how the spirit is classically called. Everything you need is on one screen, no flipping pages."},
        {"t": "h2", "id": "purpose-search", "text": "Purpose Search"},
        {"t": "p", "text": "Purpose search is the feature that changes everything. Instead of knowing a name and looking it up, you start from the outcome you want. Need love, money, or knowledge? The app surfaces the spirits whose offices match."},
        {"t": "h2", "id": "seal-library", "text": "The Seal Library"},
        {"t": "p", "text": "Seals are the signature of each spirit. The app renders all 72 seals sharply and at scale, so you can trace or print the correct one instead of copying a blurry scan. Accuracy matters: a drifted seal is a different working."},
        {"t": "h2", "id": "ranks-and-offices", "text": "Ranks & Offices"},
        {"t": "p", "text": "Ranks describe how a spirit operates: kings work formally, dukes work directly, presidents lean scholarly, and so on. Pairing the right rank with the right task makes results far more consistent."},
        {"t": "h2", "id": "digital-practice", "text": "Digital Practice"},
        {"t": "p", "text": "A phone screen is a legitimate place to keep seals and working data. The app works fully offline, stores nothing on a server, and requires no account. That privacy is part of why it is a one-time purchase with no subscription."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is the app a replacement for studying the grimoire?"},
        {"t": "p", "text": "No. It is a working reference. You still benefit from reading the source texts, but the app carries the data you need during a ritual."},
        {"t": "h3", "text": "Does it work offline?"},
        {"t": "p", "text": "Yes. The full spirit library, seals, and purpose search all work without an internet connection and without an account."},
        {"t": "h3", "text": "Is it really a one-time payment?"},
        {"t": "p", "text": "Yes. Pay once and the complete 72-spirit reference is yours. No subscription, no ads, no recurring fees."},
    ],
    "faq": [
        ["Is the app a replacement for studying the grimoire?", "No. It is a working reference; read the source texts to go deeper."],
        ["Does it work offline?", "Yes, fully offline with no account required."],
        ["Is it really a one-time payment?", "Yes, one-time with no subscription, ads, or recurring fees."],
    ],
}
