# -*- coding: utf-8 -*-
"""Article 42 — How to Read Changing Lines with the I Ching Oracle App."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "iching-changing-lines-guide",
    "title": "How to Read Changing Lines in the I Ching: Complete Guide (2026)",
    "index_title": "Reading I Ching Changing Lines",
    "desc": "Changing lines turn a hexagram into a living answer. Learn what lines 6 and 9 mean, how a hexagram transforms, and how to read both judgments.",
    "keywords": "i ching changing lines, i ching line 6, i ching line 9, i ching hexagram transformation, i ching reading guide, book of changes changing lines",
    "og_alt": "An I Ching hexagram with one changing line highlighted in gold",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "iching",
    "excerpt": "Changing lines are where the I Ching earns its name: the Book of Changes. Here is how to read them correctly.",
    "cta_apps": [["iching-oracle", "I Ching Oracle"]],
    "related": [
        ["i-ching-hexagram-meanings-complete-guide", RT["i-ching-hexagram-meanings-complete-guide"]],
        ["how-to-cast-iching-digitally", RT["how-to-cast-iching-digitally"]],
        ["i-ching-oracle-app-review", RT["i-ching-oracle-app-review"]],
        ["iching-for-love-questions", "I Ching for Love Questions: How to Ask About Relationships (2026)"],
    ],
    "references": [
        "Wilhelm, R. & Baynes, C. (1967). The I Ching or Book of Changes. Princeton University Press.",
        "Legge, J. (1882). The Sacred Books of China: The I Ching. Clarendon Press.",
        "Ritsema, R. & Karcher, S. (1994). I Ching: The Classic Chinese Oracle of Change. Element.",
    ],
    "howto": [
        {"name": "Cast and identify changing lines", "text": "Cast your hexagram and mark any line that came up as 6 (old yin) or 9 (old yang)."},
        {"name": "Read the primary hexagram", "text": "The primary hexagram describes the current situation."},
        {"name": "Read the changing lines", "text": "Each changing line carries specific advice about the moment of transition."},
        {"name": "Form the transformed hexagram", "text": "Flip the changing lines and read the resulting hexagram as the outcome."},
        {"name": "Act on the movement", "text": "The path from primary to transformed hexagram is the change the oracle is describing."},
    ],
    "toc": [
        ("what-are-changing-lines", "What Are Changing Lines?"),
        ("why-they-matter", "Why Changing Lines Matter"),
        ("how-to-find-them", "How to Find Changing Lines"),
        ("reading-line-6", "Reading Old Yin (Line 6)"),
        ("reading-line-9", "Reading Old Yang (Line 9)"),
        ("the-transformed-hexagram", "The Transformed Hexagram"),
        ("reading-the-texts", "Reading the Judgments"),
        ("example-reading", "A Full Example Reading"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "Most beginners stop at the judgment text and miss the most important part of the I Ching: the changing lines. When a line is 'changing,' it is old, at the end of its cycle, and about to transform into its opposite. That single line is the oracle telling you <em>what is moving right now</em> — and where the situation is headed."},
        {"t": "h2", "id": "what-are-changing-lines", "text": "What Are Changing Lines?"},
        {"t": "p", "text": "In the coin method, each line is built from three coins. The totals give four possible values:"},
        {"t": "table", "headers": ["Total", "Line", "Nature", "Meaning"], "rows": [
            ["6 (three tails)", "Old yin", "Changing", "A broken line that is becoming solid"],
            ["7 (two tails, one heads)", "Young yang", "Stable", "A solid line that stays solid"],
            ["8 (two heads, one tails)", "Young yin", "Stable", "A broken line that stays broken"],
            ["9 (three heads)", "Old yang", "Changing", "A solid line that is becoming broken"],
        ]},
        {"t": "p", "text": "Only the old lines — 6 and 9 — are changing. They appear roughly one time in eight each, which is why most casts have zero to two changing lines."},
        {"t": "h2", "id": "why-they-matter", "text": "Why Changing Lines Matter"},
        {"t": "p", "text": "The judgment text describes the whole situation. The changing lines describe the <em>point of transformation</em> — the specific place where your action matters. Ignoring them is like reading a map and skipping the route."},
        {"t": "h2", "id": "how-to-find-them", "text": "How to Find Changing Lines"},
        {"t": "ol", "items": [
            "Write your hexagram from bottom to top (line 1 is the bottom).",
            "Mark every line that was cast as 6 or 9.",
            "If there are none, the answer is stable — read only the primary judgment.",
            "If there are one or more, note their positions for the line texts.",
            "Flip the changing lines (solid becomes broken, broken becomes solid) to form the transformed hexagram.",
        ]},
        {"t": "h2", "id": "reading-line-6", "text": "Reading Old Yin (Line 6)"},
        {"t": "p", "text": "Old yin is a broken line that is about to become solid. It represents a yielding, receptive force that has reached its limit. The energy has been withdrawn; something is ready to be received, accepted, or released. Line 6 texts often speak of letting go so that a new beginning can enter."},
        {"t": "h2", "id": "reading-line-9", "text": "Reading Old Yang (Line 9)"},
        {"t": "p", "text": "Old yang is a solid line about to become broken. It represents an active, creative force that has over-extended. The energy is at its peak and cannot hold. Line 9 texts often warn against pushing further, or celebrate a completed action that must now be released."},
        {"t": "h2", "id": "the-transformed-hexagram", "text": "The Transformed Hexagram"},
        {"t": "p", "text": "After flipping every changing line, you get a second hexagram. It shows the <em>outcome</em> — where the movement is taking you. The relationship between the two hexagrams is the story: the first is the seed, the second is the fruit."},
        {"t": "p", "text": "When multiple lines change, the transformed hexagram often carries more weight than any single line text. Read the movement first, then the details."},
        {"t": "h2", "id": "reading-the-texts", "text": "Reading the Judgments"},
        {"t": "ul", "items": [
            "No changing lines: read only the primary hexagram's judgment and image.",
            "One changing line: read that line's text as the core advice.",
            "Two to three changing lines: read them together; the transformed hexagram's judgment gains weight.",
            "Four to six changing lines: the transformation dominates — prioritize the transformed hexagram and its judgment.",
        ]},
        {"t": "h2", "id": "example-reading", "text": "A Full Example Reading"},
        {"t": "p", "text": "Question: 'Should I take the new job?' You cast hexagram 29 (The Abysmal Water, Kan), with a changing line at position 2."},
        {"t": "p", "text": "Primary hexagram 29 is the water over water trigram — difficulty, depth, the necessity of moving through. Its judgment counsels sincerity in the face of danger: the situation is genuinely hard, but passable."},
        {"t": "p", "text": "The changing line at position 2 reads: 'The abyss is dangerous. One should strive after small things only.' Applied to the job: the role is risky, but small, incremental gains are possible. Do not expect to fix everything at once."},
        {"t": "p", "text": "Line 2 is a broken line (old yin) in the lower trigram, so it flips to solid — the lower trigram becomes Li (The Clinging, Fire), forming hexagram 63 (After Completion). The transformed hexagram says the situation <em>can</em> reach order, but only after careful, step-by-step work. The answer is not a clean yes — it is 'yes, with your eyes open and your steps small.'"},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Reading the transformed hexagram as if it were the primary situation.",
            "Ignoring changing lines entirely and reading only the judgment.",
            "Reading lines top-down instead of bottom-up (line 1 is the bottom).",
            "Treating line 6 as 'bad' and line 9 as 'good' — both are simply points of change.",
            "Forgetting that no changing lines is itself a meaningful answer: stability.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "What if I get no changing lines?"},
        {"t": "p", "text": "The situation is stable. Read the primary judgment and image text only, and treat the stability as meaningful: the oracle is saying nothing needs to change right now."},
        {"t": "h3", "text": "Is a changing line always about something bad?"},
        {"t": "p", "text": "No. A changing line marks a threshold — it can be an opportunity, a warning, or a celebration, depending on the hexagram and the line position."},
        {"t": "h3", "text": "Does the I Ching Oracle app handle changing lines automatically?"},
        {"t": "p", "text": "Yes. The app records which lines were 6 or 9, displays the line texts, and automatically builds the transformed hexagram so you can read the outcome in one screen."},
    ],
    "faq": [
        ["What if I get no changing lines?", "The situation is stable — read the primary judgment and image text only."],
        ["Is a changing line always negative?", "No. It marks a threshold; context decides whether it is opportunity or warning."],
        ["Does the app handle changing lines automatically?", "Yes — it records old lines, shows line texts, and builds the transformed hexagram."],
    ],
}
