# -*- coding: utf-8 -*-
# Article 20: I Ching for love questions → iching-oracle
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "iching-for-love-questions",
    "title": "I Ching for Love Questions: How to Ask About Relationships (2026)",
    "index_title": "I Ching for Love Questions",
    "desc": "Ask the I Ching about love the right way: phrase relationship questions, read hexagrams for romance, and avoid the traps that ruin love readings.",
    "keywords": "i ching love, i ching relationship questions, i ching for love, i ching love reading, book of changes love",
    "og_alt": "An I Ching cast with coins and a hexagram chart beside a candle",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "iching",
    "excerpt": "The I Ching answers love questions with unsettling precision - if you ask the right way. Here is the exact phrasing and hexagram grammar.",
    "cta_apps": [["iching-oracle", "I Ching Oracle"]],
    "related": [
        [RT["how-to-cast-iching-digitally"], "How to Cast the I Ching Digitally: Coin Method Explained (2026)"],
        [RT["i-ching-hexagram-meanings-complete-guide"], "I Ching Hexagram Meanings: Complete 64 Hexagram Guide (2026)"],
        [RT["tarot-spreads-for-love-relationships"], "5 Best Tarot Spreads for Love and Relationships: Deepen Your Connection"],
        [RT["i-ching-oracle-app-review"], "I Ching Oracle App Review: Best Book of Changes App for"],
    ],
    "references": [
        "Wilhelm, R. & Baynes, C. (1967). The I Ching or Book of Changes. Princeton University Press.",
        "Legge, J. (1882). The I Ching: The Sacred Books of China. Clarendon Press.",
        "Ritsema, R. & Karcher, S. (2003). I Ching: The Classic Chinese Oracle of Change. Element Books.",
    ],
    "howto": [
        {"name": "Frame one question at a time", "text": "Ask about one relationship or one decision. Compound questions get muddy answers."},
        {"name": "Phrase it about your part", "text": "Ask what YOU should do, not what your partner is secretly feeling. The oracle answers the asker."},
        {"name": "Cast and record the hexagram", "text": "Use the three-coin method or the app. Note the lower trigram, upper trigram, and any changing lines."},
        {"name": "Read the judgment for the situation", "text": "The hexagram text describes the situation. The changing lines describe the movement."},
        {"name": "Act on the advice, not the prediction", "text": "The I Ching advises a way of proceeding. Follow the counsel, then let events unfold."},
    ],
    "toc": [
        ("can-the-iching-read-love", "Can the I Ching Read Love?"),
        ("how-to-phrase-love-questions", "How to Phrase Love Questions"),
        ("questions-to-avoid", "Questions to Avoid"),
        ("romance-hexagrams", "The Romance Hexagrams"),
        ("reading-the-lines", "Reading the Changing Lines"),
        ("love-situations", "Love Situations Decoded"),
        ("iching-vs-tarot-love", "I Ching vs Tarot for Love"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "The I Ching was answering relationship questions centuries before tarot decks existed. The Book of Changes is not a romance oracle - it is a situational oracle, which is exactly why it works for love. It does not whisper prophecies; it describes the movement of a situation and the attitude that moves with it."},
        {"t": "h2", "id": "can-the-iching-read-love", "text": "Can the I Ching Read Love?"},
        {"t": "p", "text": "Yes, but on its own terms. The oracle answers the question you actually ask. If you ask 'Does he love me?', it answers with the shape of the situation, not a yes or no. If you ask 'How should I act toward this person?', it gives you strategy. That second question is the one that changes your life."},
        {"t": "ul", "items": [
            "The hexagram names the situation: pursuit, waiting, devotion, parting.",
            "The judgment advises the correct attitude for the situation.",
            "The changing lines show the direction the situation is moving.",
            "The second hexagram (from changing lines) shows the outcome of following the advice.",
        ]},
        {"t": "h2", "id": "how-to-phrase-love-questions", "text": "How to Phrase Love Questions"},
        {"t": "p", "text": "Phrasing is 80 percent of a good love reading. The I Ching answers the literal asker. 'Is my ex coming back?' reads as a question about waiting. 'What should I do about the possibility of reconciliation?' reads as a question about action. Both are valid - the second one is useful."},
        {"t": "ol", "items": [
            "Use 'How should I...' or 'What attitude should I take...' instead of 'Will they...'.",
            "Include one relationship, not two ('my partner and I' is fine; 'my ex and my new crush' is not).",
            "State the time frame you care about: 'in the next month' or 'as things stand now'.",
            "Ask about behavior you control: 'What can I do to improve this connection?'",
            "Write the question down before casting so you cannot drift mid-cast.",
        ]},
        {"t": "h2", "id": "questions-to-avoid", "text": "Questions to Avoid"},
        {"t": "ul", "items": [
            "Yes-or-no ultimatums: 'Will we get married?' - the I Ching is not a fortune-telling coin.",
            "Mind-reading: 'What does she feel about me?' - it answers the asker, not the other person.",
            "Triangulation: 'Should I leave him for her?' - pick one decision to consult on.",
            "Spying: 'Is he cheating?' - if you need an oracle to find out, the situation already tells you.",
            "Impossible choices: 'Who is my soulmate?' - ask what to do next, not who to wait for.",
        ]},
        {"t": "h2", "id": "romance-hexagrams", "text": "The Romance Hexagrams"},
        {"t": "p", "text": "Some hexagrams recur constantly in love readings. None is a guaranteed 'yes' or 'no' - each describes a situation and its correct response."},
        {"t": "table", "headers": ["Hexagram", "Situation", "Advice"], "rows": [
            ["31 Influence (Hsien)", "Mutual attraction, courtship", "Move slowly; influence works by yielding"],
            ["32 Duration (Heng)", "Long-term commitment", "Steadfastness; persistence over excitement"],
            ["44 Coming to Meet (Kou)", "Unexpected encounter", "Beware a seductive but unbalanced influence"],
            ["53 Development (Chien)", "Gradual growth", "One step at a time; no forcing"],
            ["54 The Marrying Maiden (Kuei Mei)", "Unequal position", "Check whether the relationship is unbalanced"],
            ["60 Limitation (Chieh)", "Boundaries", "Set limits; respect each other's constraints"],
            ["63 After Completion (Chi Chi)", "Everything in place", "Stay attentive; the order can tip"],
            ["64 Before Completion (Wei Chi)", "Almost there", "Careful crossing; don't rush the last step"],
        ]},
        {"t": "h2", "id": "reading-the-lines", "text": "Reading the Changing Lines"},
        {"t": "p", "text": "A changing line (a 6 or 9 in the three-coin method) marks where the situation is moving. Read the line text as the pivot point, then cast the second hexagram to see the direction of change. No changing lines means the situation is stable and the advice is to stand still."},
        {"t": "ul", "items": [
            "Line 1: the foundation - the issue at the very start of the relationship.",
            "Line 2: your position - what you are doing right now, from your seat.",
            "Line 3: the danger - the point where the relationship could go wrong.",
            "Line 4: the invitation - the next step offered from the other side.",
            "Line 5: the leadership - the central, most public position of the bond.",
            "Line 6: the excess - where the situation has gone past its useful end.",
        ]},
        {"t": "h2", "id": "love-situations", "text": "Love Situations Decoded"},
        {"t": "p", "text": "New connection? Read Hexagram 31 and watch whether it develops into 32. In a long-term slump? Hexagram 32 tells you to renew commitment through steadiness, not grand gestures. A breakup is often Hexagram 44 or 54 - something unbalanced was 'coming to meet' you, and the advice is to examine the imbalance rather than rewind it."},
        {"t": "p", "text": "The same question repeated in a week often produces the same hexagram - the situation has not moved. If you keep drawing Hexagram 60 (Limitation), the advice is not 'try harder'; it is 'set a boundary'. The oracle reflects the situation back until you act on it."},
        {"t": "h2", "id": "iching-vs-tarot-love", "text": "I Ching vs Tarot for Love"},
        {"t": "p", "text": "Tarot gives you character and narrative - the lovers, the cups, the emotional weather. The I Ching gives you dynamics and strategy - how the situation moves and what to do about it. For 'how do we feel', use tarot. For 'what should I do', the I Ching is sharper. The two read beautifully together: tarot for the map, I Ching for the compass."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Re-casting the same question in the same week out of impatience.",
            "Reading the hexagram as a prophecy instead of advice.",
            "Ignoring the changing lines and reading only the main hexagram.",
            "Asking about a third person's feelings instead of your own action.",
            "Choosing the answer you wanted and skipping the counsel.",
        ]},
        {"t": "p", "text": "The <a href=\"../apps/iching-oracle.html\">I Ching Oracle</a> app handles the coin throws, hexagram lookup, changing lines, and the full Wilhelm text automatically - so you can focus on phrasing the question and applying the advice."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Can I ask the I Ching about a specific person?"},
        {"t": "p", "text": "Yes, but phrase it around your action: 'How should I approach this person?' The oracle answers the one consulting it."},
        {"t": "h3", "text": "Does Hexagram 61 (Inner Truth) mean someone is loyal?"},
        {"t": "p", "text": "It describes sincerity and inner truth as a situation - usually that honesty will reveal itself. Read it as 'trust and be truthful', not as a wiretap on someone's heart."},
        {"t": "h3", "text": "Why do I keep drawing the same hexagram for different questions?"},
        {"t": "p", "text": "The I Ching reflects the state of the asker. A recurring hexagram is usually a signal about a pattern in you - often Hexagram 29 or 64 when you are stuck in the same loop."},
    ],
}
