# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "goetia-seals-and-sigils-guide",
    "title": "Goetia Seals & Sigils: How to Use the 72 Seals of Solomon (2026)",
    "index_title": "Goetia Seals & Sigils Guide",
    "desc": "The 72 Goetia seals are the most overlooked part of the Lesser Key. Learn what they mean, how to use them in evocation, and common mistakes.",
    "keywords": "goetia seals meaning, how to use goetia sigils, seals of solomon 72, goetia seal consecration",
    "og_alt": "The 72 Goetia seals of Solomon arranged in a grid on parchment",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "goetia",
    "excerpt": "The 72 seals are the most overlooked part of the Goetia. They are not decorations — each one is the spirit's signature, and getting them right changes the work.",
    "cta_apps": [["arcana-goetia", "Arcana Goetia"]],
    "related": [
        ["arcana-goetia-app-review", RT["arcana-goetia-app-review"]],
        ["goetia-beginners-ritual", RT["goetia-beginners-ritual"]],
        ["best-goetia-books-essential-reading-2026", RT["best-goetia-books-essential-reading-2026"]],
        ["which-goetia-spirit-for-love-money-knowledge", RT["which-goetia-spirit-for-love-money-knowledge"]],
    ],
    "references": [
        "Mathers, S. L. MacGregor & Crowley, Aleister. The Lesser Key of Solomon (1904).",
        "Peterson, Joseph H. The Lesser Key of Solomon. Weiser Books, 2001.",
        "Agrippa, Heinrich Cornelius. Three Books of Occult Philosophy (1533).",
    ],
    "howto": [
        {"name": "Choose the right seal", "text": "Identify the spirit you intend to call and locate its unique seal among the 72."},
        {"name": "Trace or print it exactly", "text": "Copy the seal at 1:1 scale from a reliable edition; proportions matter."},
        {"name": "Consecrate the seal", "text": "Pass it through incense and state its purpose and the spirit's name aloud."},
        {"name": "Use it during evocation", "text": "Place it inside the triangle of art or hold it while you call the spirit."},
        {"name": "Store or burn it after", "text": "Keep reusable seals wrapped in cloth, or burn one-time seals after the work."},
    ],
    "toc": [
        ["what-are-the-seals", "What Are the 72 Seals?"],
        ["seal-vs-sigil", "Goetia Seal vs Chaos Sigil"],
        ["why-seals-matter", "Why the Seals Matter"],
        ["how-to-use-seals", "How to Use a Seal"],
        ["seal-by-rank", "Seals by Rank"],
        ["seals-in-digital-work", "Seals in Digital Work"],
        ["common-mistakes", "Common Mistakes"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "The Ars Goetia, the first book of the Lesser Key of Solomon, catalogues 72 spirits — kings, dukes, princes, marquises, presidents, and knights. Each spirit has a unique geometric seal. These seals are not artwork: they are the spirit's signature, and most evocation procedures in the grimoire assume you have them in front of you."},
        {"t": "h2", "id": "what-are-the-seals", "text": "What Are the 72 Seals?"},
        {"t": "p", "text": "Each seal is a diagram composed of lines, circles, and characters derived from the spirit's name and rank. In the grimoire tradition, the seal acts as a name written in a language the spirit recognizes. The 1904 Mathers and Crowley edition printed them in crowded plates; the Peterson edition redrew them cleanly. Always copy from a clean source."},
        {"t": "h2", "id": "seal-vs-sigil", "text": "Goetia Seal vs Chaos Sigil"},
        {"t": "table", "headers": ["Feature", "Goetia Seal", "Chaos Sigil"], "rows": [
            ["Origin", "Fixed, from the grimoire", "Personal, you design it"],
            ["Purpose", "Summons a specific spirit", "Programs a desire"],
            ["Design", "Must be exact", "Any shape that collapses"],
            ["Lifespan", "Reusable", "Destroyed after charging"],
            ["Tradition", "Solomonic", "Spare / chaos magick"],
        ]},
        {"t": "p", "text": "The rule is simple: you do not design a Goetia seal, you copy it. A chaos sigil is a compressed statement of intent; a Goetia seal is a fixed key. Confusing the two is the most common beginner error."},
        {"t": "h2", "id": "why-seals-matter", "text": "Why the Seals Matter"},
        {"t": "ul", "items": [
            "They anchor your attention during the evocation.",
            "They focus your will on a single, named spirit.",
            "They act as a protective token during the working.",
            "They give you a visual centerpiece for the ritual space.",
        ]},
        {"t": "h2", "id": "how-to-use-seals", "text": "How to Use a Seal"},
        {"t": "ol", "items": [
            "Purify the space and set up the circle and triangle of art.",
            "Place the spirit's seal inside the triangle.",
            "Light incense and recite the spirit's name and office.",
            "State your request clearly and calmly.",
            "Wait for a sign — sound, vision, temperature shift, or felt presence.",
            "Dismiss with the proper license to depart and banish.",
        ]},
        {"t": "h2", "id": "seal-by-rank", "text": "Seals by Rank"},
        {"t": "table", "headers": ["Rank", "Count", "Examples", "Working Style"], "rows": [
            ["King", "8", "Bael, Paimon, Beleth, Asmoday", "Formal, ceremonial"],
            ["Duke", "16", "Agares, Vepar, Gremory, Dantalion", "Direct, practical"],
            ["Prince", "6", "Vassago, Stolas, Seere", "Cerebral, informative"],
            ["Marquis", "8", "Amon, Sabnock, Decarabia", "Warrior, energetic"],
            ["President", "6", "Marbas, Buer, Foras", "Scholarly, medical"],
            ["Knight", "2", "Furcas, Focalor", "Specialized"],
            ["Count / Earl", "6", "Botis, Morax, Ipos", "Balanced"],
        ]},
        {"t": "h2", "id": "seals-in-digital-work", "text": "Seals in Digital Work"},
        {"t": "p", "text": "Displaying the seal on a phone or tablet screen beside your triangle is a legitimate modern adaptation — the geometry and proportions are what matter, not the medium. The <a href=\"../apps/arcana-goetia.html\">Arcana Goetia</a> app renders all 72 seals accurately and lets you save or print each one at the correct ratio."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Using blurry or resized seals that distort the geometry.",
            "Confusing the spirit's seal with the Great Seal of Solomon.",
            "Skipping consecration and intent-setting.",
            "Drawing from memory instead of copying.",
            "Forgetting to speak the name and office together.",
            "Reusing a seal you decided to burn after a one-time working.",
            "Handling the seal with fear instead of respect.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Do I need to hand-draw the seal?"},
        {"t": "p", "text": "No. An accurate, scaled rendering — printed or on screen — works. Proportions matter more than the medium."},
        {"t": "h3", "text": "Can one seal be used for multiple spirits?"},
        {"t": "p", "text": "No. Each of the 72 spirits has a unique seal; using the wrong one is a common cause of muddy results."},
        {"t": "h3", "text": "Are the seals dangerous?"},
        {"t": "p", "text": "They are identification tools. The danger in Goetia comes from sloppy protection and fear, not from ink or pixels."},
    ],
    "faq": [
        ["Do I need to hand-draw the seal?", "No. An accurate, scaled rendering — printed or on screen — works. Proportions matter more than the medium."],
        ["Can one seal be used for multiple spirits?", "No. Each of the 72 spirits has a unique seal; using the wrong one is a common cause of muddy results."],
        ["Are the seals dangerous?", "They are identification tools. The danger in Goetia comes from sloppy protection and fear, not from ink or pixels."],
    ],
}
