# -*- coding: utf-8 -*-
"""PSI GYM training modes walkthrough (batch A2 #8)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "psi-gym-training-modes-guide",
    "title": "PSI GYM Training Modes: A Practical Walkthrough (2026)",
    "index_title": "PSI GYM Training Modes Walkthrough",
    "desc": "A practical tour of the PSI GYM training modes: classic Zener tests, timed runs, and how to read your score history to actually improve your ESP.",
    "keywords": "psi gym app, psi gym training modes, zener card trainer, ESP training app, psi gym guide, zener card app",
    "og_alt": "PSI GYM training modes shown on an Android phone screen with Zener card symbols",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "esp",
    "excerpt": "A practical walkthrough of every PSI GYM training mode — from quick tests to timed runs — and how to use the score history to train your ESP.",
    "cta_apps": [["psi-gym", "PSI GYM: Zener Cards & ESP"]],
    "related": [
        ["psi-gym-app-review", RT["psi-gym-app-review"]],
        ["zener-cards-esp-training-guide", RT["zener-cards-esp-training-guide"]],
        ["zener-card-test-score-meaning", RT["zener-card-test-score-meaning"]],
        ["best-esp-training-apps-android", RT["best-esp-training-apps-android"]],
    ],
    "references": [
        "Rhine, J. B. (1934). Extrasensory Perception. Boston: Bruce Humphries.",
        "Rhine, J. B. (1947). The Reach of the Mind. New York: William Sloane Associates.",
        "Zener, K. & Rhine, J. B. (1930s). Duke University ESP card protocols.",
    ],
    "howto": [
        {"name": "Pick your mode", "text": "Choose between a quick single-run test and a timed or scored training session."},
        {"name": "Set your goal", "text": "Decide what you are training: raw accuracy, consistency, or long-run stamina."},
        {"name": "Run the session", "text": "Guess each card in turn and let the app reveal the true symbol."},
        {"name": "Check the score", "text": "Compare your result to the 1-in-5 chance baseline of 5 out of 25."},
        {"name": "Review history", "text": "Use the session history to spot trends, streaks, and psi-missing patterns."},
    ],
    "toc": [
        ("why-modes-matter", "Why the Training Modes Matter"),
        ("classic-test", "The Classic Zener Test"),
        ("timed-run", "Timed Runs"),
        ("score-history", "Reading Your Score History"),
        ("chance-baseline", "The Chance Baseline"),
        ("improving", "How to Actually Improve"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "Frequently Asked Questions"),
    ],
    "sections": [
        {"t": "p", "text": "Most free Zener card tests give you one boring 25-card run and nothing else. PSI GYM is built differently: it gives you several ways to train, and — more importantly — it keeps a score history so you can see whether you are actually improving or just guessing at chance."},
        {"t": "h2", "id": "why-modes-matter", "text": "Why the Training Modes Matter"},
        {"t": "p", "text": "ESP is a skill you train, not a switch you flip. That means you need repeatable sessions, honest feedback, and a way to track change over time. Training modes give you that structure. Without it, a single lucky 10-out-of-25 run tells you nothing."},
        {"t": "h2", "id": "classic-test", "text": "The Classic Zener Test"},
        {"t": "p", "text": "The core mode: you are shown a random sequence of the five Zener symbols — circle, cross, waves, square, and star — and you try to guess each one before it is revealed."},
        {"t": "ul", "items": [
            "25-card standard run (matches the classic Rhine protocol).",
            "Guesses are recorded in order, so you can review them later.",
            "The app uses a true random draw so the sequence cannot be predicted.",
            "Your final score is compared to the 1-in-5 chance baseline.",
        ]},
        {"t": "h2", "id": "timed-run", "text": "Timed Runs"},
        {"t": "p", "text": "A timed run adds pressure: you have a set window and you must move fast. This is useful for training the kind of quick, first-impression intuition that a relaxed session never forces you to develop."},
        {"t": "ul", "items": [
            "Good for building snap-judgement ESP under mild pressure.",
            "Helps you separate genuine hits from hesitation-driven guesses.",
            "A fast pace can raise your raw count, so read it alongside the accuracy rate.",
        ]},
        {"t": "h2", "id": "score-history", "text": "Reading Your Score History"},
        {"t": "p", "text": "The score history is where the real training value lives. A single 7-out-of-25 run is noise. A pattern of 7s, 8s, and 9s across a week is a signal worth acting on."},
        {"t": "ul", "items": [
            "Log every session so trends become visible.",
            "Watch for psi-hitting (consistently above 5) vs psi-missing (consistently below 5).",
            "Both patterns are interesting — psi-missing is still a non-chance result.",
            "Improve means the moving average drifts up, not one lucky peak.",
        ]},
        {"t": "h2", "id": "chance-baseline", "text": "The Chance Baseline"},
        {"t": "p", "text": "Five correct guesses out of twenty-five is exactly what pure chance predicts. Anything above that is where you start to pay attention."},
        {"t": "table", "headers": ["Score (out of 25)", "What It Means"], "rows": [
            ["0-4", "Below chance — often psi-missing, worth investigating"],
            ["5", "Exactly chance — no signal yet"],
            ["6-8", "Noise — could be luck, keep training"],
            ["9-10", "Notable — worth taking seriously"],
            ["11+", "Significant — well above chance (p < 0.05 in a 25-run)"],
        ]},
        {"t": "h2", "id": "improving", "text": "How to Actually Improve"},
        {"t": "p", "text": "Improvement is a habit. Train at roughly the same time, in the same quiet state, and give each session your full attention rather than rushing it between other tasks."},
        {"t": "ol", "items": [
            "Train 10-15 minutes, 3-5 times a week.",
            "Log every session in the app so your history builds up.",
            "Review your patterns weekly, not after every run.",
            "Pair training with a relaxed, slightly trance-like state.",
            "Stay consistent for 30 days before judging your results.",
        ]},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Training while distracted — attention is the whole point.",
            "Quitting after one bad session instead of looking at the trend.",
            "Ignoring psi-missing patterns when they are actually informative.",
            "Expecting a dramatic jump instead of a slow upward drift.",
            "Comparing single sessions instead of averages.",
        ]},
        {"t": "h2", "id": "faq", "text": "Frequently Asked Questions"},
        {"t": "h3", "text": "Is 5 out of 25 a bad score?"},
        {"t": "p", "text": "No — 5 out of 25 is exactly the chance baseline, so it is the neutral starting point, not a failure."},
        {"t": "h3", "text": "What score counts as real ESP?"},
        {"t": "p", "text": "Consistently scoring 9-10 or higher across many sessions is the pattern to take seriously. A single 11 is interesting; a week of 9s is stronger evidence."},
        {"t": "h3", "text": "Is PSI GYM really a one-time purchase?"},
        {"t": "p", "text": "Yes. You pay once, there is no subscription, no recurring fee, and no ads — your full training history lives on your device."},
    ],
    "faq": [
        ["How long until I improve?", "Most people see their moving average drift upward within 2-4 weeks of consistent, focused training."],
        ["Does the app need internet?", "No. PSI GYM runs fully offline, so your sessions work anywhere and your history stays private."],
        ["What if I score below chance?", "Below-chance scoring (psi-missing) is still a non-random pattern. Train it like any other signal."],
    ],
}
