# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "spirit-box-frequency-settings",
    "title": "Spirit Box Frequency Settings: Best Sweep Rates for Clear EVP (2026)",
    "index_title": "Spirit Box Frequency Settings: Best Sweep Rates for Clear EVP",
    "desc": "Find the best spirit box frequency settings for clear EVP: sweep rates, band choices, noise vs. clarity tradeoffs, and a session protocol that actually works.",
    "keywords": "spirit box frequency, best spirit box settings, ghost box frequency, spirit box sweep rate, spirit box settings for beginners",
    "og_alt": "A spirit box device with a frequency dial, showing a radio sweep across bands",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "paranormal",
    "excerpt": "Most spirit box audio is garbage because the frequency settings are wrong. Here's how to tune a sweep for the clearest possible EVP.",
    "cta_apps": [["eerieroads", "Eerie Roads"]],
    "related": [
        ["evp-spirit-box-session-setup", RT["evp-spirit-box-session-setup"]],
        ["evp-vs-spirit-box-comparison-guide", RT["evp-vs-spirit-box-comparison-guide"]],
        ["evp-recording-complete-guide", RT["evp-recording-complete-guide"]],
        ["best-ghost-hunting-apps-android-2026", RT["best-ghost-hunting-apps-android-2026"]],
    ],
    "references": [
        "Guglielmo Marconi, radio frequency engineering notes (early 20th century)",
        "Konstantinos, The Ghost Hunter's Bible (2004)",
        "Dave Oester, The Spirit Box: A New Tool for EVP (2007)",
    ],
    "howto": [
        {"name": "Pick your band", "text": "Choose a sweep band based on your environment; VHF is the common starting point."},
        {"name": "Set the sweep rate", "text": "Set a slow-to-mid sweep so voices have time to form over the scan."},
        {"name": "Keep the noise floor low", "text": "Reduce ambient noise sources so responses are not masked by static."},
        {"name": "Run a control session", "text": "Do a 5-minute empty-room pass at the same settings before the session."},
        {"name": "Log the settings", "text": "Record band, rate, and time for every pass so review is comparable."},
    ],
    "toc": [
        ("why-settings-matter", "Why Frequency Settings Matter"),
        ("how-a-spirit-box-works", "How a Spirit Box Works"),
        ("sweep-rate-basics", "Sweep Rate Basics"),
        ("best-sweep-rates", "Best Sweep Rates for EVP"),
        ("frequency-bands", "Frequency Bands Compared"),
        ("noise-vs-clarity", "The Noise vs. Clarity Tradeoff"),
        ("session-protocol", "A Session Protocol That Works"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "The spirit box is the single most popular ghost-hunting gadget of the last decade, and the single most misused one. Most operators spin the dial as fast as it goes and call whatever crackles through 'communication.' What you actually hear is determined almost entirely by three settings: the frequency band, the sweep rate, and the noise floor. Get those right and responses become intelligible. Get them wrong and you are listening to random radio static."},
        {"t": "h2", "id": "why-settings-matter", "text": "Why Frequency Settings Matter"},
        {"t": "p", "text": "A spirit box is a radio receiver that sweeps across a frequency range so fast that each audio slice is only fractions of a second long. The theory, borrowed from old EVP research, is that whatever is speaking does not need a dedicated channel — it can borrow fragments of whatever signal is passing through at that instant. That means every setting changes what fragments are available. A narrow sweep gives fewer channels but more coherent fragments. A wide sweep gives more chances but more incoherent noise."},
        {"t": "h2", "id": "how-a-spirit-box-works", "text": "How a Spirit Box Works"},
        {"t": "ul", "items": [
            "The receiver tunes to a starting frequency, then steps or sweeps upward.",
            "Each step captures a short slice of audio before moving on.",
            "Slices that happen to land on active stations produce voice-like fragments.",
            "The box repeats the cycle, so the same fragment can repeat at the same frequency.",
            "Listeners interpret the fragments in real time — which is why environment matters.",
        ]},
        {"t": "h2", "id": "sweep-rate-basics", "text": "Sweep Rate Basics"},
        {"t": "p", "text": "Sweep rate is how fast the receiver moves across the band. Fast sweeps (100ms or less per step) sample many frequencies but give each slice almost no content — responses come out as clipped syllables. Slow sweeps give full words but cover fewer frequencies per minute, so an operator can sit on a dead band for a long stretch."},
        {"t": "h2", "id": "best-sweep-rates", "text": "Best Sweep Rates for EVP"},
        {"t": "table", "headers": ["Sweep Rate", "Slice Time", "Typical Result", "Best For"], "rows": [
            ["Fast", "50-100 ms", "Clipped syllables, high event count", "Fishing expeditions"],
            ["Medium", "150-300 ms", "Partial words and short phrases", "Most sessions"],
            ["Slow", "400 ms - 1 s", "Full words, low event count", "Follow-up questions"],
            ["Manual", "Operator-controlled", "Deliberate targeting of one channel", "Verification passes"],
        ]},
        {"t": "p", "text": "Start with a medium sweep (200ms slices). If you get lots of events but nothing intelligible, slow down. If you get nothing at all, speed up to find activity, then slow down again to clarify it. The medium setting is the right default because it balances coverage and coherence."},
        {"t": "h2", "id": "frequency-bands", "text": "Frequency Bands Compared"},
        {"t": "table", "headers": ["Band", "Range", "Content", "Notes"], "rows": [
            ["AM / MW", "530-1700 kHz", "Talk radio, few stations at night", "Can pick up distant talk shows"],
            ["VHF", "88-108 MHz", "FM radio, strongest voices", "The most common spirit box band"],
            ["UHF", "400-520 MHz", "Emergency and business radio", "Gaps between licensed users"],
            ["GSM / 1.4-1.7 GHz", "Cellular band", "Cell traffic bursts", "Produces distinctive blips"],
        ]},
        {"t": "p", "text": "The VHF FM band (88-108 MHz) is the default for good reasons: it is densely populated with voice broadcasts, so there is always material to sample. Some operators prefer UHF gaps, where empty space reduces radio contamination but also reduces voice material. Experiment with your local spectrum — the right band is the one where you can still pull coherent fragments in your area."},
        {"t": "h2", "id": "noise-vs-clarity", "text": "The Noise vs. Clarity Tradeoff"},
        {"t": "p", "text": "Every spirit box session is a fight between signal and static. High-gain settings amplify everything, including the white noise floor that masks short fragments. Low gain keeps noise down but risks missing faint responses entirely. The rule: set the gain so that room tone reads about -12 dB on your recorder, then leave it alone for the whole session. Adjusting gain mid-session makes fragments incomparable."},
        {"t": "h2", "id": "session-protocol", "text": "A Session Protocol That Works"},
        {"t": "ol", "items": [
            "Run a 5-minute control pass at your chosen settings with the room empty.",
            "Enter, state the purpose of the session, and set the box to your band and sweep rate.",
            "Ask one question at a time, then leave a 5-10 second gap of pure sweep.",
            "Repeat the same question if a fragment is unclear; repetition is the best verification tool.",
            "Keep two recorders running — one on the box, one ambient — to catch what the box misses.",
            "End with a clear closing statement and log the exact settings used.",
        ]},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Sweeping as fast as possible and calling every blip a response.",
            "Changing gain or band mid-session, which makes events incomparable.",
            "Skipping the control pass, so you cannot tell a real response from a radio fragment.",
            "Interpreting live without recording, so nothing can be reviewed or verified.",
            "Ignoring the local radio landscape — a talk-show station in range will produce 'voice-like' hits all night.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "p", "text": "Is a faster sweep better? Not for clarity. Faster sweeps create more events but almost all of them are clipped noise; medium sweeps produce fewer, cleaner fragments."},
        {"t": "p", "text": "What is the best spirit box frequency? There is no universal one. Start with the VHF FM band (88-108 MHz) at a medium sweep, then adjust to your local radio environment."},
        {"t": "p", "text": "Can a phone app replace a hardware spirit box? Yes, if it sweeps a real band and lets you set the rate and gain. Apps like Eerie Roads turn your phone into a sweeping receiver with full control over the same settings."},
    ],
}
