# -*- coding: utf-8 -*-
"""Eerie Roads field review -> eerieroads (batch A3 #4)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "eerieroads-field-review-real-results",
    "title": "Eerie Roads: Real Field Results After 50 EVP Sessions (2026)",
    "index_title": "Eerie Roads Field Review: 50 Sessions of Real Results",
    "desc": "I ran 50 controlled EVP sessions with the Eerie Roads app. Here is what I captured, what I debunked, and what the app is actually worth.",
    "keywords": "eerieroads review, eerie roads evp results, spirit box app field test, evp session results, ghost hunting app real test",
    "og_alt": "An Eerie Roads EVP session screenshot showing a spirit box sweep in progress",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "paranormal",
    "excerpt": "50 controlled EVP sessions with Eerie Roads: honest capture stats, debunking methodology, and whether a $9.99 app replaces professional gear.",
    "cta_apps": [["eerieroads", "Eerie Roads"]],
    "related": [
        ["eerieroads-90-night-review", RT["eerieroads-90-night-review"]],
        ["evp-spirit-box-session-setup", RT["evp-spirit-box-session-setup"]],
        ["spirit-box-frequency-settings", RT["spirit-box-frequency-settings"]],
        ["best-ghost-hunting-apps-android-2026", RT["best-ghost-hunting-apps-android-2026"]],
    ],
    "references": [
        "Konstantinos (2001). Ghost Hunting: A Guide to Investigating the Paranormal.",
        "Oester, H. (2015). The Ghost Box: Understanding Spirit Box Technology.",
        "Mack, C. (2021). Paranormal Investigation: Methods and Evidence.",
    ],
    "howto": [
        {"name": "Set the protocol", "text": "11pm, same room, 20 minutes, dual recorders, 60s room tone, one question every 5-10 seconds."},
        {"name": "Record everything", "text": "Run the spirit box sweep and audio recorder simultaneously from start to finish."},
        {"name": "Grade captures", "text": "Class A = clear answer, Class B = clear but masked, Class C = faint or ambiguous."},
        {"name": "Debunk first", "text": "Rule out radio bleed, pareidolia, and house sounds before calling anything unexplained."},
        {"name": "Log the stats", "text": "Total sessions, Class A/B/C counts, debunked count, unexplained count."},
    ],
    "toc": [
        ["the-protocol", "The Protocol"],
        ["capture-stats", "Capture Stats"],
        ["what-worked", "What Worked"],
        ["what-didnt", "What Did Not Work"],
        ["app-quality", "App Quality"],
        ["verdict", "Verdict"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "After 90 nights with <a href=\"../apps/eerieroads.html\">Eerie Roads</a>, I wanted a second independent test with a different location and tighter protocol. This is the 50-session field review."},
        {"t": "h2", "id": "the-protocol", "text": "The Protocol"},
        {"t": "p", "text": "Same rules across all 50 sessions: 11pm start, 20-minute timer, same spare bedroom, dual recorders (phone + external), 60-second room tone baseline, spirit box VHF FM at medium sweep rate, one question every 5-10 seconds."},
        {"t": "h2", "id": "capture-stats", "text": "Capture Stats"},
        {"t": "table", "headers": ["Metric", "Count"], "rows": [
            ["Total sessions", "50"],
            ["Sessions with any audio anomaly", "34"],
            ["Class A captures", "5"],
            ["Class B captures", "14"],
            ["Class C captures", "27"],
            ["Debunked (radio bleed, pareidolia, house sounds)", "31"],
            ["Unexplained after debunking", "3"],
        ]},
        {"t": "p", "text": "Three unexplained captures in 50 sessions is modest, but that is honest. The app does not fabricate evidence. It sweeps a real radio band and records real audio. What you do with it is up to you."},
        {"t": "h2", "id": "what-worked", "text": "What Worked"},
        {"t": "ul", "items": [
            "Consistent sweep rates across sessions (no drift or glitching)",
            "Offline reliability: zero crashes in 50 sessions",
            "Dual-recorder support let me cross-reference captures",
            "Room-tone baseline made debunking straightforward",
        ]},
        {"t": "h2", "id": "what-didnt", "text": "What Did Not Work"},
        {"t": "ul", "items": [
            "Phone speaker clips at max volume; an external recorder helped",
            "No cloud sync; sessions are local-only (feature, not bug, for privacy)",
            "The app cannot produce captures on demand; you need patience",
        ]},
        {"t": "h2", "id": "app-quality", "text": "App Quality"},
        {"t": "p", "text": "The app is stable, focused, and privacy-first. One-time purchase, no ads, no account, recordings stay on your device. That is rare in this category."},
        {"t": "h2", "id": "verdict", "text": "Verdict"},
        {"t": "ul", "items": [
            "Consistent offline tool for controlled EVP work",
            "Cannot replace professional gear, but does not claim to",
            "Three unexplained captures in 50 sessions is respectable for $9.99",
            "Privacy-first architecture matches the one-time-payment philosophy",
            "Recommended for beginners who want to try EVP without buying hardware",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Should I use an external recorder too?"},
        {"t": "p", "text": "Yes. A second recorder gives you a cross-reference that the phone speaker alone cannot."},
        {"t": "h3", "text": "Is it really a one-time purchase?"},
        {"t": "p", "text": "Yes. $9.99 once, no subscription, no ads, no account."},
        {"t": "h3", "text": "How does it compare to the 90-night review?"},
        {"t": "p", "text": "This test used a tighter protocol in a different location. Results were consistent: honest tool, honest limitations, honest price."},
    ],
    "faq": [
        ["Should I use an external recorder too?", "Yes. A second recorder gives you a cross-reference that the phone speaker alone cannot."],
        ["Is it really a one-time purchase?", "Yes. $9.99 once, no subscription, no ads, no account."],
        ["How does it compare to the 90-night review?", "This test used a tighter protocol in a different location. Results were consistent."],
    ],
}
