# -*- coding: utf-8 -*-
# Norse Rune Oracle: nine-rune digital cast guide (batch A2 #7)
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "norse-rune-nine-rune-digital-cast",
    "title": "How to Do the Nine-Rune Cast Digitally: Norse Rune Oracle Guide (2026)",
    "index_title": "Norse Rune Oracle: Nine-Rune Digital Cast",
    "desc": "The nine-rune cast is the deepest Elder Futhark spread. Learn the positions and how to cast it digitally with the Norse Rune Oracle app.",
    "keywords": "nine rune cast, norse rune oracle app, how to cast runes, nine rune spread, elder futhark cast, rune reading app",
    "og_alt": "A digital nine-rune cast spread across a dark ritual cloth",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "runes",
    "excerpt": "Master the nine-rune cast: the five fixed positions, their meaning, and how the Norse Rune Oracle app handles the digital draw.",
    "cta_apps": [["norse-rune-oracle", "Norse Rune Oracle"]],
    "related": [
        ["norse-rune-oracle-app-review", RT["norse-rune-oracle-app-review"]],
        ["rune-spreads-for-beginners", RT["rune-spreads-for-beginners"]],
        ["norse-runes-beginners-guide", RT["norse-runes-beginners-guide"]],
        ["free-online-rune-reading-guide", RT["free-online-rune-reading-guide"]],
    ],
    "references": [
        "Diana L. Paxson, Taking Up the Runes, 2005",
        "Edred Thorsson, Futhark: A Handbook of Rune Magic, 1984",
        "Stephen Flowers, Rune Might, 1989",
    ],
    "howto": [
        {"name": "Frame the question", "text": "Write a single clear question or intention before drawing."},
        {"name": "Draw nine runes", "text": "Let the app draw nine runes from the full 24-rune Elder Futhark set."},
        {"name": "Place the first five", "text": "The first rune is the center; the next four fill the right, left, top, and bottom positions."},
        {"name": "Read the remaining four", "text": "The final four runes are read as a second layer, refining the picture."},
        {"name": "Record the cast", "text": "Log runes, positions, and your interpretation in the app journal for review."},
    ],
    "toc": [
        ("what-is-nine-cast", "What Is the Nine-Rune Cast"),
        ("the-five-positions", "The Five Fixed Positions"),
        ("reading-layers", "Reading the Layers"),
        ("digital-vs-physical", "Digital vs Physical Casting"),
        ("example-reading", "Example Reading"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "The nine-rune cast is the most complete layout in Elder Futhark practice. Unlike a single draw or a three-rune spread, it maps a situation onto a field of meaning: a center surrounded by four directional stations, plus four more runes that deepen the picture. It is the spread practitioners turn to when a question resists a quick answer."},
        {"t": "h2", "id": "what-is-nine-cast", "text": "What Is the Nine-Rune Cast"},
        {"t": "p", "text": "Nine is a sacred number in Norse tradition — the worlds of Yggdrasil, the nights Odin hung before gaining the runes. The cast draws nine runes and places them in relation to one another, treating the whole field as a single statement about your question."},
        {"t": "h2", "id": "the-five-positions", "text": "The Five Fixed Positions"},
        {"t": "p", "text": "The first five runes occupy fixed stations. The remaining four run around them and refine the reading."},
        {"t": "ul", "items": [
            "Center — the core of the situation or the question itself",
            "Right — the path forward or the action to take",
            "Left — the root, the cause, or what lies behind you",
            "Top — the hidden influence or the larger force at work",
            "Bottom — the foundation or what you can rely on",
        ]},
        {"t": "h2", "id": "reading-layers", "text": "Reading the Layers"},
        {"t": "p", "text": "Read the first five as the main statement. Then read the four outer runes as a second layer: they confirm, contradict, or deepen what the fixed positions already say. If an outer rune mirrors an inner one, that theme is the heart of the reading."},
        {"t": "h2", "id": "digital-vs-physical", "text": "Digital vs Physical Casting"},
        {"t": "p", "text": "A digital draw uses the same randomness as throwing runes onto cloth — each of the 24 runes has an equal chance per position. What the digital cast removes is clutter: no runes scattering off the table, no re-drawing because you knocked one over, and a clean record every time. The <a href=\"../apps/norse-rune-oracle.html\">Norse Rune Oracle</a> app draws the nine runes, marks the five fixed positions, and saves each cast to your journal."},
        {"t": "h2", "id": "example-reading", "text": "Example Reading"},
        {"t": "p", "text": "Suppose the center is Fehu (value), the right is Raido (journey), and the top is Ansuz (communication). The message reads: a resource or income (Fehu) is moving through a change (Raido) guided by honest words or messages (Ansuz) — a practical move, communicated clearly, is the way forward."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Reading every rune as a separate fortune instead of one connected field",
            "Skipping the fixed positions and shuffling the layout after the draw",
            "Ignoring the outer layer that refines the first five",
            "Asking a new question in the middle of a cast",
            "Forgetting to log the reading for later review",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is the nine-rune cast better than a three-rune spread?"},
        {"t": "p", "text": "Not better — deeper. Use the three-rune spread for a fast snapshot and the nine-rune cast when you need the full field of a situation."},
        {"t": "h3", "text": "Do reversed runes matter in a digital cast?"},
        {"t": "p", "text": "The nine-rune cast traditionally reads runes upright. For positional reversals, the Norse Rune Oracle lets you choose your reading style before drawing."},
        {"t": "h3", "text": "Can I cast nine runes daily?"},
        {"t": "p", "text": "You can, but the spread is heavy for daily use. Many practitioners save it for the full moon or for questions that genuinely need depth, and use a single draw on other days."},
    ],
    "faq": [
        ["Is the nine-rune cast better than a three-rune spread?", "Not better — deeper. Use the three-rune spread for a fast snapshot and the nine-rune cast when you need the full field."],
        ["Do reversed runes matter in a digital cast?", "The nine-rune cast traditionally reads upright. For positional reversals, choose your reading style in the app before drawing."],
        ["Can I cast nine runes daily?", "You can, but the spread is heavy for daily use. Save it for the full moon or genuinely deep questions."],
    ],
}
