# -*- coding: utf-8 -*-
# Article 45 — batch A2. Data-driven (0% hardcoded HTML).
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "astral-lab-hypnagogia-to-projection",
    "title": "From Hypnagogia to Full Projection: Astral Lab Field Guide (2026)",
    "index_title": "Astral Lab Field Guide: Hypnagogia to Projection",
    "desc": "Use the hypnagogic state as your launchpad: eyes-closed imagery, exit techniques, and how the Astral Lab app supports each stage of projection.",
    "keywords": "hypnagogic state, astral projection steps, how to astral project, astral lab app, hypnagogia exit technique, out of body beginner",
    "og_alt": "The stages of astral projection from waking hypnagogia to full exit",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "astral-projection",
    "excerpt": "The hypnagogic state is the gateway: learn to recognize it, ride it, and exit.",
    "cta_apps": [["astral-lab", "Astral Lab"]],
    "related": [
        ["astral-projection-for-beginners", RT["astral-projection-for-beginners"]],
        ["astral-projection-techniques-rope-roll-out-phasing-compared", RT["astral-projection-techniques-rope-roll-out-phasing-compared"]],
        ["astral-lab-app-review", RT["astral-lab-app-review"]],
        ["vibrational-state-obe-precursor-recognition", RT["vibrational-state-obe-precursor-recognition"]],
    ],
    "references": [
        "Monroe, Robert. Journeys Out of the Body (1971)",
        "Fox, Oliver. Astral Projection (1938)",
        "Raduga, Michael. The Phase (2021)",
    ],
    "howto": [
        {"name": "Set an exit intention", "text": "Decide before sleep that the first exit attempt happens tonight, not sometime."},
        {"name": "Enter hypnagogia", "text": "Lie still, eyes closed, and let the random imagery and drifting thoughts arrive."},
        {"name": "Catch the body asleep", "text": "The body goes numb while awareness stays; do not move or swallow deliberately."},
        {"name": "Fire the exit technique", "text": "At the right moment use rope, roll-out, or rising; act within seconds."},
        {"name": "Stabilize and log", "text": "Rub hands or spin to stabilize, then write the journal entry immediately."},
    ],
    "toc": [
        ["why-hypnagogia", "Why Hypnagogia"],
        ["the-threshold", "The Threshold"],
        ["stage-by-stage", "Stage by Stage"],
        ["three-exits", "Three Exit Techniques"],
        ["stabilizing", "Stabilizing After Exit"],
        ["astral-lab-stages", "Astral Lab Support"],
        ["common-blocks", "Common Blocks"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Most people who try astral projection never get past the boring middle: they lie still, nothing happens, and they fall asleep or give up. The missing piece is usually the hypnagogic state — the drifting, dreamlike phase between waking and sleep where projection actually launches. This guide maps that threshold, and shows how the <a href=\"../apps/astral-lab.html\">Astral Lab</a> app fits each stage."},
        {"t": "h2", "id": "why-hypnagogia", "text": "Why Hypnagogia Is the Launchpad"},
        {"t": "p", "text": "Hypnagogia is the state of hypnagogic imagery: spontaneous visuals, sounds, and body sensations that appear as your brain shifts from waking to sleep. It is the doorway for most exit techniques because the body falls asleep first while your awareness stays online. Trying to project from full waking alertness skips the state that makes exit possible."},
        {"t": "h2", "id": "the-threshold", "text": "The Threshold"},
        {"t": "ul", "items": [
            "Random colors, faces, or scenes appear behind closed eyes",
            "Body feels heavy, numb, or like it is sinking",
            "Hearing drifts: distant voices, wind, or a hum",
            "Thoughts fragment into short dream-like snippets",
            "A sudden jerk or falling sensation means you are close",
        ]},
        {"t": "h2", "id": "stage-by-stage", "text": "Stage by Stage"},
        {"t": "ol", "items": [
            "Lie down in your usual sleep position, eyes closed, and commit to staying still",
            "Let imagery come; watch it without controlling it for several minutes",
            "When numbness spreads, stop moving completely (no swallowing, no scratching)",
            "Hold the imagery in view while your body slips into sleep",
            "Fire your exit technique the instant the threshold feels ready",
        ]},
        {"t": "h2", "id": "three-exits", "text": "Three Exit Techniques"},
        {"t": "h3", "text": "Rope Technique"},
        {"t": "p", "text": "Imagine a rope hanging above you. Reach up with an imaginary hand and pull yourself up hand over hand. The action pulls your awareness out of the body."},
        {"t": "h3", "text": "Roll-Out Technique"},
        {"t": "p", "text": "While numb, try to roll your whole body to one side as if turning in bed. Let the imaginary roll carry you out of the body."},
        {"t": "h3", "text": "Rising Technique"},
        {"t": "p", "text": "Float upward like a balloon releasing from the body. Keep the sensation of rising, not flying with effort."},
        {"t": "h2", "id": "stabilizing", "text": "Stabilizing After Exit"},
        {"t": "ul", "items": [
            "Rub your phantom hands together until the world sharpens",
            "Spin in place a few times to anchor your perception",
            "State your intention out loud: where you are going, what you will do",
            "Keep the exit short at first; return deliberately before fatigue sets in",
        ]},
        {"t": "h2", "id": "astral-lab-stages", "text": "Astral Lab Support"},
        {"t": "p", "text": "The <a href=\"../apps/astral-lab.html\">Astral Lab</a> app turns this sequence into a practice loop: a guided pre-sleep routine that walks you into hypnagogia, exit technique reminders, a vibration-state tracker, and a journal for comparing what worked. Because everything runs offline with no account and no subscription, your practice data stays on your device."},
        {"t": "h2", "id": "common-blocks", "text": "Common Blocks"},
        {"t": "ul", "items": [
            "Moving too soon (scratching an itch resets the threshold)",
            "Racing thoughts from stress or caffeine close to bed",
            "Trying to force imagery instead of watching it",
            "Skipping the journal, so patterns never surface",
            "Quitting after one or two attempts — consistency beats intensity",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "How long until the first projection?"},
        {"t": "p", "text": "Most beginners report their first exit between 1 and 4 weeks of nightly practice. Treat the first week as threshold training."},
        {"t": "h3", "text": "Is hypnagogia dangerous?"},
        {"t": "p", "text": "No. Sleep paralysis-like numbness is normal and temporary. If it feels uncomfortable, wiggle a finger or toe to break it."},
        {"t": "h3", "text": "Do I need the app to project?"},
        {"t": "p", "text": "No — the technique works alone. The app exists to keep you consistent and logged, which is what actually produces results."},
    ],
}
