# -*- coding: utf-8 -*-
"""Astral Lab 30-day log → astral-lab (batch A3 #9)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "astral-lab-30-day-log",
    "title": "30 Days of Astral Projection Practice: My Honest Log (2026)",
    "index_title": "Astral Lab 30-Day Log: What Actually Happened",
    "desc": "A 30-day astral projection experiment with nightly logs. What worked, what failed, and the first time the vibration state hit.",
    "keywords": "astral projection 30 day challenge, astral projection log, astral lab app review, 30 days astral projection, out of body experience log",
    "og_alt": "A journal page showing 30 days of astral projection practice logs",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "astral-projection",
    "excerpt": "I tried astral projection every night for 30 days and logged the results. Here is what actually happened.",
    "cta_apps": [["astral-lab", "Astral Lab"]],
    "related": [
        ["astral-projection-for-beginners", RT["astral-projection-for-beginners"]],
        ["astral-projection-techniques-rope-roll-out-phasing-compared", RT["astral-projection-techniques-rope-roll-out-phasing-compared"]],
        ["astral-lab-app-review", RT["astral-lab-app-review"]],
        ["vibrational-state-obe-precursor-recognition", RT["vibrational-state-obe-precursor-recognition"]],
    ],
    "references": [
        "Monroe, R.A. (1971). Journeys Out of the Body.",
        "Fox, J. (1962). The Challenge of the Unknown.",
        "Raduga, M. (2021). The Phase: Practitioner's Handbook.",
    ],
    "howto": [
        {"name": "Set the intention nightly", "text": "Write a one-sentence exit intention before bed and log it in the app."},
        {"name": "Use a consistent exit technique", "text": "Pick one technique and use it every session rather than switching."},
        {"name": "Log everything", "text": "Record vibrations, sleep paralysis, partial exits, and full projections."},
        {"name": "Review at day 30", "text": "Compare week 1 to week 4 and note what changed."},
    ],
    "toc": [
        ["why-30-days", "Why 30 Days"],
        ["the-protocol", "The Protocol"],
        ["week-1", "Week 1: Nothing Happened"],
        ["week-2", "Week 2: The Vibrations"],
        ["weeks-3-4", "Weeks 3-4: Partial Exits"],
        ["results", "Results Table"],
        ["lessons", "Lessons Learned"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Astral projection is a skill most people try once and give up. I decided to practice nightly for 30 days and log every result, however small."},
        {"t": "h2", "id": "why-30-days", "text": "Why 30 Days"},
        {"t": "p", "text": "Most astral projection research spans years but practitioner handbooks suggest 30 consecutive days is enough to establish the habit and encounter the vibration state at least once."},
        {"t": "h2", "id": "the-protocol", "text": "The Protocol"},
        {"t": "p", "text": "Same technique every night: WBTB at 5 hours, 10 minutes meditation, exit intention written in the <a href=\"../apps/astral-lab.html\">Astral Lab</a> app, rope technique as primary exit method."},
        {"t": "h2", "id": "week-1", "text": "Week 1: Nothing Happened"},
        {"t": "p", "text": "Nights 1-7 produced nothing except better sleep and more vivid dreams. No vibrations, no sleep paralysis, no partial exit. Frustrating but expected."},
        {"t": "h2", "id": "week-2", "text": "Week 2: The Vibrations"},
        {"t": "p", "text": "Night 9 I felt the vibration state for the first time. Buzzing through the body, loud noise in the ears, a sensation of separating. I panicked and lost it. By night 12 I could induce vibrations within 20 minutes of the WBTB protocol."},
        {"t": "h2", "id": "weeks-3-4", "text": "Weeks 3-4: Partial Exits"},
        {"t": "p", "text": "Night 19 I achieved what I believe was a partial exit: one arm free of the body while the rest remained asleep. Night 26 was the closest to a full exit: I felt the whole body separate but snapped back before full separation."},
        {"t": "h2", "id": "results", "text": "Results Table"},
        {"t": "table", "headers": ["Week", "Sessions", "Vibrations", "Partial Exit", "Full Exit"], "rows": [
            ["Week 1", "7", "0", "0", "0"],
            ["Week 2", "7", "5", "0", "0"],
            ["Week 3", "7", "6", "1", "0"],
            ["Week 4", "7", "6", "3", "0"],
        ]},
        {"t": "h2", "id": "lessons", "text": "Lessons Learned"},
        {"t": "ul", "items": [
            "Consistency matters more than any single technique",
            "The vibration state is learnable within 10-14 days for most people",
            "Panic during vibrations is the main barrier to exit",
            "The app journal helped me see patterns I would have missed",
            "30 days is not enough for a full projection but enough to build the skill",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Did you fully project?"},
        {"t": "p", "text": "Not a full out-of-body experience in 30 days. But the vibration state became reliable and partial exits appeared. A full projection likely requires 60-90 more days."},
        {"t": "h3", "text": "Is the app necessary?"},
        {"t": "p", "text": "No, but it kept me honest. The tracking feature showed me which nights worked and which technique was most effective."},
        {"t": "h3", "text": "What was the hardest part?"},
        {"t": "p", "text": "Waking up at 5am every day. The practice itself was fascinating; the discipline was the real challenge."},
    ],
    "faq": [
        ["Did you fully project?", "Not a full OBE in 30 days, but the vibration state became reliable."],
        ["Is the app necessary?", "No, but it kept me honest with tracking and technique comparison."],
        ["What was the hardest part?", "Waking up at 5am every day for the WBTB protocol."],
    ],
}
