# -*- coding: utf-8 -*-
"""A126: I Ching Hexagram List: All 64 with One-Line Meanings"""
from related_titles import RELATED_TITLES as RT

A126 = {
    'slug': 'i-ching-hexagram-list-all-64-one-line-meanings',
    'title': 'I Ching Hexagram List: All 64 with One-Line Meanings (2026)',
    'index_title': 'I Ching Hexagram List: All 64 with One-Line Meanings',
    'desc': 'All 64 I Ching hexagrams in one reference: number, name, and a one-line meaning for each. Bookmark this page for casts and study.',
    'keywords': 'i ching hexagrams, 64 hexagrams, i ching list, hexagram meanings, book of changes, i ching reference',
    'date_iso': '2026-08-16',
    'date_display': 'August 16, 2026',
    'lastmod': '2026-08-16',
    'read_min': 10,
    'category': 'I Ching',
    'excerpt': (
        'The I Ching, or Book of Changes, organizes reality into 64 hexagrams. Each is six lines '
        'of yin and yang. This reference gives all 64 with a one-line meaning, so any cast '
        'becomes readable immediately.'
    ),
    'cta_apps': [
        ['iching-oracle', 'I Ching Oracle']
    ],
    'related': [
        ['i-ching-hexagram-meanings-complete-guide', RT['i-ching-hexagram-meanings-complete-guide']],
        ['how-to-cast-iching-digitally', RT['how-to-cast-iching-digitally']],
        ['iching-vs-tarot', RT['iching-vs-tarot']],
        ['i-ching-oracle-app-review', RT['i-ching-oracle-app-review']],
    ],
    'references': [
        'Wilhelm, R. (Trans.). (1923). The I Ching or Book of Changes. Princeton University Press.',
        'Legge, J. (Trans.). (1882). The I Ching: The Sacred Books of China. Clarendon Press.',
        'Huang, A. (1998). The Complete I Ching. Inner Traditions.',
    ],
    'howto': [
        {'name': 'Cast first, read second', 'text': 'Cast your hexagram, then find it in the list. The number and name are the entry point to the full reading.'},
        {'name': 'Read the one-liner', 'text': 'The one-line meaning is the core message. Let it frame your question before you open the deeper commentary.'},
        {'name': 'Check changing lines', 'text': 'If your cast produced changing lines, also read the transformed hexagram. The movement between two hexagrams is the real answer.'},
        {'name': 'Note the trigrams', 'text': 'Every hexagram is two trigrams. Knowing the upper and lower trigram (Heaven, Earth, Thunder, Water, Mountain, Wind, Fire, Lake) deepens the reading.'},
        {'name': 'Use the app', 'text': 'I Ching Oracle automates the cast and gives the full reference for all 64 hexagrams offline.'},
    ],
    'toc': [
        ['start', 'All 64 Hexagrams'],
        ['how-to-read-a-hexagram', 'How to Read a Hexagram'],
        ['the-complete-list', 'The Complete List'],
        ['changing-lines', 'Changing Lines'],
        ['faq', 'FAQ'],
    ],
    'sections': [
        {'t': 'p', 'text': 'The I Ching is the oldest continuous divination system in the world, in use for over 3,000 years. Its 64 hexagrams cover every situation a person can face. This list condenses each into a single working meaning.'},
        {'t': 'h2', 'text': 'How to Read a Hexagram', 'id': 'how-to-read-a-hexagram'},
        {'t': 'p', 'text': 'A hexagram is six stacked lines, each solid (yang) or broken (yin). The bottom three lines form the lower trigram; the top three form the upper trigram. Together they name the hexagram and its meaning.'},
        {'t': 'table', 'headers': ['Element', 'Trigram', 'Image'], 'rows': [
            ['Heaven', 'Qian', 'Three solid lines'],
            ['Earth', 'Kun', 'Three broken lines'],
            ['Thunder', 'Zhen', 'Solid, broken, broken'],
            ['Water', 'Kan', 'Broken, solid, broken'],
            ['Mountain', 'Gen', 'Broken, broken, solid'],
            ['Wind', 'Xun', 'Broken, solid, solid'],
            ['Fire', 'Li', 'Solid, broken, solid'],
            ['Lake', 'Dui', 'Solid, solid, broken'],
        ]},
        {'t': 'h2', 'text': 'The Complete List', 'id': 'the-complete-list'},
        {'t': 'p', 'text': 'All 64 hexagrams with number, name, and one-line meaning. Use this table to decode any cast in seconds.'},
        {'t': 'table', 'headers': ['No.', 'Name', 'One-Line Meaning'], 'rows': [
            ['1', 'The Creative (Qian)', 'Powerful initiative; heaven moving at full strength'],
            ['2', 'The Receptive (Kun)', 'Yield and receive; earth carrying all things'],
            ['3', 'Difficulty at the Beginning', 'Birth is messy; take the first step slowly'],
            ['4', 'Youthful Folly', 'Ask and learn; ignorance is a starting point'],
            ['5', 'Waiting', 'Patience while the situation ripens'],
            ['6', 'Conflict', 'Face the dispute directly; do not escalate'],
            ['7', 'The Army', 'Discipline and leadership in a crisis'],
            ['8', 'Holding Together', 'Loyalty and alliance; find your people'],
            ['9', 'The Taming Power of the Small', 'Small gestures create gradual influence'],
            ['10', 'Treading', 'Careful conduct; walk with respect'],
            ['11', 'Peace', 'Heaven and earth connect; harmonious times'],
            ['12', 'Standstill', 'Blockage; retreat and prepare'],
            ['13', 'Fellowship with Men', 'Common cause unites people'],
            ['14', 'Possession in Great Measure', 'Abundance; wield it with humility'],
            ['15', 'Modesty', 'Low posture brings safety and growth'],
            ['16', 'Enthusiasm', 'Energy and momentum; act while it flows'],
            ['17', 'Following', 'Adapt to the leader and the moment'],
            ['18', 'Work on What Has Been Spoiled', 'Repair the damage from the past'],
            ['19', 'Approach', 'Advance; the time is favorable'],
            ['20', 'Contemplation', 'Step back and observe before acting'],
            ['21', 'Biting Through', 'Decisive correction; cut through the knot'],
            ['22', 'Grace', 'Beauty and ornament; polish the surface'],
            ['23', 'Splitting Apart', 'Decay from below; strip away what is weak'],
            ['24', 'Return', 'The turning point; renewal after decline'],
            ['25', 'Innocence', 'Act without scheming; integrity carries'],
            ['26', 'The Taming Power of the Great', 'Restrain the great; build strength in stillness'],
            ['27', 'Nourishment', 'Feed the body and the mind; guard your words'],
            ['28', 'Preponderance of the Great', 'Pressure at the center; hold the bridge'],
            ['29', 'The Abysmal Water', 'Repeated peril; heart of the danger'],
            ['30', 'The Clinging Fire', 'Clarity and dependence; attach to what is good'],
            ['31', 'Influence', 'Mutual attraction; the meeting of two'],
            ['32', 'Duration', 'Constancy; slow and steady prevails'],
            ['33', 'Retreat', 'Withdraw strategically; timing is everything'],
            ['34', 'The Power of the Great', 'Strength in action; do not abuse force'],
            ['35', 'Progress', 'Rising like the sun; clear advancement'],
            ['36', 'Darkening of the Light', 'Hide your light in dark times; survive'],
            ['37', 'The Family', 'Order in the household; roles and respect'],
            ['38', 'Opposition', 'Divergence; see the other side'],
            ['39', 'Obstruction', 'Hardship on the road; turn back or find the pass'],
            ['40', 'Deliverance', 'Release from tension; the knot unties'],
            ['41', 'Decrease', 'Loss that prepares a greater gain'],
            ['42', 'Increase', 'Growth from below; generous action'],
            ['43', 'Breakthrough', 'Resolute action; the decisive step'],
            ['44', 'Coming to Meet', 'The unexpected arrival; guard the gate'],
            ['45', 'Gathering Together', 'Assembly and communion; find the center'],
            ['46', 'Pushing Upward', 'Rising through effort and merit'],
            ['47', 'Oppression', 'Exhaustion and constraint; keep the inner flame'],
            ['48', 'The Well', 'The source of life; share what sustains'],
            ['49', 'Revolution', 'Change of mandate; shed the old skin'],
            ['50', 'The Cauldron', 'Transformation; cook the raw into the nourishing'],
            ['51', 'The Arousing Thunder', 'Shock that wakes; meet it with composure'],
            ['52', 'Keeping Still', 'Mountain stillness; know when to stop'],
            ['53', 'Development', 'Gradual progress; the tree grows slowly'],
            ['54', 'The Marrying Maiden', 'Secondary role; accept the position'],
            ['55', 'Abundance', 'Fullness and peak; the moment of maximum light'],
            ['56', 'The Wanderer', 'Travel and caution; be the guest'],
            ['57', 'The Gentle Wind', 'Penetration by persistence; subtle influence'],
            ['58', 'The Joyous Lake', 'Open joy; shared delight'],
            ['59', 'Dispersion', 'The ice melts; dissolve the blockage'],
            ['60', 'Limitation', 'Boundaries create freedom; know the measure'],
            ['61', 'Inner Truth', 'Sincerity that moves without words'],
            ['62', 'Preponderance of the Small', 'Small steps, great caution; fly low'],
            ['63', 'After Completion', 'Order achieved; guard against complacency'],
            ['64', 'Before Completion', 'Almost across the river; the final caution'],
        ]},
        {'t': 'h2', 'text': 'Changing Lines', 'id': 'changing-lines'},
        {'t': 'p', 'text': 'When a cast produces changing lines, those lines turn into their opposite and form a second hexagram. The first hexagram describes the present situation; the second describes where it is heading. Read both.'},
        {'t': 'ul', 'items': [
            'A changing yang line becomes yin; a changing yin line becomes yang.',
            'The primary hexagram is the current state.',
            'The transformed hexagram is the outcome or next phase.',
            'Changing lines carry individual commentaries beyond the hexagram text.',
            'No changing lines means the situation is stable; read only the primary hexagram.',
        ]},
        {'t': 'h2', 'text': 'FAQ', 'id': 'faq'},
    ],
    'faq': [
        ('Do I need to memorize all 64 hexagrams?', 'No. The system is designed for lookup: cast, then consult the list. Over time you will naturally remember the hexagrams you encounter most. The app does the lookup for you in seconds.'),
        ('What do the numbers mean?', 'The traditional numbering follows King Wen, who arranged the hexagrams in a fixed sequence. Numbers are mnemonic anchors, not rankings. Hexagram 1 is not better than 64, just the opening of the sequence.'),
        ('Why do some readings include two hexagrams?', 'Changing lines move the cast from a primary to a transformed hexagram. The pair tells the full story: where you are and where the situation is moving. Readings without changing lines describe a stable state.'),
    ],
}