# -*- coding: utf-8 -*-
# Article 16: Fehu Rune Meaning (typed sections data)
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "fehu-rune-meaning",
    "title": "Fehu Rune Meaning: Wealth, Reversed & How to Use It (2026)",
    "index_title": "Fehu Rune Meaning",
    "desc": "Fehu is the rune of cattle, gold and moveable wealth. Learn its upright and reversed meanings, its role in divination, and how to use it for prosperity.",
    "keywords": "fehu rune meaning, fehu reversed, fehu rune wealth, fehu divination, elder futhark fehu",
    "og_alt": "The Fehu rune carved on a wooden block with gold coins beside it",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "runes",
    "excerpt": "Fehu is the first rune of the Elder Futhark for a reason: it governs wealth, value and the flow of resources. Here is everything it means upright, reversed and in practice.",
    "cta_apps": [["norse-rune-oracle", "Norse Rune Oracle"]],
    "related": [
        ["norse-runes-beginners-guide", RT["norse-runes-beginners-guide"]],
        ["rune-spreads-for-beginners", RT["rune-spreads-for-beginners"]],
        ["bindrune-wealth-protection-fehu-algiz-othala", RT["bindrune-wealth-protection-fehu-algiz-othala"]],
        ["norse-rune-oracle-app-review", RT["norse-rune-oracle-app-review"]],
    ],
    "references": [
        "Paxson, D. (2005). Taking Up the Runes: A Complete Guide to Using Runes in Spells, Rituals, Divination, and Magic. Weiser Books.",
        "Thorsson, E. (1987). Futhark: A Handbook of Rune Magic. Weiser Books.",
        "Flowers, S. (1986). Rune Might: Secret Practices of the German Rune Magicians. Llewellyn.",
    ],
    "howto": [
        {"name": "Set your question", "text": "Frame one concrete question before you draw. Vague questions produce vague answers."},
        {"name": "Draw the rune", "text": "Use the Norse Rune Oracle app or a physical rune set and draw one rune."},
        {"name": "Note the orientation", "text": "Check whether the rune landed upright or reversed, since Fehu flips meaning."},
        {"name": "Read positionally", "text": "In a spread, weigh the position and surrounding runes before concluding."},
    ],
    "toc": [
        ["what-is-fehu", "What Is Fehu?"],
        ["fehu-upright", "Fehu Upright: Core Meaning"],
        ["fehu-reversed", "Fehu Reversed: Blocked or Stolen Value"],
        ["fehu-in-divination", "Fehu in Divination"],
        ["fehu-for-prosperity", "Fehu for Prosperity Work"],
        ["fehu-in-combination", "Fehu in Combination"],
        ["common-questions", "Common Questions"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "h2", "id": "what-is-fehu", "text": "What Is Fehu?"},
        {"t": "p", "text": "Fehu (\U0001D708\U0001D708) is the first rune of the Elder Futhark, the oldest Germanic runic alphabet. Its literal name means \"cattle\" \u2014 in an age before currency, cattle were the unit of wealth, the measure of what a person owned. By extension Fehu governs money, gold, property and every form of movable wealth: the things that can change hands."},
        {"t": "p", "text": "Because it opens the entire futhark, Fehu is also the rune of beginnings and of earned value. It appears at the start of the rune row because, traditionally, nothing else can happen until resources exist."},
        {"t": "h2", "id": "fehu-upright", "text": "Fehu Upright: Core Meaning"},
        {"t": "p", "text": "Drawn upright, Fehu signals incoming value, financial gain, a new income stream, or a resource that is about to move in your direction. It rewards earned results rather than luck: the traditional reading is that value arrives because you produced something worth trading."},
        {"t": "ul", "items": [
            "New money or a raise is likely when the rune appears in a work question",
            "A purchase, sale or contract that returns more than it costs",
            "Energy, health or attention treated as a resource to invest deliberately",
            "A positive start to a new venture or project",
        ]},
        {"t": "h2", "id": "fehu-reversed", "text": "Fehu Reversed: Blocked or Stolen Value"},
        {"t": "p", "text": "Reversed, Fehu warns of loss, blocked income, missed opportunity, or value that is draining away \u2014 sometimes through other people's actions, more often through your own handling of resources. It is not a permanent curse; it is a signal to review where the leak is."},
        {"t": "ul", "items": [
            "Money owed to you that is slow to arrive, or a payment you should chase",
            "Spending that outruns income, or an investment that is not paying",
            "Possessiveness: holding value so tightly that it stops circulating and dies",
            "A career or project resource that is being misallocated",
        ]},
        {"t": "h2", "id": "fehu-in-divination", "text": "Fehu in Divination"},
        {"t": "p", "text": "In a reading, Fehu answers questions about finances, security and value exchange. It rarely speaks about romance or spirituality directly \u2014 it is the rune of the wallet, the harvest, and the fair trade. In the past position it shows how you acquired or lost resources; in the present it shows the current flow; in the future it points to an exchange coming your way."},
        {"t": "h2", "id": "fehu-for-prosperity", "text": "Fehu for Prosperity Work"},
        {"t": "p", "text": "Fehu is a favorite for prosperity rituals and bindrunes. Combined with Algiz (protection) and Othala (inherited wealth), it forms the classic wealth-protection bindrune. A simple daily practice: draw Fehu, state what value you are creating today, and picture the exchange completing."},
        {"t": "p", "text": "For digital practitioners, the <a href=\"../apps/norse-rune-oracle.html\">Norse Rune Oracle</a> app includes Fehu among the 24 Elder Futhark runes with upright and reversed readings, ideal for a daily single-rune draw."},
        {"t": "h2", "id": "fehu-in-combination", "text": "Fehu in Combination"},
        {"t": "ul", "items": [
            "Fehu + Ansuz: income through communication, writing, teaching or negotiation",
            "Fehu + Raidho: money that comes from travel, movement or a journey",
            "Fehu + Sowilo: financial clarity; a goal that becomes visible and reachable",
            "Fehu + Hagalaz: a financial disruption; review before committing more capital",
        ]},
        {"t": "h2", "id": "common-questions", "text": "Common Questions"},
        {"t": "p", "text": "Is Fehu only about money? No \u2014 it is about all movable value, including time, energy and reputation. Does Fehu guarantee wealth? No rune guarantees anything; it describes the current and most likely flow. Should I fear the reversed rune? Treat it as information, not doom: find the leak, plug it, and the rune flips."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "What does Fehu mean in love readings?"},
        {"t": "p", "text": "Fehu in a love question usually points to what each person contributes and values in the relationship \u2014 shared resources, effort balance, or a practical stage rather than pure emotion."},
        {"t": "h3", "text": "Can I use Fehu to attract money?"},
        {"t": "p", "text": "Yes. Carve or draw Fehu, charge it with the specific income you want, and act on one concrete opportunity. The rune rewards effort, not wishing."},
        {"t": "h3", "text": "Is Fehu the same as the money rune?"},
        {"t": "p", "text": "Popularly yes, but precisely it is the wealth-and-value rune: cattle, gold, and anything movable. It is broader than cash."},
    ],
    "faq": [
        ["What does Fehu mean in love readings?", "Fehu in a love question usually points to what each person contributes and values in the relationship \u2014 shared resources, effort balance, or a practical stage rather than pure emotion."],
        ["Can I use Fehu to attract money?", "Yes. Carve or draw Fehu, charge it with the specific income you want, and act on one concrete opportunity. The rune rewards effort, not wishing."],
        ["Is Fehu the same as the money rune?", "Popularly yes, but precisely it is the wealth-and-value rune: cattle, gold, and anything movable. It is broader than cash."],
    ],
}
