# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "astral-projection-verification",
    "title": "Out-of-Body Verification: How to Know You Actually Projected (2026)",
    "index_title": "Out-of-Body Verification",
    "desc": "How to verify an astral projection: the wall test, memory granularity, environment pinning, sensory checks, and journal cross-validation to separate real OBE.",
    "keywords": "astral projection verification, how to know you astral projected, out of body verification, OBE reality test",
    "og_alt": "A figure floating above their body with a checklist of verification tests beside them",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "astral-projection",
    "excerpt": "How do you know you actually projected and didn't just dream it? These six verification tests separate real out-of-body experiences from vivid hypnagogic dreams.",
    "cta_apps": [["astral-lab", "Astral Lab"]],
    "related": [
        ["astral-projection-for-beginners", RT["astral-projection-for-beginners"]],
        ["vibrational-state-obe-precursor-recognition", RT["vibrational-state-obe-precursor-recognition"]],
        ["astral-projection-techniques-rope-roll-out-phasing-compared", RT["astral-projection-techniques-rope-roll-out-phasing-compared"]],
        ["astral-lab-app-review", RT["astral-lab-app-review"]],
    ],
    "references": [
        "Monroe, R. A. (1971). Journeys Out of the Body. Doubleday.",
        "Fox, O. (1938). Astral Projection: A Record of Out-of-the-Body Experiences. Rider & Co.",
        "Raduga, M. (2021). The Phase: Shaping the Future of Immortality. CreateSpace.",
    ],
    "howto": [
        {"name": "Run the wall test during the experience", "text": "While out, walk to a wall and try to pass a hand through it. A genuine projection responds with altered physics, not instant dream-scene teleport."},
        {"name": "Pin three specific objects", "text": "Choose three small, fixed objects in your room and study each for at least ten seconds. Memorize their state."},
        {"name": "Check a clock or calendar", "text": "Read the time on a clock twice. Real projections often distort text and time; the distortion pattern itself is evidence."},
        {"name": "Cross-check with your journal", "text": "Immediately after waking, write every detail you remember. Then physically verify the three pinned objects."},
        {"name": "Grade the experience", "text": "Score it A (verified) / B (consistent, unverifiable) / C (dream-like). Only A counts as confirmed projection."},
    ],
    "toc": [
        ["why-verify", "Why Verification Matters"],
        ["the-confusion-problem", "The Confusion Problem"],
        ["wall-test", "Test 1: The Wall Test"],
        ["object-pinning", "Test 2: Object Pinning"],
        ["clock-test", "Test 3: The Clock Test"],
        ["sensory-check", "Test 4: Sensory Discrepancy"],
        ["memory-granularity", "Test 5: Memory Granularity"],
        ["journal-cross-check", "Test 6: Journal Cross-Check"],
        ["grading-system", "The A/B/C Grading System"],
        ["common-mistakes", "Common Verification Mistakes"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "You float up, hover above your bed, glide to the window — and then you wake up and doubt everything. Was that a real out-of-body experience, or did you just have an unusually vivid dream? This guide gives you six concrete verification tests you can run during and after a projection, plus a grading system so you never have to guess again."},
        {"t": "h2", "id": "why-verify", "text": "Why Verification Matters"},
        {"t": "p", "text": "Every beginner projecter faces the same wall: the experience feels absolutely real in the moment, and completely unreal five minutes after waking. Without verification, you cannot tell whether you developed an actual OBE skill or a very good imagination. Verification is not skepticism for its own sake — it is the difference between a random night and a repeatable practice you can build on."},
        {"t": "h2", "id": "the-confusion-problem", "text": "The Confusion Problem"},
        {"t": "p", "text": "Research on lucid dreaming and out-of-body states (Raduga's work with The Phase program included) shows that most beginners confuse three things: full-fledged projections, lucid dreams that begin with a projected-looking start, and vivid hypnagogic imagery that feels like movement. All three share the floating sensation. The tests below separate them."},
        {"t": "h2", "id": "wall-test", "text": "Test 1: The Wall Test"},
        {"t": "p", "text": "The moment you realize you might be out of body, find a wall and push your hand into it. In a genuine projection the wall typically offers resistance, slows your hand, or lets you pass with a tingle — the physics feels altered but present. In a dream, the scene tends to shift instantly or the wall behaves like a normal wall with no feedback. Run this early, before the experience stabilizes."},
        {"t": "h2", "id": "object-pinning", "text": "Test 2: Object Pinning"},
        {"t": "p", "text": "Before you even attempt a projection, pick three small fixed objects in your room — a clock on a shelf, a crack in the ceiling, a particular book spine. Memorize their exact state. During the projection, study each one for ten seconds. After waking, check them physically. If the crack, the angle, or the book position matches what you saw out of body, you have real evidence."},
        {"t": "h2", "id": "clock-test", "text": "Test 3: The Clock Test"},
        {"t": "p", "text": "Awareness of time is notoriously unreliable in non-physical states. Read a clock or watch twice, looking away between reads. In genuine projections, the time often changes, the digits look wrong, or the second read makes no sense. That specific distortion pattern — readable but inconsistent — is a strong marker that you were not simply awake. A dream, by contrast, usually shows you a plausible fixed time with no second read."},
        {"t": "h2", "id": "sensory-check", "text": "Test 4: Sensory Discrepancy"},
        {"t": "p", "text": "Test your senses one by one. In a projection, touch is usually the most stable, smell often absent or distorted, and sound selective — you might hear a distant conversation but not the hum of your fridge. Write down which senses worked and which failed. Dreams tend to produce coherent multi-sensory scenes; projections produce inconsistent ones. The inconsistency is diagnostic."},
        {"t": "h2", "id": "memory-granularity", "text": "Test 5: Memory Granularity"},
        {"t": "p", "text": "Ask yourself immediately after waking: how much specific, verifiable detail do I remember? Dreams typically dissolve into plot summaries — 'I was running from something.' Projections retain granular detail: the angle of the window light, the texture of the rug, the position of furniture you never consciously noted. If you can recall layout details you could not have described while awake, that is evidence of genuine non-physical perception."},
        {"t": "h2", "id": "journal-cross-check", "text": "Test 6: Journal Cross-Check"},
        {"t": "p", "text": "Write everything down the second you wake, before your brain normalizes the memory. Date it, time it, note your sleep position and any technique you used (WBTB, binaural, or the exit method from our <a href=\"../blog/astral-projection-techniques-rope-roll-out-phasing-compared.html\">exit technique comparison</a>). Then, within 24 hours, physically verify the objects you pinned. A journal that matches reality is your permanent record."},
        {"t": "h2", "id": "grading-system", "text": "The A/B/C Grading System"},
        {"t": "table", "headers": ["Grade", "Requirement", "What It Means"],
         "rows": [
             ["A — Verified", "Wall test passed AND at least one pinned object confirmed physically", "Confirmed non-physical experience"],
             ["B — Consistent", "Coherent sensory/memory detail, no physical confirmation possible", "Likely projection, unverified"],
             ["C — Dream-like", "Scene shifts, coherent multi-sensory, no granular detail", "Probably vivid dream — rerun protocol"],
         ]},
        {"t": "p", "text": "Grade every single experience. Over ten sessions you will see a pattern: your A grades cluster on nights with the same preparation, the same exit method, the same pre-sleep routine. That pattern is your personal recipe — and it is far more valuable than any single dramatic experience."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Verification Mistakes"},
        {"t": "ul", "items": [
            "Verifying from memory instead of the journal — memories edit themselves within minutes",
            "Only testing one sense — dreams can pass a single casual check",
            "Trusting the 'I was definitely out' feeling alone — it is not evidence",
            "Forgetting to pin objects before sleep — you cannot verify what you never defined",
            "Grading every experience as A out of hope instead of evidence — be brutally honest",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Can I verify a projection I already had last night?"},
        {"t": "p", "text": "Only if you pinned objects or noted verifiable details at the time. Otherwise grade it B at best and rerun the full protocol tonight. The habit of pinning before sleep is what turns random experiences into data."},
        {"t": "h3", "text": "How many A-graded projections do I need to trust the skill?"},
        {"t": "p", "text": "Three A-grades using the same preparation routine is a solid benchmark. After that, you can trust your exit technique and focus on exploration instead of doubt."},
        {"t": "h3", "text": "Can an app help with verification?"},
        {"t": "p", "text": "Yes. <a href=\"../apps/astral-lab.html\">Astral Lab</a> gives you structured reality checks, a pre-sleep object-pinning reminder, and a journal template built around the A/B/C grading system — so the protocol becomes a habit instead of an afterthought."},
    ],
    "faq": [
        ["Can I verify a projection I already had last night?", "Only if you pinned objects or noted verifiable details at the time. Otherwise grade it B at best and rerun the full protocol tonight."],
        ["How many A-graded projections do I need to trust the skill?", "Three A-grades using the same preparation routine is a solid benchmark. After that, trust your exit technique and explore."],
        ["Can an app help with verification?", "Yes. Astral Lab provides structured reality checks, an object-pinning reminder before sleep, and an A/B/C journal template that makes the protocol automatic."],
    ],
}
