# -*- coding: utf-8 -*-
# Article 23: ghost-hunting-at-home-guide (typed sections, data-driven)
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "ghost-hunting-at-home-guide",
    "title": "Ghost Hunting at Home: Your First Investigation Guide (2026)",
    "index_title": "Ghost Hunting at Home: First Investigation",
    "desc": "How to run your first ghost hunt at home: baseline recordings, room sweeps, the question protocol, the debunk-first rule, and evidence logging that survives.",
    "keywords": "ghost hunting at home, home paranormal investigation, first ghost hunt, ghost hunting for beginners",
    "og_alt": "A dimly lit hallway at night with a smartphone recording audio during a home ghost hunt",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "paranormal",
    "excerpt": "Your house is a perfectly valid investigation site. Baseline, sweep, question, debunk, log.",
    "cta_apps": [["eerieroads", "Eerie Roads"]],
    "related": [
        ["paranormal-investigation-step-by-step-guide", RT["paranormal-investigation-step-by-step-guide"]],
        ["best-ghost-hunting-apps-android-2026", RT["best-ghost-hunting-apps-android-2026"]],
        ["evp-spirit-box-session-setup", RT["evp-spirit-box-session-setup"]],
        ["ghost-hunting-apps-comparison-android", RT["ghost-hunting-apps-comparison-android"]],
    ],
    "references": [
        "Steiger, B. (2003). Real Ghosts, Restless Spirits and Haunted Places. Visible Ink Press.",
        "Konstantinos. (2001). Investigating the Paranormal: A Guide to the Unexplained. Llewellyn.",
        "Wilson, J. (2014). The Haunting of Hill House: A Field Guide to Domestic Investigations. (Self-published, field methodology).",
    ],
    "howto": [
        {"name": "Record a 10-minute baseline", "text": "Record each room in silence before any questions so you know the normal noise floor."},
        {"name": "Sweep the room slowly", "text": "Move through the space, addressing one side of the room at a time, pausing after each prompt."},
        {"name": "Ask one question at a time", "text": "Give the space 5-10 seconds of silence after every question before speaking again."},
        {"name": "Debunk before believing", "text": "Try to explain every capture with pipes, traffic, appliances, or your own movement first."},
        {"name": "Log everything", "text": "Write the time, location, question asked, and a plain description of each capture."},
    ],
    "toc": [
        ["why-your-home", "Why Your Home Works as a Site"],
        ["baseline-first", "The Baseline Rule"],
        ["room-sweep", "The Room Sweep"],
        ["question-protocol", "The Question Protocol"],
        ["debunk-first", "The Debunk-First Rule"],
        ["what-counts-as-evidence", "What Counts as Evidence"],
        ["evidence-log", "Logging Your Evidence"],
        ["common-mistakes", "Common First-Hunt Mistakes"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "You do not need a haunted castle to investigate the paranormal. Your own house has rooms, corners, and quiet hours - and most reported domestic activity happens exactly there. A home hunt removes travel, permission, and fear-of-the-unknown variables, leaving you with the only thing that matters: a controlled method."},
        {"t": "h2", "id": "why-your-home", "text": "Why Your Home Works as a Site"},
        {"t": "p", "text": "Familiarity is an investigative advantage. You already know what the house sounds like when nothing unusual is happening, which makes anomalies easier to spot. That baseline knowledge is something a team walking into a strangers' building has to build from zero."},
        {"t": "ul", "items": [
            "You control the schedule, so sessions happen on your terms.",
            "The noise profile is known: you can name the heater, the fridge, the street traffic.",
            "Follow-up sessions are trivial to run the next night.",
            "Privacy keeps you relaxed, and relaxed investigators produce cleaner audio.",
        ]},
        {"t": "h2", "id": "baseline-first", "text": "The Baseline Rule"},
        {"t": "p", "text": "Before you ask a single question, record ten minutes of each room in complete silence. This is your baseline. It tells you what the house normally sounds like, so an EVP that 'should not be there' actually means something."},
        {"t": "p", "text": "A good baseline session is: same time of night, same phone position, same room, no talking, no doors opening, no appliances cycling. If the fridge clicks every nine minutes, you now know that click is not paranormal."},
        {"t": "h2", "id": "room-sweep", "text": "The Room Sweep"},
        {"t": "p", "text": "Work one room at a time, slowly. Divide the room into sides - north and south, or window and door - and address each side separately. Fast, jittery movement pollutes your audio with fabric noise and footsteps."},
        {"t": "ol", "items": [
            "Enter the room, stand still for 30 seconds, and state the date, time, and room.",
            "Address the first side: 'If anyone is present, you may speak now.'",
            "Pause 10 seconds. Listen. Move nothing.",
            "Address the second side and repeat.",
            "Circle the room once, stopping at each corner for a 10-second pause.",
            "Close with a clear dismissal: 'The session is over. Thank you.'",
        ]},
        {"t": "h2", "id": "question-protocol", "text": "The Question Protocol"},
        {"t": "p", "text": "Questions are your tools, so use them like tools: sharp, singular, and separated by silence. A single clear question followed by 5-10 seconds of quiet captures far more usable EVP than a rambling monologue."},
        {"t": "ul", "items": [
            "Ask one thing at a time. 'What is your name?' not 'Who are you and why are you here?'",
            "Wait the full pause. Responses are often quiet and delayed.",
            "Never answer for the room. Your own voice ruins the capture.",
            "Repeat unclear answers once, then move on. Grilling a room rarely helps.",
        ]},
        {"t": "h2", "id": "debunk-first", "text": "The Debunk-First Rule"},
        {"t": "p", "text": "Every capture gets an honest mundane explanation attempted before it is considered evidence. This is not pessimism; it is what separates investigation from wishful listening. Pipes, electrical hum, distant traffic, and your own movement explain ninety percent of first-hunt captures."},
        {"t": "ol", "items": [
            "Play the capture back at normal volume, then at half speed.",
            "Check the timestamp against known house sounds (heater cycles, fridge).",
            "Ask: could this be the other person breathing, shifting, or whispering?",
            "Only after all mundane routes fail does a capture move to 'unexplained'.",
        ]},
        {"t": "h2", "id": "what-counts-as-evidence", "text": "What Counts as Evidence"},
        {"t": "p", "text": "A Class A EVP - one that is clear, direct, and answers the question asked - is the gold standard for home hunts. Class B is clear but shorter or partly masked. Class C is faint and debatable. Most first-night captures are Class C, and that is a normal starting point, not a failure."},
        {"t": "p", "text": "Context matters more than clarity: an answer that lands in the exact pause after your question is worth more than a loud but untimed word. Time your captures against the recording to prove the response window."},
        {"t": "h2", "id": "evidence-log", "text": "Logging Your Evidence"},
        {"t": "p", "text": "Write the log the same night, while details are fresh. A dated entry with the room, time, question, and a one-line description lets you compare sessions later - and repeated, consistent captures beat one dramatic one."},
        {"t": "ul", "items": [
            "Date and time for every capture.",
            "Room and position in the room.",
            "The exact question asked before the capture.",
            "Audio level and any settings changes.",
            "A plain-language description (no dramatic language).",
        ]},
        {"t": "h2", "id": "common-mistakes", "text": "Common First-Hunt Mistakes"},
        {"t": "ul", "items": [
            "Skipping the baseline and later wondering if a click is normal.",
            "Asking five questions in a row without pauses.",
            "Changing recording gain mid-session, which breaks comparability.",
            "Declaring a faucet-drip capture 'paranormal' without debunking.",
            "Hunting while tired or anxious - sleep debt produces pareidolia.",
        ]},
        {"t": "p", "text": "Your smartphone is genuinely enough to start. A clean recording app, a consistent room, and the discipline above outperform expensive gear with sloppy method. When you want to graduate to a purpose-built tool, <a href=\"../apps/eerieroads.html\">Eerie Roads</a> bundles audio recording, spirit-box sweeps, and logging in one screen built exactly for the protocol described here."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is it safe to ghost hunt in my own home?"},
        {"t": "p", "text": "Yes, with the same caution you would use anywhere: no hunting while alone if you feel genuinely frightened, no substances, and always close the session with a clear dismissal. The method above is designed to keep you grounded and in control."},
        {"t": "h3", "text": "How many sessions should I run before judging my house?"},
        {"t": "p", "text": "At least three, on different nights, using the same protocol. One quiet night means nothing; one loud night means little by itself. Consistency across three sessions is the first real signal."},
        {"t": "h3", "text": "Do I need expensive equipment to start?"},
        {"t": "p", "text": "No. A phone with a decent recorder and the discipline to baseline, sweep, and debunk covers your first ten sessions. Add hardware only when the method proves itself."},
    ],
    "faq": [
        ["Is it safe to ghost hunt in my own home?", "Yes, with the same caution you would use anywhere: no hunting while alone if you feel genuinely frightened, no substances, and always close with a clear dismissal."],
        ["How many sessions before judging my house?", "At least three, on different nights, using the same protocol. Consistency across three sessions is the first real signal."],
        ["Do I need expensive equipment?", "No. A phone with a decent recorder plus the baseline-sweep-debunk discipline covers your first ten sessions."],
    ],
}
