# -*- coding: utf-8 -*-
# Article 44 (batch A2 #4): NOCTEM Paranormal Suite feature tour.
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "noctem-feature-tour-guide",
    "title": "NOCTEM Paranormal Suite: Complete Feature Tour (2026)",
    "index_title": "NOCTEM Feature Tour: The Full Paranormal Suite",
    "desc": "A complete tour of NOCTEM, the all-in-one paranormal suite: EVP recorder, spirit box, SLS-style camera, EMF meter, and investigation logger in one app.",
    "keywords": "noctem app, noctem paranormal suite, paranormal app suite, evp recorder app, sls camera app, ghost hunting app android, noctem tools",
    "og_alt": "The NOCTEM paranormal investigation suite showing its instrument panel on a phone screen",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "paranormal",
    "excerpt": "NOCTEM bundles an EVP recorder, spirit box, SLS-style camera, EMF meter, and a session logger into one offline suite. Here is every instrument, and how to use it.",
    "cta_apps": [["noctem-tools", "NOCTEM Paranormal Suite"]],
    "related": [
        ["evp-spirit-box-session-setup", RT["evp-spirit-box-session-setup"]],
        ["spirit-box-frequency-settings", RT["spirit-box-frequency-settings"]],
        ["noctem-tools-app-review", RT["noctem-tools-app-review"]],
        ["eerieroads-90-night-review", "Eerie Roads Reviewed After 90 Nights of EVP Sessions (2026)"],
    ],
    "references": [
        "Konstantinos, P. (2001). Ghost Hunting for Beginners. Career Press.",
        "Oester, D. (2015). Unexplained Magazine field investigation protocols.",
        "Mack, J. (2021). The Paranormal Investigation Field Manual.",
    ],
    "howto": [
        {"name": "Plan the session", "text": "Pick a room, set a 10-minute baseline, and note the time, weather, and who is present before opening any instrument."},
        {"name": "Run the recorder", "text": "Open the EVP recorder, set gain to a quiet room tone, and ask one question at a time with a 5-10 second pause."},
        {"name": "Sweep with the spirit box", "text": "Switch to the spirit box, choose a band and sweep rate, and repeat questions in the same room."},
        {"name": "Scan with the camera", "text": "Use the SLS-style camera to scan corners and furniture slowly, watching for skeletal silhouettes."},
        {"name": "Log and close", "text": "Close every instrument, dismiss the session in the logger, and review your audio with the debunk-first rule."},
    ],
    "toc": [
        ["what-is-noctem", "What Is NOCTEM?"],
        ["the-instruments", "The Instruments"],
        ["evp-recorder", "EVP Recorder"],
        ["spirit-box", "Spirit Box"],
        ["sls-camera", "SLS-Style Camera"],
        ["emf-meter", "EMF Meter"],
        ["session-logger", "Session Logger"],
        ["one-app-vs-separate", "One App vs Separate Tools"],
        ["getting-started", "Getting Started"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "h2", "id": "what-is-noctem", "text": "What Is NOCTEM?"},
        {"t": "p", "text": "NOCTEM is the all-in-one paranormal investigation suite: EVP recorder, spirit box, SLS-style camera, EMF meter, and a structured session logger packaged into a single offline app. Instead of juggling five apps with five sets of settings, you run one instrument panel and one timeline of evidence."},
        {"t": "p", "text": "It is the heavier sibling of Eerie Roads. Where Eerie Roads is a focused EVP and spirit box tool, NOCTEM is the full instrument rack for a serious investigation. You pay once, everything is local, and no instrument needs an account."},
        {"t": "h2", "id": "the-instruments", "text": "The Instruments"},
        {"t": "table", "headers": ["Instrument", "What It Does", "Best For"], "rows": [
            ["EVP recorder", "Captures room audio with gain and tone controls", "Class A/B/C voice captures"],
            ["Spirit box", "Sweeps radio bands for fragmentary voices", "Live back-and-forth questions"],
            ["SLS-style camera", "Maps depth and highlights humanoid silhouettes", "Empty-room scanning"],
            ["EMF meter", "Measures electromagnetic field changes", "Spike correlation with events"],
            ["Session logger", "Timestamps every reading into one timeline", "Evidence review and reports"],
        ]},
        {"t": "h2", "id": "evp-recorder", "text": "The EVP Recorder"},
        {"t": "p", "text": "The recorder is built around the idea that gain and room tone matter more than exotic filters. You set the level against a 60-second silent baseline, ask one question, pause five to ten seconds, and move on. Captures are graded Class A, B, or C after review — never during the session."},
        {"t": "h2", "id": "spirit-box", "text": "The Spirit Box"},
        {"t": "p", "text": "The spirit box sweeps a chosen frequency band at a rate you control. Fast sweeps produce clipped fragments; medium sweeps (150-300ms) produce partial words; slow sweeps produce fuller phrases with longer gaps. Start on VHF FM and adjust from there."},
        {"t": "h2", "id": "sls-camera", "text": "The SLS-Style Camera"},
        {"t": "p", "text": "The camera uses depth-mapping software to highlight humanoid silhouettes in the field of view. It is a visualization aid, not a detector: it draws a figure where depth and motion match a body shape, and pareidolia produces false positives. Treat every hit as a lead, never as proof."},
        {"t": "h2", "id": "emf-meter", "text": "The EMF Meter"},
        {"t": "p", "text": "The EMF meter plots field strength over time and flags spikes. The honest use is correlation: did the EMF spike at the same moment the recorder captured something? Correlated spikes are interesting; standalone spikes are usually wiring, phones, or appliances."},
        {"t": "h2", "id": "session-logger", "text": "The Session Logger"},
        {"t": "p", "text": "Every reading is timestamped into one investigation timeline: recorder level, spirit box band, camera hit, EMF spike, and your own notes. The logger is what turns a chaotic session into a reviewable document."},
        {"t": "h2", "id": "one-app-vs-separate", "text": "One App vs Separate Tools"},
        {"t": "ul", "items": [
            "One timeline: events are correlated by timestamp, not by your memory",
            "One settings profile: you do not reconfigure five apps between rooms",
            "One purchase: one-time price, no per-instrument subscriptions",
            "One privacy posture: all recordings and logs stay on your device",
            "One learning curve: learn the suite once, run any instrument",
        ]},
        {"t": "h2", "id": "getting-started", "text": "Getting Started"},
        {"t": "ol", "items": [
            "Install NOCTEM and run a 10-minute baseline in your chosen room",
            "Do one recorder pass: one question at a time, 5-10 second pauses",
            "Repeat the questions with the spirit box on VHF FM at medium sweep",
            "Scan the room once with the camera, then once with the EMF meter",
            "Close the session in the logger and review with the debunk-first rule",
            "Repeat the same protocol for at least three sessions before judging",
        ]},
        {"t": "p", "text": "Ready to run your first full investigation? <a href=\"../apps/noctem-tools.html\">Get NOCTEM Paranormal Suite</a> — one-time payment, no subscription, no ads, no account."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is NOCTEM the same as Eerie Roads?"},
        {"t": "p", "text": "No. Eerie Roads is the focused EVP and spirit box tool. NOCTEM adds the SLS-style camera, EMF meter, and session logger for a complete investigation."},
        {"t": "h3", "text": "Is the SLS camera real detection?"},
        {"t": "p", "text": "It is depth-mapping visualization. It highlights shapes that match a humanoid silhouette; pareidolia produces false positives, so hits are leads to correlate, never proof."},
        {"t": "h3", "text": "Where do my recordings go?"},
        {"t": "p", "text": "On your device. NOCTEM has no cloud sync and no account, so your evidence and notes never leave your phone."},
    ],
    "faq": [
        ["Is NOCTEM really one-time payment?", "Yes. One purchase unlocks every instrument, forever. No subscription, no ads, no in-app paywalls."],
        ["Do I need internet for an investigation?", "No. Every instrument works offline, which matters in basements and remote locations."],
        ["Can I export my session log?", "Yes. Sessions can be exported from the logger for review or sharing."],
    ],
}
