# -*- coding: utf-8 -*-
"""
articles_a.py — Structured data for articles 1-5 (data-driven, no hardcoded HTML).

Each article is a dict consumed by build_10_articles.py. The `sections` list
uses typed entries: {t: "p"|"h2"|"h3"|"ul"|"ol"|"table", ...}.
"""

ARTICLES_A = [
    {
        "slug": "which-goetia-spirit-for-love-money-knowledge",
        "title": "Which Goetia Spirit Should You Call? Love, Money & Knowledge (2026)",
        "index_title": "Which Goetia Spirit for Love, Money & Knowledge?",
        "desc": "The 72 spirits of the Ars Goetia sorted by purpose: the exact demon to call for love, money, and knowledge, with ranks, legions, and safe evocation steps.",
        "keywords": "goetia spirit for love, goetia spirit for money, goetia spirit for knowledge, which goetia spirit to summon, ars goetia spirits by purpose, goetia love spell",
        "og_alt": "Goetia spirits sorted by purpose — love, money, and knowledge",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 14,
        "category": "goetia",
        "excerpt": "Bael, Paimon, Sitri, Bune, Marbas — 72 spirits listed alphabetically help no one. Here is the Ars Goetia re-sorted by purpose: love, money, and knowledge, with ranks and legions.",
        "cta_apps": [["arcana-goetia", "Arcana Goetia"]],
        "related": [
            ["goetia-beginners-ritual", "How to Safely Invoke a Goetic Spirit for Beginners: Step-by-Step Ritual 2026"],
            ["austin-osman-spare-sigil-method", "Austin Osman Spare Sigilization: The Original Method..."],
            ["zener-cards-esp-training-guide", "Zener Cards ESP Training Guide"],
            ["best-goetia-books-essential-reading-2026", "Best Goetia Books: Essential Reading for Solomonic Magic Practitioners 2026"],
        ],
        "references": [
            "Mathers, S. L. & Crowley, A. — The Lesser Key of Solomon (Goetia).",
            "Weyer, J. — Pseudomonarchia Daemonum (1583).",
            "Peterson, J. H. — The Lesser Key of Solomon (edition and translation).",
        ],
        "howto": [
            {"name": "Choose a purpose", "text": "Decide whether the working is for love, money, or knowledge, and phrase it as one clear sentence."},
            {"name": "Pick the matching spirit", "text": "Use the purpose tables to select the spirit whose dominion matches your request."},
            {"name": "Prepare a protective space", "text": "Set up a quiet area, cast a banishing ritual if you have one, and keep the spirit's seal on hand."},
            {"name": "State the request", "text": "Speak the spirit's name and your request aloud, clearly and without ambiguity."},
            {"name": "Dismiss and ground", "text": "Thank the spirit, close the working, and ground yourself with food, water, or a walk."},
        ],
        "toc": [
            ["why-purpose-matters", "Why Purpose Matters"],
            ["the-72-spirits", "The 72 Spirits: Rank & Legion, Explained"],
            ["love-spirits", "Spirits for Love & Attraction"],
            ["money-spirits", "Spirits for Money & Wealth"],
            ["knowledge-spirits", "Spirits for Knowledge & Divination"],
            ["how-to-evoke", "How to Evoke a Goetia Spirit Safely"],
            ["common-mistakes", "Common Mistakes to Avoid"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "why-purpose-matters", "text": "Why Purpose Matters"},
            {"t": "p", "text": "The Ars Goetia lists its 72 spirits alphabetically — Bael first, Andromalius last. Alphabetical order is fine for study and useless for practice. When you need a specific outcome, what you actually want is a lookup table: which spirit rules love, which one opens doors for money, and which one teaches hidden knowledge. That table is exactly what this guide gives you."},
            {"t": "p", "text": "Every rank and legion count below comes from the standard source material: the First Book of the Lesser Key of Solomon (the Goetia), Johann Weyer's Pseudomonarchia Daemonum, and Peterson's critical edition. The spirit names are the traditional ones; the attributions follow the grimoire text, not modern inventions."},
            {"t": "h2", "id": "the-72-spirits", "text": "The 72 Spirits: Rank & Legion, Explained"},
            {"t": "p", "text": "The 72 spirits are organized by rank: King, Prince, Duke, Marquis, Count, President, and Knight. Rank matters more than people assume — a King like Paimon commands 200 legions and expects a formal approach, while a President like Marbas answers with clinical efficiency. Matching your request to the right rank keeps the working clean."},
            {"t": "p", "text": "A legion is the grimoire's unit of command: roughly 1,000 spirits. Spirit with more legions is not 'stronger' in any simple sense — it governs more territory, which often means broader but less surgical results. A Duke with 26 legions can be far more practical for a single focused request than a King with 66."},
            {"t": "h2", "id": "love-spirits", "text": "Spirits for Love & Attraction"},
            {"t": "p", "text": "Traditionally, love work in the Goetia means attraction, lust, and the union of couples. These are the spirits the grimoire assigns to that dominion, with their rank and legions:"},
            {"t": "table", "headers": ["Spirit", "Rank", "Legions", "Traditional Dominion"],
             "rows": [
                ["Sitri", "Prince", "60", "Attraction, lust, uncovering secrets of love"],
                ["Zepar", "Duke", "26", "Causing love and lust, making women love men"],
                ["Sallos", "Duke", "30", "Causing love between men and women"],
                ["Vepar", "Duke", "29", "Governing waters and love affairs"],
                ["Gremory", "Duke", "26", "Love and treasure, finding hidden things"],
                ["Vual", "Duke", "37", "Love between people, reconciliation of lovers"],
             ]},
            {"t": "p", "text": "For a gentle, long-term attraction working, Sallos is the most approachable. For driving passion quickly, Sitri or Zepar. Gremory doubles as a money spirit, which makes her a good choice when love and stability are linked."},
            {"t": "h2", "id": "money-spirits", "text": "Spirits for Money & Wealth"},
            {"t": "table", "headers": ["Spirit", "Rank", "Legions", "Traditional Dominion"],
             "rows": [
                ["Bael", "King", "66", "Wealth, invisibility, making one wise"],
                ["Bune", "Duke", "30", "Riches, wealth, changing the dead"],
                ["Agares", "Duke", "31", "Dignities, languages, causing people to flee"],
                ["Gremory", "Duke", "26", "Treasure, love, finding hidden riches"],
                ["Zagan", "King", "33", "Turning base metals, wealth, sharpening wit"],
             ]},
            {"t": "p", "text": "Bune is the classic wealth spirit — patient, direct, and widely worked by practitioners who want steady money rather than lottery luck. Bael works well for career and status gains. Zagan suits magical alchemy and business strategy."},
            {"t": "h2", "id": "knowledge-spirits", "text": "Spirits for Knowledge & Divination"},
            {"t": "table", "headers": ["Spirit", "Rank", "Legions", "Traditional Dominion"],
             "rows": [
                ["Vassago", "Prince", "26", "Past, present, and future; finding hidden things"],
                ["Paimon", "King", "200", "All sciences, arts, and hidden knowledge"],
                ["Marbas", "President", "36", "Answers to questions, healing, mechanics"],
                ["Dantalion", "Duke", "36", "All minds and thoughts, teaching arts and sciences"],
                ["Astaroth", "Duke", "40", "Liberal sciences, past and future"],
                ["Stolas", "Prince", "26", "Astronomy, herbs, and precious stones"],
                ["Amon", "Marquis", "40", "Past and future, reconciliation, sharpening intellect"],
             ]},
            {"t": "p", "text": "For study, exams, or creative work, Marbas is the workhorse. For divination and insight into a situation, Vassago or Amon. For deep occult and scientific knowledge, Paimon — but expect a formal ceremony; a King of 200 legions does not answer a casual whisper."},
            {"t": "h2", "id": "how-to-evoke", "text": "How to Evoke a Goetia Spirit Safely"},
            {"t": "p", "text": "Evocation is the practice of calling a spirit into a ritual space for a request. It is a discipline, not a party trick. Follow a fixed structure every time:"},
            {"t": "ol", "items": [
                "State your purpose in one sentence before you begin. If you cannot say it plainly, you are not ready.",
                "Pick the spirit whose dominion matches that purpose, and draw or display its correct seal.",
                "Set up a quiet, clean space and perform a banishing ritual — the Lesser Banishing Ritual of the Pentagram is the standard — to clear interference.",
                "Recite the traditional invocation, then speak the spirit's name and your request clearly.",
                "Keep your request specific, time-bound, and ethical. 'Bring me a better-paying job by the new moon' beats 'make me rich.'",
                "When the working is done, thank the spirit, formally dismiss it, and ground yourself with food, water, and physical movement.",
            ]},
            {"t": "p", "text": "Practitioners who skip the banishing or the dismissal tend to report noisy sessions and muddled results. The ritual container is what keeps the working clean."},
            {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes to Avoid"},
            {"t": "ul", "items": [
                "Calling a King when a Duke would do. Match rank to task, not to ego.",
                "Asking for vague outcomes. 'Money' means nothing; 'a specific job offer by Friday' means something.",
                "Skipping the banishing and the dismissal. The bookkeeping of a ritual is half the ritual.",
                "Working while exhausted, intoxicated, or emotionally raw. State of mind is state of circle.",
                "Ignoring the seal. The seal is the spirit's address; get it right or get nothing.",
            ]},
            {"t": "p", "text": "A digital reference keeps the seal accurate and the descriptions at hand — <a href=\"../apps/arcana-goetia.html\">Arcana Goetia</a> carries all 72 spirits with their seals, ranks, and legions, so the grimoire is never misquoted mid-working."},
        ],
        "faq": [
            ["Is Goetia practice dangerous?", "Like any ritual work, it rewards preparation and punishes carelessness. A clean space, a clear purpose, and a formal dismissal keep the practice safe and effective."],
            ["Can I use a Goetia spirit for love without free will issues?", "Traditional love spirits work on attraction and circumstance, not on overriding anyone. Frame requests around openness and opportunity rather than control."],
            ["Do I need to memorize all 72 spirits?", "No. Use a lookup by purpose — that is exactly what this guide and apps like Arcana Goetia are for. Memorize the ones you actually work with."],
        ],
    },
    {
        "slug": "zener-card-test-score-meaning",
        "title": "Zener Card Test Score Meaning: What Your ESP Score Really Says (2026)",
        "index_title": "Zener Card Test Score Meaning: What Your ESP Score Really Says",
        "desc": "What does a Zener card score actually mean? Chance baselines, psi-hitting vs psi-missing, when a score is statistically significant, and how to improve your.",
        "keywords": "zener card score meaning, zener card test results, what does a zener card score mean, ESP score significance, psi-hitting vs psi-missing, zener card test scoring",
        "og_alt": "Zener card test score interpretation chart",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 11,
        "category": "esp",
        "excerpt": "Scored 9 out of 25 on the Zener card test? Good or bad? Here is the exact math: chance baseline, when a score means something, and what psi-hitting and psi-missing actually tell you.",
        "cta_apps": [["psi-gym", "PSI GYM: Zener Cards & ESP"]],
        "related": [
            ["zener-cards-esp-training-guide", "Zener Cards ESP Training Guide"],
            ["psi-gym-app-review", "PSI GYM App Review"],
            ["remote-viewing-techniques-beginners", "Remote Viewing for Beginners: Techniques, Training & Tools"],
            ["best-esp-training-apps-android", "Best ESP Training Apps for Android"],
        ],
        "references": [
            "Rhine, J. B. — Extra-Sensory Perception (1934), Boston Society for Psychical Research.",
            "Zener, K. & Rhine, J. B. — Duke University card-guessing protocols (1930s).",
            "The Psychical Research Foundation — ESP testing methodology and statistics.",
        ],
        "howto": [
            {"name": "Understand the baseline", "text": "With 5 symbols, chance alone predicts 1 hit in 5 — 20% or 5 of 25."},
            {"name": "Run a full run", "text": "Complete a 25-card run and record how many you guessed correctly."},
            {"name": "Compare to chance", "text": "Subtract 5 from your score; the remainder is your margin above chance."},
            {"name": "Check significance", "text": "Scores of 9-10 hint at an effect; 11+ out of 25 is where statistical significance (p < 0.05) begins."},
            {"name": "Track trends over time", "text": "One run proves nothing; log runs over weeks to separate noise from signal."},
        ],
        "toc": [
            ["how-the-test-works", "How the Zener Test Works"],
            ["chance-baseline", "The Chance Baseline: 1 in 5"],
            ["score-table", "What Your Score Means (Score Table)"],
            ["significance", "When a Score Is Significant"],
            ["psi-hitting", "Psi-Hitting vs Psi-Missing"],
            ["improve-your-score", "How to Improve Your Score"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "how-the-test-works", "text": "How the Zener Test Works"},
            {"t": "p", "text": "The Zener card test is the classic ESP protocol designed by psychologist Karl Zener and parapsychologist J. B. Rhine at Duke University in the 1930s. A standard deck has 25 cards divided among five symbols: circle, cross, waves, square, and star. The receiver tries to guess the symbol on the hidden card; the run produces a score out of 25."},
            {"t": "p", "text": "It became the laboratory standard because it produces a number you can compare against pure chance. No interpretation is needed — the math does the talking."},
            {"t": "h2", "id": "chance-baseline", "text": "The Chance Baseline: 1 in 5"},
            {"t": "p", "text": "Five symbols, one guess, so chance predicts exactly 1 correct guess in 5 — 20%. Across a 25-card run, the expected score from pure luck is 5 out of 25. Everything above or below that 5 is your margin above or below chance."},
            {"t": "p", "text": "A score of 5 means the deck might as well be shuffled for you. A score of 6 or 7 is barely above chance and could be a good streak. The interesting territory starts at 9 and up."},
            {"t": "h2", "id": "score-table", "text": "What Your Score Means (Score Table)"},
            {"t": "table", "headers": ["Score (of 25)", "Interpretation", "What to Do"],
             "rows": [
                ["0-4", "Below chance — possible psi-missing", "Run again in a calm state; check for mental noise"],
                ["5", "Exactly chance — 20%", "Normal baseline; nothing to interpret"],
                ["6-8", "Above chance but within noise", "Keep training; log runs to spot a trend"],
                ["9-10", "Notable — hints at a real effect", "Repeat the protocol; consistent 9-10s matter"],
                ["11-14", "Significant — p < 0.05 territory", "You have a measurable ESP signal; standardize your method"],
                ["15+", "Strongly significant", "Rare; document the conditions carefully"],
             ]},
            {"t": "h2", "id": "significance", "text": "When a Score Is Significant"},
            {"t": "p", "text": "Statistical significance is the threshold where a score is unlikely to be luck. With the Zener deck, a single 25-card run crosses the conventional p < 0.05 line around 11 correct guesses. The original Rhine-era protocols often used longer runs — a 50-card run with 17+ correct was considered significant under the z-test — but the principle is the same: the farther your score climbs past chance, the less likely it is to be coincidence."},
            {"t": "p", "text": "One high run is a fluke candidate; consistent high runs are a signal. If you hit 11+ once, retest tomorrow. If you keep hitting it, you are doing something real."},
            {"t": "h2", "id": "psi-hitting", "text": "Psi-Hitting vs Psi-Missing"},
            {"t": "p", "text": "Two patterns appear in the research. Psi-hitting is scoring significantly ABOVE chance — the classic 'I guessed the star again' effect. Psi-missing is scoring significantly BELOW chance, which sounds like failure but is actually its own phenomenon: the receiver is consistently avoiding the correct symbol, which is also statistically impossible by luck."},
            {"t": "p", "text": "Psi-missing usually signals internal interference — expectation, tension, or a noisy mind — actively steering guesses away from the target. Many practitioners treat it as a diagnostic: clean up your state and the direction flips."},
            {"t": "h2", "id": "improve-your-score", "text": "How to Improve Your Score"},
            {"t": "ul", "items": [
                "Run tests in a quiet, dim space. External noise suppresses the signal.",
                "Log every run with date, time, and state of mind. Trends matter more than singles.",
                "Go with your first impression. Overthinking converts hits into misses.",
                "Use a consistent symbol set and a blind protocol — you should not see the target until after you guess.",
                "Take breaks. Fatigue turns psi-hitting into psi-missing.",
            ]},
            {"t": "p", "text": "A digital trainer removes the two biggest error sources: sloppy shuffling and peeking. <a href=\"../apps/psi-gym.html\">PSI GYM</a> runs the classic 25-card protocol with automatic scoring, so your numbers are honest — which is the entire point of the Zener test."},
        ],
        "faq": [
            ["Is 7 out of 25 on the Zener test good?", "It is above chance but still inside normal noise — a 7 means a hint of effect, not proof. Consistent 7s and 8s over many runs are more meaningful than a single 10."],
            ["What is a good Zener card score?", "A good score is one that holds up: 9-10 out of 25 is notable, and 11+ enters statistically significant territory. Consistency across runs beats a lucky single."],
            ["Can I train my ESP score?", "Yes. The Zener protocol was designed for repeat testing precisely because scores respond to training, state management, and consistent practice — log your runs and watch the trend line."],
        ],
    },
    {
        "slug": "how-to-charge-sigil-without-meditation",
        "title": "How to Charge a Sigil Without Meditation: 7 Fast Methods (2026)",
        "index_title": "How to Charge a Sigil Without Meditation: 7 Fast Methods",
        "desc": "Meditation not your thing? Charge sigils with box breathing, physical exertion, emotional spikes, dancing, sensory overload, laughter, and orgasmic states — no.",
        "keywords": "how to charge a sigil without meditation, sigil charging methods, charge sigil fast, sigil gnosis without meditation, chaos magic sigil activation, sigil charging techniques",
        "og_alt": "Seven sigil charging methods without meditation",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 12,
        "category": "sigils",
        "excerpt": "Charging a sigil needs gnosis — an altered state — not necessarily meditation. These 7 methods reach that state through the body and the senses instead of stillness.",
        "cta_apps": [["chaos-sigil-generator", "Chaos Sigil Generator"]],
        "related": [
            ["austin-osman-spare-sigil-method", "Austin Osman Spare Sigilization: The Original Method..."],
            ["austin-osman-spare-sigil-method", "Austin Osman Spare Sigilization: The Original Method..."],
            ["complete-magickal-servitors-guide", "Complete Magickal Servitors Guide: Create, Activate &..."],
            ["chaos-magick-beginners-complete-guide", "Chaos Magick for Beginners: Complete Guide (2026)"],
        ],
        "references": [
            "Spare, A. O. — The Book of Pleasure (1913).",
            "Carroll, P. J. — Liber Null & Psychonaut.",
            "Hine, P. — Condensed Chaos: An Introduction to Chaos Magic.",
        ],
        "howto": [
            {"name": "Prepare the sigil", "text": "Draw or generate your sigil and stare at it until its image is fixed in your mind."},
            {"name": "Reach gnosis", "text": "Use one of the seven methods below to enter an altered, one-pointed state."},
            {"name": "Release the sigil", "text": "At the peak of the state, let the sigil's image fire from your mind and immediately forget it."},
            {"name": "Dismiss and detach", "text": "Close the working, ground yourself, and do not dwell on the sigil or the outcome."},
        ],
        "toc": [
            ["what-gnosis-is", "What 'Charging' Actually Means"],
            ["method-1-box-breathing", "Method 1: Box Breathing"],
            ["method-2-exertion", "Method 2: Physical Exertion"],
            ["method-3-emotional-spike", "Method 3: Emotional Spike"],
            ["method-4-dancing", "Method 4: Dancing & Rhythmic Music"],
            ["method-5-sensory-overload", "Method 5: Sensory Overload"],
            ["method-6-laughter", "Method 6: Laughter"],
            ["method-7-orgasmic", "Method 7: The Orgasmic State"],
            ["common-mistakes", "Common Mistakes"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "what-gnosis-is", "text": "What 'Charging' Actually Means"},
            {"t": "p", "text": "In chaos magic, a sigil is charged by firing it into the unconscious at the peak of gnosis — a one-pointed, altered state where the analytical mind goes quiet. The classic instruction says to meditate, but meditation is only ONE route to gnosis. Gnosis is a state, not a technique. Any activity that floods your attention and silences the inner editor will do the job."},
            {"t": "p", "text": "There are two families of gnosis: inhibitory (stillness, breath, trance) and excitatory (movement, pain, pleasure, overwhelm). If sitting still does not work for you, you are an excitatory person — and the next seven methods are yours."},
            {"t": "h2", "id": "method-1-box-breathing", "text": "Method 1: Box Breathing"},
            {"t": "p", "text": "Inhale for four counts, hold for four, exhale for four, hold for four. Repeat for two to three minutes. The rhythm becomes hypnotic and the counting crowds out thought. At the third or fourth minute, hold the sigil in mind and release it on an exhale."},
            {"t": "p", "text": "Box breathing is the gentlest excitatory-adjacent method — it borders on inhibitory gnosis but keeps the body engaged, which makes it ideal for beginners and for people who get bored in silent meditation."},
            {"t": "h2", "id": "method-2-exertion", "text": "Method 2: Physical Exertion"},
            {"t": "p", "text": "Run, sprint, do burpees, lift, or climb stairs until you hit the wall — the point where your body is screaming and your mind goes quiet. That exhausted, tunnel-vision state is gnosis. Fire the sigil at the moment of maximum effort."},
            {"t": "p", "text": "The burn-out method works because physical exhaustion is a proven trance inducer: the body hijacks all attention and the verbal mind has nothing left to say."},
            {"t": "h2", "id": "method-3-emotional-spike", "text": "Method 3: Emotional Spike"},
            {"t": "p", "text": "Trigger a strong emotion — rage, grief, excitement, awe — and ride it to its peak, then fire the sigil into the feeling. A vivid memory, a charged song, or a scene that reliably moves you will do. The emotional spike must be genuine; manufactured feeling produces a weak charge."},
            {"t": "p", "text": "This is the fastest method but the hardest to fake. It is also why many practitioners keep a 'trigger playlist' — music that reliably floods them in under a minute."},
            {"t": "h2", "id": "method-4-dancing", "text": "Method 4: Dancing & Rhythmic Music"},
            {"t": "p", "text": "Put on a driving track and dance — not choreographed, just moving — until you lose track of time and your internal monologue shuts off. Repetitive rhythm is the oldest trance technology in the book. When the music owns you, that is the moment."},
            {"t": "p", "text": "The dervish method. Drumming, techno, tribal rhythms, anything with a relentless beat. Twenty minutes of uninhibited movement beats an hour of frustrated stillness."},
            {"t": "h2", "id": "method-5-sensory-overload", "text": "Method 5: Sensory Overload"},
            {"t": "p", "text": "Flood one or more senses until conscious processing gives up. Examples: a freezing cold shower, alternating hot and cold water, intense strobing light with loud sound, a spinning chair until dizzy, or pressing on a trigger point until it aches."},
            {"t": "p", "text": "Overload works because the brain cannot verbalize a firehose. At the peak of the overwhelm, the sigil fires cleanly. Keep sessions short — seconds to a minute — and never push past safety."},
            {"t": "h2", "id": "method-6-laughter", "text": "Method 6: Laughter"},
            {"t": "p", "text": "Laughing until you cry produces the same one-pointed collapse as any strong emotion — the mind empties, the body shakes, and the inner editor is offline. Watch something genuinely funny, get a friend to make you crack, or work yourself up to the point where laughing becomes uncontrollable."},
            {"t": "p", "text": "Controlled laughter is a documented trance state, and it is the most pleasant gnosis on this list. Fire the sigil at the peak of the laughing fit."},
            {"t": "h2", "id": "method-7-orgasmic", "text": "Method 7: The Orgasmic State"},
            {"t": "p", "text": "The orgasmic state is the strongest natural gnosis available — total attention collapse, total body engagement. Traditional practice: hold the sigil in mind or on a screen, and fire it at the moment of climax. This is the method Austin Osman Spare wrote around in The Book of Pleasure."},
            {"t": "p", "text": "It is also the method people feel most awkward about. Use it privately, plan ahead, and keep the sigil where you can actually see it at the critical moment — a phone screen propped nearby works perfectly."},
            {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
            {"t": "ul", "items": [
                "Watching the sigil after firing it. The point is to forget — obsessive checking is the #1 sigil killer.",
                "Firing the sigil too early, while the analytical mind is still running.",
                "Charging more than one sigil in a session. Split attention means split charge.",
                "Skipping the grounding afterward. A charged sigil leaves you buzzing; food, water, and movement settle you.",
                "Recharging the same sigil repeatedly. If it does not work, re-examine the statement, not the charge.",
            ]},
            {"t": "p", "text": "The sigil itself matters less than the charge, but a clean, unambiguous symbol helps. A <a href=\"../apps/chaos-sigil-generator.html\">sigil generator</a> removes the design bottleneck so the working is pure charge — statement in, sigil out, ready to fire."},
        ],
        "faq": [
            ["Does a sigil need meditation to charge?", "No. Meditation is one route to the gnosis state, but box breathing, exertion, emotional spikes, and the other methods above reach the same state faster for most people."],
            ["How long does a sigil take to manifest?", "From days to weeks, and sometimes longer — it depends on the statement, not the charge method. A clear, time-bound statement manifests faster than a vague one."],
            ["What if I accidentally remember the sigil?", "Re-firing from memory is usually harmless once it is charged. The danger is obsessing over the outcome — that is what actually blocks manifestation."],
        ],
    },
    {
        "slug": "rune-spreads-for-beginners",
        "title": "Rune Spreads for Beginners: 5 Simple Layouts That Actually Work (2026)",
        "index_title": "Rune Spreads for Beginners: 5 Simple Layouts",
        "desc": "Five easy Elder Futhark rune spreads for beginners: the single daily draw, past-present-future, the Norns, the Rune Cross, and the nine-rune cast — with.",
        "keywords": "rune spreads for beginners, elder futhark spreads, how to cast runes, rune reading layouts, norse rune spreads, simple rune spreads",
        "og_alt": "Five beginner rune spread layouts",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 13,
        "category": "runes",
        "excerpt": "Rune spreads don't need to be complicated. These 5 layouts — from a single daily draw to the nine-rune cast — give beginners clear positions and obvious meanings.",
        "cta_apps": [["norse-rune-oracle", "Norse Rune Oracle"]],
        "related": [
            ["norse-runes-beginners-guide", "Norse Runes Guide: Elder Futhark Divination for Beginners"],
            ["hunter-runes-vs-elder-futhark-comparison", "Chaos Hunter Runes vs Elder Futhark: A Complete Comparison of Runic Systems"],
            ["norse-rune-oracle-app-review", "Norse Rune Oracle App Review: Best Viking Rune Reader..."],
            ["divination-methods-beyond-tarot-guide", "10 Divination Methods Beyond Tarot: From Tea Leaves to Bone Casting (2026)"],
        ],
        "references": [
            "Paxson, D. — Taking Up the Runes: A Complete Guide to Using Runes in Spells, Rituals, Divination, and Magic.",
            "Thorsson, E. — Futhark: A Handbook of Rune Magic.",
            "Flowers, S. E. — Rune Might: Secret Practices of the German Rune Magicians.",
        ],
        "howto": [
            {"name": "Choose a spread", "text": "Pick one of the five layouts below based on the question you want answered."},
            {"name": "Prepare your runes", "text": "Hold the runes, state your question silently, and focus on it while you shuffle or cast."},
            {"name": "Draw or cast", "text": "Draw runes one at a time for structured spreads, or cast them freely for the nine-rune method."},
            {"name": "Read each position", "text": "Interpret each rune by its position in the spread, then combine them into a story."},
            {"name": "Log the reading", "text": "Write down the spread and your interpretation; revisiting readings teaches you more than repeating them."},
        ],
        "toc": [
            ["before-you-start", "Before You Start"],
            ["spread-1-single-draw", "Spread 1: The Single Daily Draw"],
            ["spread-2-past-present-future", "Spread 2: Past, Present, Future"],
            ["spread-3-norns", "Spread 3: The Norns"],
            ["spread-4-rune-cross", "Spread 4: The Five-Rune Rune Cross"],
            ["spread-5-nine-cast", "Spread 5: The Nine-Rune Cast"],
            ["reading-tips", "Reading Tips for Beginners"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "before-you-start", "text": "Before You Start"},
            {"t": "p", "text": "Rune spreads are position-based readings: each position in the layout asks the rune a different question. The power is in the positions, not the layout's complexity. Beginners consistently do better with five simple spreads mastered deeply than with a dozen complex ones half-learned."},
            {"t": "p", "text": "Use the Elder Futhark — the 24-rune alphabet that is the default for modern divination. Shuffle, concentrate on your question, and either draw runes one at a time or cast them onto a flat surface. The same ritual works for every spread below."},
            {"t": "h2", "id": "spread-1-single-draw", "text": "Spread 1: The Single Daily Draw"},
            {"t": "p", "text": "The single draw is the beginner's bread and butter: one rune, drawn each morning, read as the theme of the day. Draw it, note whether it is upright or reversed, and carry the answer with you. It takes ten seconds and builds a habit of daily contact with the runes."},
            {"t": "p", "text": "Interpretation is simple: the rune's core meaning applied to the day ahead. Fehu at the start of a workday says 'opportunity and income'; Thurisaz says 'conflict or protection — watch your boundaries.'"},
            {"t": "h2", "id": "spread-2-past-present-future", "text": "Spread 2: Past, Present, Future"},
            {"t": "p", "text": "Draw three runes left to right. Position one is the past — the root of the situation. Position two is the present — the current force. Position three is the trajectory — where things are heading if nothing changes."},
            {"t": "p", "text": "This is the first spread that tells a story, and it is the one to master before moving on. Read the middle rune as the pivot: it is the only position you can act on directly."},
            {"t": "h2", "id": "spread-3-norns", "text": "Spread 3: The Norns"},
            {"t": "p", "text": "The Norns — Urd, Verdandi, Skuld — are the three Norse figures of fate: what was, what is becoming, and what must be. The spread is a three-rune arc with a twist: it reads destiny rather than timeline, making it better for 'why is this happening?' questions than 'what happens next?'"},
            {"t": "ul", "items": [
                "First rune (Urd): the cause — what was set in motion.",
                "Second rune (Verdandi): the becoming — what is actively unfolding.",
                "Third rune (Skuld): the necessity — what must be acknowledged.",
            ]},
            {"t": "h2", "id": "spread-4-rune-cross", "text": "Spread 4: The Five-Rune Rune Cross"},
            {"t": "p", "text": "The Rune Cross is the runic answer to the Celtic cross, compacted to five positions. It is the workhorse spread for real questions: situations, relationships, and decisions."},
            {"t": "ul", "items": [
                "Center: the heart of the matter — the core issue.",
                "Left: the hidden influence — what is not being said.",
                "Right: the visible influence — what is on the surface.",
                "Top: the goal or best outcome.",
                "Bottom: the foundation — what supports or blocks everything.",
            ]},
            {"t": "h2", "id": "spread-5-nine-cast", "text": "Spread 5: The Nine-Rune Cast"},
            {"t": "p", "text": "The nine-rune cast is the traditional Norse method: cast all runes onto a cloth and read the ones that land face-up, nearest to the center first. Nine is the number of the worlds in Norse cosmology, which is why nine runes define the reading."},
            {"t": "p", "text": "Read the pattern, not the positions: runes clustered at the center are immediate and pressing; runes at the edges are distant or fading. A rune that lands pointing toward the center pulls the reading inward; one pointing away pushes outward. Reversed meanings apply for upside-down runes."},
            {"t": "h2", "id": "reading-tips", "text": "Reading Tips for Beginners"},
            {"t": "ul", "items": [
                "Read the question, not the runes. Let the position's question drive the interpretation.",
                "Combine meanings into a sentence before you reach for a book — synthesis beats lookup.",
                "Note the spread in a journal. Patterns emerge over weeks that no single reading reveals.",
                "Trust the first rune that jumps at you. Second-guessing is where beginners lose the signal.",
                "Respect reversed runes. A reversed Fehu is loss or debt — context decides, not fear.",
            ]},
            {"t": "p", "text": "A <a href=\"../apps/norse-rune-oracle.html\">digital rune oracle</a> handles the mechanical part — shuffle, cast, and store your readings — so you can spend your energy on interpretation, which is the skill that actually grows."},
        ],
        "faq": [
            ["What is the best rune spread for a total beginner?", "The single daily draw. It builds the habit, teaches the meanings one at a time, and gives immediate feedback on how your readings feel."],
            ["Do rune positions have to be read in a specific order?", "Yes — read them in the order the spread defines. Position is half the meaning; skipping the order scrambles the story."],
            ["Can I use a rune app instead of physical runes?", "Yes. The divination works the same; the app just removes the shuffling and bookkeeping. Many beginners start digital, then buy physical runes once the habit is set."],
        ],
    },
    {
        "slug": "moon-phase-calculator-for-spells",
        "title": "Moon Phase Calculator for Spells: Cast on the Right Night (2026)",
        "index_title": "Moon Phase Calculator for Spells: Cast on the Right Night",
        "desc": "Which moon phase for which spell? A practical moon-phase-to-spell table: new moon for beginnings, waxing for growth, full moon for charging, waning for.",
        "keywords": "moon phase calculator for spells, what moon phase for spells, moon phase spell timing, best moon phase for money spell, waxing moon spells, waning moon banishing",
        "og_alt": "Moon phase to spell type matching table",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 11,
        "category": "lunar-magic",
        "excerpt": "New moon for beginnings, waxing for growth, full moon for charging, waning for release. This moon phase calculator guide maps every phase to the spells that actually belong to it.",
        "cta_apps": [["lunar-phase-calculator", "Lunar Phase Calculator"]],
        "related": [
            ["moon-phases-spell-timing-guide", "Moon Phases & Spell Timing: Complete Magical Calendar Guide"],
            ["candle-magic-beginners-guide", "Candle Magic for Beginners"],
            ["moon-phases-spell-timing-guide", "Moon Phases & Spell Timing: Complete Magical Calendar Guide"],
            ["lunar-phase-calculator-app-review", "Lunar Phase Calculator App Review"],
        ],
        "references": [
            "Cunningham, S. — Wicca: A Guide for the Solitary Practitioner.",
            "Kynes, S. — Lunar Magic: A Guide to Working with the Moon's Phases.",
            "US Naval Observatory — Moon phase and illumination data.",
        ],
        "howto": [
            {"name": "Check the phase", "text": "Look up the current moon phase and its exact timing for your time zone."},
            {"name": "Match phase to intent", "text": "Use the phase table to pick the type of spell that aligns with the moon's energy."},
            {"name": "Time the working", "text": "Perform the spell within the phase window — ideally in the first half of the phase for growing work."},
            {"name": "Close and release", "text": "Finish the working, release the intention, and stop thinking about the outcome."},
        ],
        "toc": [
            ["why-phases-matter", "Why Phases Matter"],
            ["the-five-phases", "The Five Working Phases"],
            ["phase-spell-table", "Phase-to-Spell Table"],
            ["timing-within-phase", "Timing Within a Phase"],
            ["void-of-course", "The Void of Course Warning"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "why-phases-matter", "text": "Why Phases Matter"},
            {"t": "p", "text": "The moon is the oldest timing system in magic, and the reason is practical: its light literally waxes and wanes, giving every working a natural growth or release curve. Spells are not stronger or weaker by phase — they are better MATCHED. A banishing cast on a waxing moon fights the current; the same banishing on a waning moon rides it."},
            {"t": "p", "text": "This guide maps each phase to the spell families that belong to it, with the precise timing windows so you can plan a working days in advance."},
            {"t": "h2", "id": "the-five-phases", "text": "The Five Working Phases"},
            {"t": "ul", "items": [
                "New Moon — the seed: beginnings, plans, fresh starts.",
                "Waxing Moon — the grow: attraction, increase, building energy.",
                "Full Moon — the peak: charging, empowerment, climax of work.",
                "Waning Moon — the release: banishing, cleansing, letting go.",
                "Dark Moon — the rest: reflection, divination, deep work.",
            ]},
            {"t": "h2", "id": "phase-spell-table", "text": "Phase-to-Spell Table"},
            {"t": "table", "headers": ["Phase", "Energy", "Best Spell Work"],
             "rows": [
                ["New Moon", "Beginnings", "Setting intentions, new projects, job applications, fresh starts"],
                ["Waxing Crescent", "Growth", "Attraction, money increase, new love, opportunities"],
                ["First Quarter", "Action", "Overcoming obstacles, decisive moves, courage work"],
                ["Waxing Gibbous", "Refinement", "Detail work, strengthening ongoing projects, healing"],
                ["Full Moon", "Peak power", "Charging talismans, empowering sigils, climax rituals, gratitude"],
                ["Waning Gibbous", "Release", "Cutting cords, breaking habits, emotional release"],
                ["Last Quarter", "Cleansing", "Banishing, cleansing spaces, debt removal, endings"],
                ["Dark Moon", "Rest", "Divination, shadow work, meditation, planning"],
             ]},
            {"t": "p", "text": "The practical takeaway: money and love growth spells belong to the waxing half; cord-cutting and cleansing belong to the waning half; talisman charging belongs to the full moon window; and big personal decisions love the new moon."},
            {"t": "h2", "id": "timing-within-phase", "text": "Timing Within a Phase"},
            {"t": "p", "text": "Within each phase, the first half carries the phase's energy most strongly. A waxing money spell works best between the new moon and the first quarter; a waning banishing works best between the full moon and the last quarter."},
            {"t": "p", "text": "Moon sign also refines the timing: for example, a money spell in the waxing moon under Taurus or Capricorn is a classic pairing. If you are just starting, the phase alone is enough — sign work is the refinement layer, not the foundation."},
            {"t": "h2", "id": "void-of-course", "text": "The Void of Course Warning"},
            {"t": "p", "text": "The one timing rule every practitioner should respect: the void of course period — the gap between the moon's last major aspect in a sign and its entry into the next sign. During a void moon, traditional practice says workings 'fizzle': they produce nothing, delay, or go sideways."},
            {"t": "p", "text": "Standard advice: avoid starting new magic during a void period. Use it for rest, planning, or divination instead. Void periods are short — a few hours — so checking the schedule before you cast is cheap insurance."},
            {"t": "p", "text": "You do not need to memorize ephemeris tables. A <a href=\"../apps/lunar-phase-calculator.html\">lunar phase calculator</a> gives you the phase, the exact timing, and the void of course windows for your time zone — so the only thing you have to bring to the working is your intention."},
        ],
        "faq": [
            ["Can I cast spells on any moon phase?", "You can, but matching the phase to the intent dramatically improves results. A growth spell on a waning moon is swimming upstream."],
            ["What moon phase is best for a money spell?", "The waxing moon — ideally between the new moon and the first quarter. Adding a Taurus or Capricorn moon refines it further."],
            ["How do I know when the moon is void of course?", "Check a lunar phase app or ephemeris for your time zone. The void period is short, but casting inside it is the classic 'nothing happened' mistake."],
        ],
    },
]
