# -*- coding: utf-8 -*-
"""Article 18: new-moon-ritual-manifestation -> lunar-phase-calculator."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "new-moon-ritual-manifestation",
    "title": "New Moon Ritual for Manifestation: Step-by-Step Guide (2026)",
    "index_title": "New Moon Manifestation Ritual: Step-by-Step",
    "desc": "A practical new moon ritual for manifestation: what to do during the 48-hour window, what to write, and when to let go so the cycle can work.",
    "keywords": "new moon ritual, new moon manifestation, new moon ritual for manifestation, new moon spell",
    "og_alt": "A crescent new moon over a candlelit altar with a journal and pen",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "moon",
    "excerpt": "The new moon is the reset button of the lunar cycle. Here is the exact ritual structure to plant an intention and get out of your own way.",
    "cta_apps": [["lunar-phase-calculator", "Lunar Phase Calculator"]],
    "related": [
        ["new-moon-vs-full-moon-ritual-guide", RT["new-moon-vs-full-moon-ritual-guide"]],
        ["moon-phases-spell-timing-guide", RT["moon-phases-spell-timing-guide"]],
        ["moon-phase-calculator-for-spells", RT["moon-phase-calculator-for-spells"]],
        ["lunar-phase-calculator-app-review", RT["lunar-phase-calculator-app-review"]],
    ],
    "references": [
        "Cunningham, Scott. Wicca: A Guide for the Solitary Practitioner (1988).",
        "Kynes, Sandra. Lunar Magic: Unlock Your Inner Power with the Energy of the Moon (2018).",
        "U.S. Naval Observatory Astronomical Applications. Moon Phase Data (2026).",
    ],
    "howto": [
        {"name": "Pin down the exact new moon time", "text": "Find the precise moment the moon conjoins the sun using a lunar calculator; the ritual window is the 48 hours after that point."},
        {"name": "Prepare your altar or space", "text": "Clean the surface, light one white candle, and set out your journal and pen. Keep it minimal; the intention is the centerpiece."},
        {"name": "Write the intention in present tense", "text": "Phrase it as if it already happened, one clear sentence, concrete and measurable, signed with your name."},
        {"name": "Charge and release", "text": "Read it aloud three times, hold the page to your chest for one minute, then close the journal and do not reopen it until the full moon."},
        {"name": "Take one physical action", "text": "Within the same cycle, do one concrete step toward the intention so the ritual has a hand in the world, not just in the journal."},
    ],
    "toc": [
        ["why-new-moon", "Why the New Moon Works"],
        ["the-window", "The 48-Hour Window"],
        ["ritual-structure", "Ritual Structure"],
        ["what-to-write", "What to Write"],
        ["what-to-skip", "What to Skip"],
        ["new-moon-vs-full", "New Moon vs Full Moon"],
        ["digital-tools", "Digital Tools for Timing"],
        ["common-mistakes", "Common Mistakes"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "The new moon is the only moment in the lunar month when the sky is effectively dark. From a magical standpoint that darkness is not emptiness; it is raw potential. The seed has not sprouted, the page has not been written, the blank has not been filled. That is exactly why manifestation work starts here rather than at the full moon, when the energy is already mid-expression."},
        {"t": "h2", "id": "why-new-moon", "text": "Why the New Moon Works"},
        {"t": "p", "text": "Every lunar cycle is a complete arc: new moon sets the intention, waxing moon builds momentum, full moon peaks, waning moon releases, dark moon rests. Start an intention at the wrong point in the arc and you are pushing against the current. Start it at the new moon and the entire following cycle pushes with you."},
        {"t": "ul", "items": [
            "The new moon favors beginnings, projects, jobs, relationships, and habits.",
            "The waxing moon that follows amplifies growth and attraction work.",
            "The full moon is for charging and celebration, not for planting.",
            "The waning moon is for banishing, cutting cords, and clearing what blocks the seed.",
        ]},
        {"t": "h2", "id": "the-window", "text": "The 48-Hour Window"},
        {"t": "p", "text": "The most effective new moon work happens in the 48 hours after the exact conjunction. The exact minute matters less than being inside the window. If you miss it, the second and third nights after the new moon still carry enough of the phase to be useful; the energy tapers, it does not vanish."},
        {"t": "h2", "id": "ritual-structure", "text": "Ritual Structure"},
        {"t": "ol", "items": [
            "Ground yourself: a few slow breaths, feet on the floor, attention on the body.",
            "Light the candle and state the phase: 'This is the new moon. I set a new intention.'",
            "Write the intention in present tense, one sentence, concrete and signed.",
            "Read it aloud three times, once for the mind, once for the heart, once for the hands.",
            "Hold the page to your chest for one minute and then close the journal.",
            "Extinguish the candle and do not revisit the page until the full moon.",
        ]},
        {"t": "h2", "id": "what-to-write", "text": "What to Write"},
        {"t": "p", "text": "Vague intentions produce vague results. 'I want more money' gives the universe nothing to aim at. 'I earn an extra $300 from my side work this month' gives it a target. Write the concrete version, in present tense, with a timeframe, and then stop editing it. The journal entry is a seed, not a thesis."},
        {"t": "h2", "id": "what-to-skip", "text": "What to Skip"},
        {"t": "ul", "items": [
            "Banishing and cord-cutting: those belong to the waning moon, not the new moon.",
            "Listing twenty intentions: one clear intention outperforms a page of wishes.",
            "Re-reading the intention every day: obsessive checking starves the seed.",
            "Negative phrasing: 'I stop being broke' focuses on the lack; 'I earn from my work' focuses on the flow.",
        ]},
        {"t": "h2", "id": "new-moon-vs-full", "text": "New Moon vs Full Moon"},
        {"t": "p", "text": "The new moon plants; the full moon harvests. If you have been doing all your manifestation work at the full moon, you are trying to harvest what you never planted. Pair the two: set at the new moon, review and charge at the full moon. For the full comparison, see our guide on <a href=\"../blog/new-moon-vs-full-moon-ritual-guide.html\">new moon vs full moon rituals</a>."},
        {"t": "h2", "id": "digital-tools", "text": "Digital Tools for Timing"},
        {"t": "p", "text": "Precision matters less than being inside the window, but a <a href=\"../apps/lunar-phase-calculator.html\">Lunar Phase Calculator</a> removes the guesswork: exact conjunction time, phase for any date, and the next new moon countdown. Keep it on the altar for two minutes, then put the phone away. The tool serves the ritual; it does not replace it."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Using the new moon for banishing work (wrong phase).",
            "Writing intentions with 'not' or 'stop' phrasing.",
            "Checking the journal daily and re-reading the intention.",
            "Skipping the physical action step and expecting magic alone to move money.",
            "Missing the window by a week and calling it a new moon ritual anyway.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Can I do the ritual after the exact new moon time?"},
        {"t": "p", "text": "Yes. The 48-hour window after the conjunction is the strongest, and the days up to the first quarter still carry new-moon energy. After that, wait for the next cycle."},
        {"t": "h3", "text": "Should I burn the paper or keep it?"},
        {"t": "p", "text": "Either works. Keeping it in a closed journal preserves a record of the cycle; burning it is a clean release. What does not work is keeping it in your wallet and re-reading it daily."},
        {"t": "h3", "text": "What if I cannot do the ritual at night?"},
        {"t": "p", "text": "The moon is present during the day too, just not visible. The phase timing is astronomical, not visual. Morning of the day after the new moon is perfectly valid."},
    ],
    "faq": [
        ["Can I do the ritual after the exact new moon time?", "Yes. The 48-hour window after the conjunction is the strongest, and the days up to the first quarter still carry new-moon energy."],
        ["Should I burn the paper or keep it?", "Either works. Keeping it in a closed journal preserves a record; burning it is a clean release. Re-reading it daily is the mistake."],
        ["What if I cannot do the ritual at night?", "Phase timing is astronomical, not visual. The morning after the new moon is perfectly valid."],
    ],
}
