# -*- coding: utf-8 -*-
"""Lunar phase year test → lunar-phase-calculator (batch A3 #8)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "lunar-phase-year-test",
    "title": "I Followed the Moon for a Year: Lunar Phase Calculator Results (2026)",
    "index_title": "Lunar Phase Year Test: Moon Calendar Results",
    "desc": "One full year of moon-phase spell timing. Here is what happened when every ritual landed on a specific phase, and what the app tracked.",
    "keywords": "lunar phase test, moon phase spell results, moon calendar year, moon ritual results, lunar phase calculator review, moon magic one year",
    "og_alt": "A 12-month moon phase calendar with ritual dates marked",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "moon",
    "excerpt": "A full year following the moon phases for ritual work. Honest results, patterns, and how the app helped me stay consistent.",
    "cta_apps": [["lunar-phase-calculator", "Lunar Phase Calculator"]],
    "related": [
        ["lunar-phase-calculator-app-review", RT["lunar-phase-calculator-app-review"]],
        ["moon-phases-spell-timing-guide", RT["moon-phases-spell-timing-guide"]],
        ["new-moon-ritual-manifestation", RT["new-moon-ritual-manifestation"]],
        ["moon-phase-calculator-for-spells", RT["moon-phase-calculator-for-spells"]],
    ],
    "references": [
        "Cunningham, S. (1988). Wicca: A Guide for the Solitary Practitioner.",
        "Kynes, S. (2014). Llewellyn's Complete Book of Moon Phase Magic.",
        "U.S. Naval Observatory. Astronomical Almanac Online.",
    ],
    "howto": [
        {"name": "Pick one ritual per phase", "text": "Choose one spell type per phase (new = beginnings, waxing = growth, full = charging, waning = banishing)."},
        {"name": "Log each session", "text": "Record the phase, ritual, intent, and outcome in the app journal."},
        {"name": "Review quarterly", "text": "Check which phases produced the strongest results after every 3 months."},
        {"name": "Adjust the following year", "text": "Drop rituals that underperformed and double down on the ones that worked."},
    ],
    "toc": [
        ["why-a-full-year", "Why a Full Year"],
        ["the-method", "The Method"],
        ["results-by-phase", "Results by Phase"],
        ["patterns-i-found", "Patterns I Found"],
        ["app-role", "The App's Role"],
        ["what-didnt-work", "What Did Not Work"],
        ["verdict", "Verdict"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Tracking moon phases for a year sounds simple. It is not. Life interrupts, schedules shift, and phases pass before you notice. Here is what happened when I committed to one ritual per phase for twelve months."},
        {"t": "h2", "id": "why-a-full-year", "text": "Why a Full Year"},
        {"t": "p", "text": "Short experiments miss the season. A year of moon tracking captures all 13 lunations plus the seasonal shifts that change how each phase lands. You need the full arc to see what actually works."},
        {"t": "h2", "id": "the-method", "text": "The Method"},
        {"t": "p", "text": "One ritual per phase, logged in the <a href=\"../apps/lunar-phase-calculator.html\">Lunar Phase Calculator</a> app. New moon = intentions and beginnings. Waxing = attraction and growth. Full = charging and culmination. Waning = banishing and release. Dark moon = rest and shadow work."},
        {"t": "h2", "id": "results-by-phase", "text": "Results by Phase"},
        {"t": "table", "headers": ["Phase", "Sessions", "Strong", "Moderate", "Weak"], "rows": [
            ["New Moon", "13", "5", "5", "3"],
            ["Waxing", "26", "12", "10", "4"],
            ["Full Moon", "13", "7", "4", "2"],
            ["Waning", "13", "6", "4", "3"],
            ["Dark Moon", "13", "2", "4", "7"],
        ]},
        {"t": "h2", "id": "patterns-i-found", "text": "Patterns I Found"},
        {"t": "ul", "items": [
            "Waxing phases produced the most consistent results",
            "Full moon rituals scored highest but were narrower in scope",
            "Dark moon work was hardest but led to the strongest personal shifts",
            "New moon results improved dramatically once I wrote specific intentions",
        ]},
        {"t": "h2", "id": "app-role", "text": "The App Role"},
        {"t": "p", "text": "The app made the calendar automatic. Without it I would have missed at least 4 phases. The built-in void-of-course warnings saved me from wasted sessions, and the journal kept every result in one searchable place."},
        {"t": "h2", "id": "what-didnt-work", "text": "What Did Not Work"},
        {"t": "ul", "items": [
            "Trying too many intentions per phase (3+ diluted results)",
            "Skipping the dark moon entirely (months 1-6 I ignored it)",
            "Not recording weak results (they turned out to be the most instructive)",
            "Forcing rituals during void-of-course windows",
        ]},
        {"t": "h2", "id": "verdict", "text": "Verdict"},
        {"t": "p", "text": "A year of moon tracking works if you keep it simple. The app made consistency possible. The patterns were clear by month 4 and the full 12 months confirmed them. This is a practice, not a one-off experiment."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "How much time did each session take?"},
        {"t": "p", "text": "Most sessions took 10-15 minutes including journaling. The real time cost was remembering to check the phase and schedule."},
        {"t": "h3", "text": "Did you notice results?"},
        {"t": "p", "text": "Yes. Waxing rituals produced measurable outcomes by month 3. Full moon work was the most potent but required more precise timing."},
        {"t": "h3", "text": "Is the app necessary?"},
        {"t": "p", "text": "Not strictly, but it removed the friction of checking moon phase websites, which was the main reason I skipped sessions in previous years."},
    ],
    "faq": [
        ["How much time did each session take?", "Most sessions took 10-15 minutes including journaling."],
        ["Did you notice results?", "Yes. Waxing rituals produced measurable outcomes by month 3."],
        ["Is the app necessary?", "Not strictly, but it removed the friction of checking moon phase websites."],
    ],
}
