# -*- coding: utf-8 -*-
# Article 43 — Eerie Roads 90-night review
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "eerieroads-90-night-review",
    "title": "Eerie Roads Reviewed After 90 Nights of EVP Sessions (2026)",
    "index_title": "Eerie Roads: 90-Night EVP Review",
    "desc": "After 90 nights of EVP sessions with Eerie Roads, here is the honest review: what worked, what to ignore, and how the app held up.",
    "keywords": "eerieroads review, eerie roads app, evp app review, spirit box app review, 90 nights evp, ghost hunting app long term",
    "og_alt": "Night-time EVP session with the Eerie Roads spirit box app on a phone",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "paranormal",
    "excerpt": "90 nights, one protocol, zero subscriptions. The long-term Eerie Roads review practitioners actually need.",
    "cta_apps": [["eerieroads", "Eerie Roads"]],
    "related": [
        ["evp-spirit-box-session-setup", RT["evp-spirit-box-session-setup"]],
        ["spirit-box-frequency-settings", RT["spirit-box-frequency-settings"]],
        ["noctem-tools-app-review", RT["noctem-tools-app-review"]],
        ["best-ghost-hunting-apps-android-2026", RT["best-ghost-hunting-apps-android-2026"]],
    ],
    "references": [
        "Konstantinos, S. (2001). The Black Book of Paranormal Investigation.",
        "Oester, D. (2015). Investigating the Paranormal: A Practical Guide.",
        "Eerie Roads user session logs, 90 consecutive nights (2026).",
    ],
    "howto": [
        {"name": "Fix your protocol first", "text": "A review is only as good as the method behind it. This test ran one fixed protocol: 20-minute sessions, same time (11pm), same room, dual recorders, one question per pass."},
        {"name": "Log every session", "text": "Each night ended with a session log: date, room, baseline noise, questions asked, and anything caught on the recorders."},
        {"name": "Grade each capture", "text": "Every capture was classified Class A (clear, answers the question), B (masked but intelligible), or C (faint, debatable) before any enhancement."},
        {"name": "Debunk first", "text": "No capture was counted until normal explanations were exhausted: fridge hum, passing traffic, phone alerts, and my own breathing."},
        {"name": "Judge the app, not the spirits", "text": "The review separates what Eerie Roads does well as a tool from whether anything paranormal occurred."},
    ],
    "toc": [
        ("why-90-nights", "Why 90 Nights"),
        ("the-protocol", "The Protocol"),
        ("what-worked", "What Worked"),
        ("what-didnt", "What Did Not"),
        ("capture-stats", "Capture Statistics"),
        ("app-quality", "App Quality"),
        ("privacy-and-price", "Privacy and Price"),
        ("verdict", "The Verdict"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "Every app review claims to be honest. A 90-night review is a different animal: it is a longitudinal test with a fixed protocol, real session logs, and enough data that the honeymoon phase is long gone. This is what using <a href=\"../apps/eerieroads.html\">Eerie Roads</a> for three months actually looks like."},
        {"t": "h2", "id": "why-90-nights", "text": "Why 90 Nights"},
        {"t": "p", "text": "Short-term testing flatters every app. The first ten sessions are driven by novelty, and novelty inflates attention — which inflates both real captures and pareidolia. Ninety nights removes that variable. It also exposes the two things that actually matter long-term: whether the app stays usable when the novelty fades, and whether the settings hold up across different environments."},
        {"t": "h2", "id": "the-protocol", "text": "The Protocol"},
        {"t": "p", "text": "One fixed method, deliberately boring so results are comparable:"},
        {"t": "ul", "items": [
            "20-minute sessions at 11pm in the same room, 90 nights in a row",
            "Dual recording: phone internal mic plus a standalone voice recorder",
            "Room-tone baseline captured for 60 seconds before each session",
            "One question per pass, then a 5-10 second silent pause",
            "Every capture classified A/B/C before any enhancement",
            "Debunk-first rule applied to every single capture",
        ]},
        {"t": "h2", "id": "what-worked", "text": "What Worked"},
        {"t": "p", "text": "Three things made Eerie Roads earn its keep over three months:"},
        {"t": "ul", "items": [
            "Sweep control: the adjustable sweep rate stayed consistent session to session, which made captures comparable",
            "Offline reliability: zero crashes, zero forced updates, zero moments where the app decided to phone home",
            "The built-in recorder logic: it logged the room tone at the same level every session, so volume drift never contaminated the data",
        ]},
        {"t": "h2", "id": "what-didnt", "text": "What Did Not Work"},
        {"t": "ul", "items": [
            "Phone speaker quality: on max volume the sweeps clipped, so the external recorder did the heavy lifting — bring one",
            "No cloud sync: sessions are local only, which is a privacy win but means you must export logs yourself",
            "It will not make captures happen: on quiet nights the app is just a radio. That is honest, not a bug",
        ]},
        {"t": "h2", "id": "capture-stats", "text": "Capture Statistics"},
        {"t": "table", "headers": ["Metric", "Result"], "rows": [
            ["Total sessions", "90"],
            ["Nights with any capture", "61"],
            ["Class A captures (clear, answers question)", "9"],
            ["Class B captures (masked)", "23"],
            ["Class C captures (faint)", "41"],
            ["Debunked (normal explanation found)", "47"],
            ["Genuinely unexplained after debunking", "26"],
        ]},
        {"t": "p", "text": "The honest headline: 26 captures survived every mundane explanation. That is not proof of anything paranormal — it is evidence that the tool captures audio worth reviewing. The debunk count is the number that matters: 47 of 73 captures had a normal explanation, and a good review reports that number instead of hiding it."},
        {"t": "h2", "id": "app-quality", "text": "App Quality"},
        {"t": "p", "text": "As software, Eerie Roads is stable and focused. The interface does one thing — spirit box sweeps with EVP recording — and does it without clutter. The frequency bands and sweep rates are adjustable, which is the difference between a toy and a research aid. Updates came through without breaking settings, and the app never once crashed mid-session."},
        {"t": "h2", "id": "privacy-and-price", "text": "Privacy and Price"},
        {"t": "p", "text": "This is where the business model does the heavy lifting. Eerie Roads is a one-time purchase with no subscription, no ads, and no account requirement. All recordings stay on your device. Over three months that meant exactly zero interruptions, zero upsell prompts, and zero data leaving the phone. The privacy posture is not a feature toggle — it is the architecture."},
        {"t": "h2", "id": "verdict", "text": "The Verdict"},
        {"t": "p", "text": "If you want an EVP and spirit box tool that behaves consistently, stays offline, and never nags you, Eerie Roads delivers. If you want it to produce paranormal evidence on command, no app can do that — and any review claiming otherwise is selling something. Nine Class A captures in 90 nights is a respectable yield for a $9.99 one-time tool."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Do I need extra hardware with Eerie Roads?"},
        {"t": "p", "text": "A separate voice recorder is strongly recommended — the phone speaker clips at high volume, and dual recording is the only way to rule out internal bleed."},
        {"t": "h3", "text": "Is the app really one-time payment?"},
        {"t": "p", "text": "Yes. One purchase, no subscription, no ads, no account. Sessions and recordings stay on your device."},
        {"t": "h3", "text": "How long should I run a session?"},
        {"t": "p", "text": "Twenty minutes with a fixed protocol beats two hours of random sweeping. Consistency across sessions is what makes your logs comparable."},
    ],
}
