# -*- coding: utf-8 -*-
"""Chaos Sigil design-charge-forget guide -> chaos-sigil-generator (batch A2 #10)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "chaos-sigil-design-charge-forget-guide",
    "title": "Design, Charge, Forget: The Complete Chaos Sigil Workflow (2026)",
    "index_title": "Design, Charge, Forget: Chaos Sigil Workflow",
    "desc": "The three-step chaos sigil workflow explained: how to design a sigil, charge it, and let it go. Use the Chaos Sigil Generator app at every stage.",
    "keywords": "chaos sigil workflow, how to make a sigil, charge a sigil, sigil design, chaos magick sigil, sigil generator app",
    "og_alt": "The three stages of a chaos sigil: design, charge, and forget",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "sigils",
    "excerpt": "Design, charge, forget. The three-stage chaos sigil method made simple, with the Chaos Sigil Generator app at every step.",
    "cta_apps": [["chaos-sigil-generator", "Chaos Sigil Generator"]],
    "related": [
        ["chaos-sigil-generator-app-review", RT["chaos-sigil-generator-app-review"]],
        ["how-to-charge-sigil-without-meditation", RT["how-to-charge-sigil-without-meditation"]],
        ["sigil-maker-ultimate-guide", RT["sigil-maker-ultimate-guide"]],
        ["how-long-sigil-takes-to-work", RT["how-long-sigil-takes-to-work"]],
    ],
    "references": [
        "Spare, A.O. (1913). The Book of Pleasure.",
        "Carroll, P. (1978). Liber Null & Psychonaut.",
        "Hine, P. (1995). Condensed Chaos.",
    ],
    "howto": [
        {"name": "Write the intention", "text": "Phrase a clear, present-tense desire in one sentence."},
        {"name": "Strip the letters", "text": "Remove duplicate letters and vowels to leave a compressed string."},
        {"name": "Merge into a glyph", "text": "Combine the remaining letters into a single flowing design."},
        {"name": "Charge it", "text": "Push energy into the sigil during gnosis, then release it."},
        {"name": "Forget it", "text": "Set it down and stop dwelling on the outcome."},
    ],
    "toc": [
        ["the-three-stages", "The Three Stages"],
        ["stage-one-design", "Stage 1: Design"],
        ["stage-two-charge", "Stage 2: Charge"],
        ["stage-three-forget", "Stage 3: Forget"],
        ["common-mistakes", "Common Mistakes"],
        ["digital-workflow", "The Digital Workflow"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Chaos sigil magic rests on one elegant loop: design, charge, forget. The <a href=\"../apps/chaos-sigil-generator.html\">Chaos Sigil Generator</a> app supports all three stages on your phone, offline, with no subscription."},
        {"t": "h2", "id": "the-three-stages", "text": "The Three Stages"},
        {"t": "ul", "items": [
            "Design: turn a desire into a glyph",
            "Charge: push energy in and let go",
            "Forget: stop thinking about it",
        ]},
        {"t": "h2", "id": "stage-one-design", "text": "Stage 1: Design"},
        {"t": "p", "text": "Start with a present-tense intention like 'I earn $500 this month from my side work.' Strip duplicate letters and vowels, then merge the remaining letters into one glyph. The app automates this compression, so you can focus on the meaning, not the busywork."},
        {"t": "h2", "id": "stage-two-charge", "text": "Stage 2: Charge"},
        {"t": "p", "text": "Charging means pushing focused energy into the sigil during an altered state, then releasing it. You do not need meditation. Box breathing, physical exertion, emotional spikes, or rhythmic music all work. See the <a href=\"../blog/how-to-charge-sigil-without-meditation.html\">no-meditation charging guide</a>."},
        {"t": "h2", "id": "stage-three-forget", "text": "Stage 3: Forget"},
        {"t": "p", "text": "Forgetting is the hard part. Once charged, the sigil works best when you stop dwelling on it. Archive it, do not check it nightly, and let the subconscious get on with it. Re-reading a sigil every day is the fastest way to keep it from firing."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Vague intentions that cannot be measured",
            "Skipping the charge and expecting the design to fire",
            "Forgetting to forget",
            "Re-firing the same glyph instead of a fresh one",
            "Skipping any action that moves you toward the goal",
        ]},
        {"t": "h2", "id": "digital-workflow", "text": "The Digital Workflow"},
        {"t": "p", "text": "The Chaos Sigil Generator handles the design stage, stores your archived sigils locally, and keeps no account or cloud sync. One-time purchase, offline, with no ads or subscription."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Do I have to draw sigils by hand?"},
        {"t": "p", "text": "No. Digital sigils work the same way. The app handles the letter-stripping and glyph merging for you."},
        {"t": "h3", "text": "How long until it works?"},
        {"t": "p", "text": "Timing varies from days to months depending on the goal. See the <a href=\"../blog/how-long-sigil-takes-to-work.html\">sigil timeline guide</a>."},
        {"t": "h3", "text": "Is it really a one-time payment?"},
        {"t": "p", "text": "Yes. Pay once, no subscription, no ads, offline forever."},
    ],
    "faq": [
        ["Do I have to draw sigils by hand?", "No. Digital sigils work the same way; the app handles compression for you."],
        ["How long until it works?", "Timing varies from days to months; see the sigil timeline guide."],
        ["Is it really a one-time payment?", "Yes, one-time with no subscription, ads, or account."],
    ],
}
