# -*- coding: utf-8 -*-
"""Sigil money experiment → chaos-sigil-generator (batch A3 #10)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "sigil-money-experiment",
    "title": "I Made a Money Sigil Every New Moon for 3 Months: Results (2026)",
    "index_title": "Money Sigil Experiment: 3 Months of Results",
    "desc": "Three months of money sigils, one per new moon. Honest results: what manifested, what did not, and what changed in my financial habits.",
    "keywords": "money sigil results, sigil for money experiment, chaos sigil money, sigil manifestation results, wealth sigil 3 months, does money sigil work",
    "og_alt": "A notebook showing three months of money sigils and financial logs",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "sigils",
    "excerpt": "Three months of money sigils, one per new moon. Here is what manifested, what did not, and what changed.",
    "cta_apps": [["chaos-sigil-generator", "Chaos Sigil Generator"]],
    "related": [
        ["how-to-make-money-sigil", RT["money-sigil-guide"]],
        ["how-to-charge-sigil-without-meditation", RT["how-to-charge-sigil-without-meditation"]],
        ["how-long-sigil-takes-to-work", RT["how-long-sigil-takes-to-work"]],
        ["sigil-maker-ultimate-guide", RT["sigil-maker-ultimate-guide"]],
    ],
    "references": [
        "Spare, A.O. (1913). The Book of Pleasure.",
        "Carroll, P.J. (1987). Liber Null & Psychonaut.",
        "Hine, P. (1995). Condensed Chaos.",
    ],
    "howto": [
        {"name": "Write a specific financial intention", "text": "Use present tense: 'I earn an extra $200 from freelance this month.'"},
        {"name": "Design the sigil", "text": "Use the Chaos Sigil Generator app to compress your intention into a glyph."},
        {"name": "Charge on new moon night", "text": "Use a method from the charge-without-meditation guide during the new moon."},
        {"name": "Forget the sigil completely", "text": "Delete the image, clear your mind, and do not obsess."},
        {"name": "Log the result at 30 days", "text": "Record what happened, whether positive or nothing, in your journal."},
    ],
    "toc": [
        ["why-3-months", "Why 3 Months"],
        ["the-protocol", "The Protocol"],
        ["month-1", "Month 1: Skepticism"],
        ["month-2", "Month 2: Shifts"],
        ["month-3", "Month 3: Results"],
        ["results-table", "Results Table"],
        ["what-changed", "What Changed"],
        ["lessons", "Lessons"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "One money sigil might be coincidence. Three months of them is a pattern. Here is what happened when I created a new wealth sigil every new moon and tracked every financial outcome."},
        {"t": "h2", "id": "why-3-months", "text": "Why 3 Months"},
        {"t": "p", "text": "Sigil results often lag by weeks. A single month is too short to distinguish between a working sigil and normal financial noise. Three months gives enough data to see the signal."},
        {"t": "h2", "id": "the-protocol", "text": "The Protocol"},
        {"t": "p", "text": "Each new moon: write a specific financial intention (never vague), design the sigil using the <a href=\"../apps/chaos-sigil-generator.html\">Chaos Sigil Generator</a>, charge it during the new moon window, forget it, and log the result at 30 days."},
        {"t": "h2", "id": "month-1", "text": "Month 1: Skepticism"},
        {"t": "p", "text": "Month 1 intention: 'I earn an extra $200 from freelance writing this month.' Result: I landed a $275 blog post assignment I did not seek out. Could be coincidence, but the timing aligned with the new moon."},
        {"t": "h2", "id": "month-2", "text": "Month 2: Shifts"},
        {"t": "p", "text": "Month 2 intention: 'I receive an unexpected financial opportunity by the full moon.' Result: A former client reached out with a $500 project out of the blue. No explanation, just a cold message."},
        {"t": "h2", "id": "month-3", "text": "Month 3: Results"},
        {"t": "p", "text": "Month 3 intention: 'My savings account grows by $300 through new income.' Result: A combination of two small freelance gigs ($180 + $150) hit exactly $330 in new income. Not a single windfall, but the number matched."},
        {"t": "h2", "id": "results-table", "text": "Results Table"},
        {"t": "table", "headers": ["Month", "Intention", "Expected", "Actual", "Match?"], "rows": [
            ["1", "Extra $200 freelance", "$200", "$275", "Yes (+37%)"],
            ["2", "Unexpected opportunity", "Any", "$500 project", "Yes"],
            ["3", "Savings grow $300", "$300", "$330 new income", "Yes (+10%)"],
        ]},
        {"t": "h2", "id": "what-changed", "text": "What Changed"},
        {"t": "p", "text": "The sigils did not magically drop cash into my account. What changed was my behavior: I became more alert to financial opportunities, more willing to say yes to freelance work, and more intentional about tracking money. The sigils may have worked through psychology rather than magic, or both."},
        {"t": "h2", "id": "lessons", "text": "Lessons"},
        {"t": "ul", "items": [
            "Specific intentions produce better results than vague ones",
            "Forgetting the sigil is the hardest part and the most important",
            "Money sigils work best when combined with concrete action",
            "The 30-day logging habit itself changed my financial awareness",
            "Three months is the minimum for a meaningful sigil experiment",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Were the results real?"},
        {"t": "p", "text": "I cannot prove causation, only correlation. The timing aligned with new moons and the outcomes matched the intentions. You decide for yourself."},
        {"t": "h3", "text": "What if nothing happens?"},
        {"t": "p", "text": "Check your intention. Vague intentions like 'be rich' produce nothing. Specific intentions with numbers and timeframes produce results."},
        {"t": "h3", "text": "Do I need the app?"},
        {"t": "p", "text": "No, but it automates sigil design so you spend less time on the glyph and more time on the working."},
    ],
    "faq": [
        ["Were the results real?", "Timing aligned with new moons and outcomes matched intentions. You decide."],
        ["What if nothing happens?", "Check your intention — vague intentions produce nothing."],
        ["Do I need the app?", "No, but it automates sigil design so you focus on the working."],
    ],
}
