# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "one-time-vs-subscription-calculator-occult",
    "title": "One-Time vs Subscription: The 3-Year Cost Calculator for Occult Apps (2026)",
    "index_title": "One-Time vs Subscription Cost Calculator",
    "desc": "Run the 3-year math on occult apps: what a $9.99 monthly subscription really costs versus a one-time purchase, with a fill-in-the-blank calculator.",
    "keywords": "one time payment vs subscription, occult app cost comparison, subscription calculator apps, one time purchase app, occult apps price comparison",
    "og_alt": "A cost comparison chart showing one-time app purchases versus monthly subscription totals over three years",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "apps",
    "excerpt": "Run the 3-year math on occult apps: what a $9.99 monthly subscription really costs versus a one-time purchase, with a fill-in-the-blank calculator.",
    "cta_apps": [
        ["dream-machine", "Dream Machine"],
        ["psi-gym", "PSI GYM"],
        ["unofficial-rider-waite-tarot", "Unofficial Rider Waite Tarot"],
        ["norse-rune-oracle", "Norse Rune Oracle"],
        ["chaos-sigil-generator", "Chaos Sigil Generator"],
        ["iching-oracle", "I Ching Oracle"],
        ["lunar-phase-calculator", "Lunar Phase Calculator"],
        ["astral-lab", "Astral Lab"],
        ["arcana-goetia", "Arcana Goetia"],
        ["eerieroads", "Eerie Roads"],
        ["noctem-tools", "NOCTEM"],
    ],
    "related": [
        ["why-stop-paying-subscription-occult-apps", RT["why-stop-paying-subscription-occult-apps"]],
        ["best-tarot-apps-android-2026", RT["best-tarot-apps-android-2026"]],
        ["true-cost-tarot-app-subscription-vs-onetime", RT["true-cost-tarot-app-subscription-vs-onetime"]],
        ["best-lucid-dreaming-apps-android-2026", RT["best-lucid-dreaming-apps-android-2026"]],
    ],
    "references": [
        "Stumbrys, T. et al. (2012). Induction of lucid dreams: A systematic review of evidence. Consciousness and Cognition, 21(4).",
        "LaBerge, S. (1985). Lucid Dreaming: The Power of Being Awake and Aware in Your Dreams. Jeremy P. Tarcher.",
        "Cha0smagick Labs (2026). Pricing policy: fixed one-time payment, no subscriptions, no ads.",
    ],
    "howto": [
        {"name": "List your subscriptions", "text": "Write down every occult or divination app you pay for monthly or yearly, with the exact price."},
        {"name": "Total the annual cost", "text": "Multiply each monthly price by 12, add any yearly plans, and sum the total per year."},
        {"name": "Project to 3 years", "text": "Multiply the annual total by 3. That is what the subscription costs you over the life of a typical app usage cycle."},
        {"name": "Find the one-time alternative", "text": "Check whether a one-time-payment app covers the same core features and note its single price."},
        {"name": "Decide with the horizon", "text": "If you expect to use the app for more than 6 months, the one-time purchase wins on every realistic horizon."},
    ],
    "toc": [
        ("why-this-calculator", "Why This Calculator"),
        ("the-formula", "The 3-Year Formula"),
        ("worked-examples", "Worked Examples"),
        ("app-by-app-table", "App-by-App Cost Table"),
        ("subscriptions-that-earn-their-keep", "Subscriptions That Earn Their Keep"),
        ("hidden-costs", "Hidden Costs Nobody Quotes"),
        ("run-your-own-numbers", "Run Your Own Numbers"),
        ("faq", "Frequently Asked Questions"),
    ],
    "sections": [
        {"t": "p", "text": "Most occult apps moved to subscriptions because recurring revenue is predictable for developers — not because it is better for you. Before you pay $9.99 a month for a tarot deck, run the same three-year math a car dealer uses on you. This guide gives you the formula, worked examples, and a fill-in-the-blank calculator you can run for any app."},
        {"t": "h2", "id": "why-this-calculator", "text": "Why This Calculator"},
        {"t": "p", "text": "A $4.99 monthly subscription looks harmless: about the price of a coffee. The problem is the horizon. Occult practice is a long-term habit — people journal for years, not months. When a purchase decision is framed as 'pay $4.99 now', the brain compares it to a coffee. When it is framed as the $179.64 it costs over three years, the comparison changes."},
        {"t": "p", "text": "The one-time-payment model inverts the incentive. A developer who charges once needs the app to stay good to keep your goodwill and your future purchases. A subscription developer needs you to keep paying even when the app stops improving. The calculator below makes that difference concrete."},
        {"t": "h2", "id": "the-formula", "text": "The 3-Year Formula"},
        {"t": "ol", "items": [
            "Monthly subscription: price × 12 = annual cost; annual × 3 = 3-year cost.",
            "Yearly subscription: price × 3 = 3-year cost (add 0 if you cancel early — but most people don't).",
            "One-time purchase: price once = 3-year cost (and every year after is free).",
            "Include the 'free tier': if the free tier is gated, count the unlock price as part of the subscription path.",
        ]},
        {"t": "p", "text": "The rule of thumb: if the subscription's 3-year cost exceeds the one-time price by more than 3×, the one-time purchase is cheaper within the first year alone."},
        {"t": "h2", "id": "worked-examples", "text": "Worked Examples"},
        {"t": "p", "text": "Three common scenarios from the occult app market:"},
        {"t": "ul", "items": [
            "A tarot app at $9.99/month: $119.88 in year 1, $359.64 over 3 years. An equivalent one-time deck app costs $9.99 once.",
            "A lucid dreaming app at $4.99/month: $59.88 in year 1, $179.64 over 3 years. One-time alternatives cost $3.99.",
            "A ghost hunting suite at $14.99/month: $179.88 in year 1, $539.64 over 3 years. A one-time suite costs $14.99.",
        ]},
        {"t": "h2", "id": "app-by-app-table", "text": "App-by-App Cost Table"},
        {"t": "table", "headers": ["Category", "Typical subscription", "3-year subscription cost", "One-time alternative", "One-time price"],
         "rows": [
             ["Tarot", "$9.99/mo", "$359.64", "Unofficial Rider Waite Tarot", "$9.99"],
             ["Lucid dreaming", "$4.99/mo", "$179.64", "Dream Machine or Lucid Dream", "$3.99"],
             ["ESP training", "$6.99/mo", "$251.64", "PSI GYM", "$3.99"],
             ["Rune divination", "$5.99/mo", "$215.64", "Norse Rune Oracle", "$3.99"],
             ["Sigil crafting", "$8.99/mo", "$323.64", "Chaos Sigil Generator", "$3.99"],
             ["I Ching", "$4.99/mo", "$179.64", "I Ching Oracle", "$3.99"],
             ["Moon tracking", "$3.99/mo", "$143.64", "Lunar Phase Calculator", "$3.99"],
             ["Astral work", "$6.99/mo", "$251.64", "Astral Lab", "$3.99"],
             ["Goetia", "$9.99/mo", "$359.64", "Arcana Goetia", "$3.99"],
             ["Ghost hunting", "$14.99/mo", "$539.64", "Eerie Roads", "$9.99"],
             ["Paranormal suite", "$14.99/mo", "$539.64", "NOCTEM", "$14.99"],
         ]},
        {"t": "h2", "id": "subscriptions-that-earn-their-keep", "text": "Subscriptions That Earn Their Keep"},
        {"t": "p", "text": "Some subscriptions genuinely earn their cost: cloud sync you actually use, a huge continuously-updated database, or team features. Before you pay, ask: is the recurring feature something I touch every week? If the answer is 'the journal I could keep locally', the subscription is charging you for convenience, not capability."},
        {"t": "h2", "id": "hidden-costs", "text": "Hidden Costs Nobody Quotes"},
        {"t": "ul", "items": [
            "Price creep: intro rates expire and prices rise silently each year.",
            "Feature gating: the free tier shrinks, pushing you to the paid plan you already pay for.",
            "Data lock-in: if you stop paying, can you still read your journal or your reading history?",
            "Attention cost: ads and upsell prompts inside paid tiers are the product.",
        ]},
        {"t": "h2", "id": "run-your-own-numbers", "text": "Run Your Own Numbers"},
        {"t": "p", "text": "Grab your phone, open your subscriptions page, and fill this in for each occult app you pay for:"},
        {"t": "ol", "items": [
            "Name of the app and its monthly or yearly price.",
            "Annual cost = monthly price × 12 (or the yearly price directly).",
            "3-year cost = annual cost × 3.",
            "Now search for the one-time alternative that covers your core feature and write its price.",
            "Compare: if 3-year subscription cost > one-time price, switch. If you would cancel in under 6 months, staying is fine.",
        ]},
        {"t": "p", "text": "If you want to keep your journal and your reading history instead of renting them, every app in the table above — from <a href=\"../apps/dream-machine.html\">Dream Machine</a> and <a href=\"../apps/psi-gym.html\">PSI GYM</a> to <a href=\"../apps/unofficial-rider-waite-tarot.html\">Unofficial Rider Waite Tarot</a>, <a href=\"../apps/norse-rune-oracle.html\">Norse Rune Oracle</a>, <a href=\"../apps/chaos-sigil-generator.html\">Chaos Sigil Generator</a>, <a href=\"../apps/iching-oracle.html\">I Ching Oracle</a>, <a href=\"../apps/lunar-phase-calculator.html\">Lunar Phase Calculator</a>, <a href=\"../apps/astral-lab.html\">Astral Lab</a>, <a href=\"../apps/arcana-goetia.html\">Arcana Goetia</a>, <a href=\"../apps/eerieroads.html\">Eerie Roads</a> and <a href=\"../apps/noctem-tools.html\">NOCTEM</a> — is a fixed one-time payment with no subscription, no ads, and no account."},
        {"t": "h2", "id": "faq", "text": "Frequently Asked Questions"},
        {"t": "h3", "text": "Is a one-time purchase really one-time?"},
        {"t": "p", "text": "Yes for every Cha0smagick app: you pay the listed price once and own the app permanently. There are no tiers, no unlocks, no recurring fees."},
        {"t": "h3", "text": "What if I only want the app for a month?"},
        {"t": "p", "text": "Then a one-month subscription wins. But for any practice you expect to continue — journaling, reading, rituals — the breakeven is usually within the first two months."},
        {"t": "h3", "text": "Do one-time apps get updates?"},
        {"t": "p", "text": "Yes. Updates are funded by new sales, not by locking existing users. The incentive is to keep the app excellent so the next buyer exists."},
    ],
    "faq": [
        ["What does the 3-year calculator tell me?", "It converts a monthly price into the total you will actually pay, which is the number that should drive your decision."],
        ["Which is better, subscription or one-time?", "For long-term practice, one-time. For a one-off weekend project, subscription. Everything in this guide assumes practice that lasts."],
        ["Are all Cha0smagick apps one-time purchases?", "Yes — every app in the table is a fixed one-time payment with no subscription, no ads, and no account."],
    ],
}
