# -*- coding: utf-8 -*-
"""
articles_b.py — Structured data for articles 6-10 (data-driven, no hardcoded HTML).

Each article is a dict consumed by build_10_articles.py. The `sections` list
uses typed entries: {t: "p"|"h2"|"h3"|"ul"|"ol"|"table", ...}.
"""

ARTICLES_B = [
    {
        "slug": "how-to-cast-iching-digitally",
        "title": "How to Cast the I Ching Digitally: Coin Method Explained (2026)",
        "index_title": "How to Cast the I Ching Digitally: Coin Method Explained",
        "desc": "The I Ching coin method, step by step: 3 coins, 6 tosses, 64 hexagrams, and changing lines. And why casting the I Ching digitally uses the exact same.",
        "keywords": "cast i ching online, how to cast the i ching, i ching coin method, i ching for beginners, digital i ching oracle, i ching changing lines explained",
        "og_alt": "I Ching coin casting method explained",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 12,
        "category": "iching",
        "excerpt": "Three coins, six tosses, one hexagram. The I Ching coin method explained step by step — including changing lines and why digital casting uses the same randomness math.",
        "cta_apps": [["iching-oracle", "I Ching Oracle"]],
        "related": [
            ["divination-methods-beyond-tarot-guide", "10 Divination Methods Beyond Tarot: From Tea Leaves to Bone Casting (2026)"],
            ["divination-methods-beyond-tarot-guide", "10 Divination Methods Beyond Tarot: From Tea Leaves to Bone Casting (2026)"],
            ["rune-spreads-for-beginners", "Rune Spreads for Beginners"],
            ["divination-methods-beyond-tarot-guide", "10 Divination Methods Beyond Tarot: From Tea Leaves to Bone Casting (2026)"],
        ],
        "references": [
            "Wilhelm, R. & Baynes, C. — The I Ching or Book of Changes (Princeton University Press).",
            "Legge, J. — The I Ching: The Book of Changes (Sacred Books of the East, Vol. XVI).",
            "Shaughnessy, E. — Unearthing the Changes: Recently Discovered Manuscripts of the Yi Jing.",
        ],
        "howto": [
            {"name": "Form your question", "text": "State a clear, specific question about your situation before any coins move."},
            {"name": "Toss three coins", "text": "Toss three coins together and record heads and tails for the first line."},
            {"name": "Build the hexagram", "text": "Repeat the toss six times, building the hexagram from the bottom line up."},
            {"name": "Convert to lines", "text": "Convert each toss to a broken or solid line, noting any changing lines."},
            {"name": "Consult the text", "text": "Read the judgment for the primary hexagram, plus the changing hexagram if lines changed."},
        ],
        "toc": [
            ["what-is-the-iching", "What the I Ching Is"],
            ["the-coin-method", "The Coin Method, Step by Step"],
            ["reading-lines", "Reading the Lines"],
            ["changing-lines", "Changing Lines & the Transformational Hexagram"],
            ["digital-casting", "Why Digital Casting Is Legitimate"],
            ["common-questions", "Common Questions"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "what-is-the-iching", "text": "What the I Ching Is"},
            {"t": "p", "text": "The I Ching — the Book of Changes — is one of the oldest divination systems in continuous use, with roots in China over 3,000 years old. It works through 64 hexagrams: six-line figures made of solid (yang) and broken (yin) lines. Each hexagram carries a judgment and images that describe the dynamics of your situation."},
            {"t": "p", "text": "You do not choose a hexagram; you generate one through a random process — traditionally yarrow stalks, later coins — and the result is read as a snapshot of the situation's energy and its likely trajectory."},
            {"t": "h2", "id": "the-coin-method", "text": "The Coin Method, Step by Step"},
            {"t": "p", "text": "The coin method is the modern standard because it needs only three coins and takes minutes. Each toss produces one line; six tosses build one hexagram. The system:"},
            {"t": "ol", "items": [
                "Assign values: heads = 3, tails = 2.",
                "Toss three coins and add the values. Possible totals: 6, 7, 8, or 9.",
                "Convert the total to a line: 6 = changing yin (broken, moving), 7 = yang (solid, stable), 8 = yin (broken, stable), 9 = changing yang (solid, moving).",
                "Write the first line at the BOTTOM of your hexagram, then toss again for line two above it.",
                "Repeat until you have six lines, bottom to top.",
            ]},
            {"t": "p", "text": "The hexagram is read from the bottom up — line one is the root of the situation, line six the outcome. This ordering is non-negotiable; a hexagram read upside down is a different answer entirely."},
            {"t": "h2", "id": "reading-lines", "text": "Reading the Lines"},
            {"t": "p", "text": "Each line position has a traditional meaning: line one is the beginning, line two the self in action, line three the point of risk, line four the approach to the leader, line five the ruler, and line six the completion or excess. The text gives each line a phrase like 'a dragon in the fields' (line two of the Creative) that describes that stage."},
            {"t": "p", "text": "When reading, the hexagram's upper three lines (the outer trigram) represent the external world and the lower three (the inner trigram) represent yourself. The judgment applies to the whole situation; the line texts refine it."},
            {"t": "h2", "id": "changing-lines", "text": "Changing Lines & the Transformational Hexagram"},
            {"t": "p", "text": "Lines 6 and 9 are CHANGING lines: they are at their extreme, so they turn into their opposite. A changing line is the I Ching's way of saying 'this is where the situation is moving.' If a toss gives you a 6 or 9, note it."},
            {"t": "p", "text": "When at least one line changes, you get a SECOND hexagram — the transformation — by flipping every changing line to its opposite. The primary hexagram describes the present; the transformational hexagram describes where things are headed if the dynamics play out. When no lines change, the reading is static: the situation has no forced trajectory."},
            {"t": "h2", "id": "digital-casting", "text": "Why Digital Casting Is Legitimate"},
            {"t": "p", "text": "Some practitioners insist on physical coins or yarrow stalks, but the mechanism is randomness — and a properly seeded random generator produces the same distribution as coins: 6, 7, 8, 9 at the same probabilities (1:5:5:1 under the standard coin weights... more precisely 6 and 9 at 1/8 each, 7 and 8 at 3/8 each). A digital oracle that implements those weights reproduces the traditional math exactly."},
            {"t": "p", "text": "What digital casting removes is the friction: no coins to lose, no ambiguity in the toss, no misreading a 6 for an 8 in dim light, and automatic tracking of changing lines and the transformational hexagram. The oracle text stays the same — the tool is just faster."},
            {"t": "h2", "id": "common-questions", "text": "Common Questions"},
            {"t": "ul", "items": [
                "Ask one question per casting — the I Ching answers the question you actually hold, so clarity is everything.",
                "Do not re-cast the same question repeatedly; the first answer is the answer.",
                "Yes/no questions are poor fits; the I Ching describes dynamics, not binary verdicts.",
                "If a reading is confusing, read the judgment twice and the lines once — most confusion is speed, not text.",
            ]},
            {"t": "p", "text": "A dedicated <a href=\"../apps/iching-oracle.html\">I Ching oracle app</a> handles the mechanics — weighted randomness, line-by-line display, changing lines, and the transformation hexagram — so your attention stays on the text, which is where the actual insight lives."},
        ],
        "faq": [
            ["Is casting the I Ching online the same as with coins?", "Yes. The traditional coin method generates lines through random weights; a correctly implemented digital oracle uses identical probabilities and the same hexagram texts."],
            ["What do changing lines mean in the I Ching?", "Changing lines (6 and 9) mark where the situation is in motion. They produce a second hexagram describing the likely transformation."],
            ["Can I ask the I Ching about love or money?", "Yes — the I Ching answers any question you can phrase clearly. The quality of the reading depends on the clarity of the question, not the topic."],
        ],
    },
    {
        "slug": "evp-spirit-box-session-setup",
        "title": "EVP & Spirit Box Session Setup: A Complete Guide (2026)",
        "index_title": "EVP & Spirit Box Session Setup: A Complete Guide",
        "desc": "How to run an EVP and spirit box session: equipment, environment, recording levels, the Class A/B/C EVP system, session protocol, and how to review your audio.",
        "keywords": "how to do an evp session, spirit box session setup, evp recording for beginners, ghost box session guide, evp class a b c, spirit box technique",
        "og_alt": "EVP and spirit box session setup checklist",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 14,
        "category": "paranormal",
        "excerpt": "EVP and spirit box sessions fail for the same reason: bad setup. Here is the full protocol — equipment, environment, recording levels, Class A/B/C EVPs, and honest review — that separates real captures from noise.",
        "cta_apps": [["eerieroads", "Eerie Roads"]],
        "related": [
            ["evp-recording-complete-guide", "EVP Recording: The Complete Guide to Capturing Electronic Voice Phenomena"],
            ["evp-vs-spirit-box-comparison-guide", "EVP vs Spirit Box: Understanding Paranormal Audio Investigation Methods"],
            ["best-ghost-hunting-apps-android-2026", "5 Best Ghost Hunting Apps for Android in 2026: EVP &amp; Spirit Box Tools"],
            ["best-ghost-hunting-apps-android-2026", "5 Best Ghost Hunting Apps for Android in 2026: EVP &amp; Spirit Box Tools"],
        ],
        "references": [
            "Konstantinos — Ghost Hunting for Beginners.",
            "Butler, T. — Ghosts and How to See Them: A Practical Guide.",
            "The American Association of Electronic Voice Phenomena (AA-EVP) — EVP recording standards.",
        ],
        "howto": [
            {"name": "Prepare the environment", "text": "Choose a quiet location, kill background noise sources, and check the room's EMF baseline."},
            {"name": "Set recording levels", "text": "Record 30 seconds of room tone and set levels so the meter peaks around -12 dB on normal speech."},
            {"name": "Run the session protocol", "text": "Introduce yourself, ask one question at a time, and leave 5-10 second pauses after each."},
            {"name": "Log everything", "text": "Note timestamps, questions, and any physical phenomena during the session."},
            {"name": "Review honestly", "text": "Listen repeatedly, compare against the room tone, and classify any capture using the Class A/B/C system."},
        ],
        "toc": [
            ["what-evp-is", "What EVP Actually Is"],
            ["class-system", "The Class A/B/C System"],
            ["equipment", "Equipment You Actually Need"],
            ["environment", "Environment & Setup"],
            ["recording-levels", "Recording Levels"],
            ["session-protocol", "The Session Protocol"],
            ["review", "Reviewing & Classifying Your Audio"],
            ["avoiding-false-positives", "Avoiding False Positives"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "what-evp-is", "text": "What EVP Actually Is"},
            {"t": "p", "text": "Electronic Voice Phenomena — EVP — are voices or voice-like sounds captured on recording media that were not heard at the time of recording. A spirit box (or ghost box) is the live version: a device that rapidly sweeps radio frequencies while you record, in the hope of catching fragments of communication in the noise."},
            {"t": "p", "text": "Both methods share one requirement: a clean, documented setup. Without it, every capture is indistinguishable from interference — and reviewers (and investigators) will rightly assume it is."},
            {"t": "h2", "id": "class-system", "text": "The Class A/B/C System"},
            {"t": "table", "headers": ["Class", "Clarity", "Examples"],
             "rows": [
                ["Class A", "Clear, intelligible without enhancement", "A single word or short phrase heard plainly"],
                ["Class B", "Audible but requires repeated listening", "Whisper, partial word, or masked phrase"],
                ["Class C", "Faint, distorted, or fragmentary", "A syllable, a mumble, or sound like speech"],
             ]},
            {"t": "p", "text": "Use the system the way researchers do: Class C is interesting, Class B is promising, Class A is the only one worth showing anyone. Most captures never leave Class C — and that is normal, not a failure of the session."},
            {"t": "h2", "id": "equipment", "text": "Equipment You Actually Need"},
            {"t": "ul", "items": [
                "A digital recorder or a phone with a voice memo app — the recording baseline.",
                "A spirit box app or device if you are running live sweeps.",
                "Wired earbuds with a mic, or a separate lapel mic — internal mics pick up handling noise.",
                "A notebook or recording app for the session log.",
                "Optional but useful: a second recorder running simultaneously for cross-referencing.",
            ]},
            {"t": "p", "text": "You do not need a $400 paranormal kit. The expensive gear filters noise slightly; it does not make captures real. A clean digital recorder and a disciplined protocol outperform fancy hardware every time."},
            {"t": "h2", "id": "environment", "text": "Environment & Setup"},
            {"t": "ul", "items": [
                "Choose the quietest room or outdoor spot you can — traffic, HVAC, and refrigerators are capture-killers.",
                "Unplug or mute anything that hums: fridges, fans, clocks, phone chargers.",
                "Do a 30-second room-tone recording BEFORE the session; this becomes your comparison baseline.",
                "Check for strong EMF sources (wires, breakers, electronics) — radio-frequency interference can mimic EVP.",
                "Tell people you are recording; unexpected voices from bystanders are the #1 false positive.",
            ]},
            {"t": "h2", "id": "recording-levels", "text": "Recording Levels"},
            {"t": "p", "text": "Set your levels with the room tone, not your voice: record 30 seconds of ambient sound and adjust so normal conversation peaks around -12 dB. If you set levels by your own voice, the room tone will be too quiet and you will amplify everything during review — hiss, hum, and clipping — while any genuine capture stays buried."},
            {"t": "p", "text": "Keep the recorder in a fixed position once the session starts. Moving it mid-session scrambles the acoustic baseline and ruins your comparison material."},
            {"t": "h2", "id": "session-protocol", "text": "The Session Protocol"},
            {"t": "ol", "items": [
                "State your name, the date, time, and location aloud — this timestamps the audio itself.",
                "Introduce yourself and explain the recording; politeness is protocol, not superstition.",
                "Ask ONE question at a time, then stay silent for 5-10 seconds. The pause is where captures happen.",
                "Keep questions simple and binary-leaning: 'Are you here?' beats 'What is your name and origin?'",
                "End with a thank-you and a clear closing statement, then stop the recorder.",
            ]},
            {"t": "p", "text": "The pause after each question is the entire trick. Reviewers listen in those gaps — if you chatter over them, you have no captures, only noise."},
            {"t": "h2", "id": "review", "text": "Reviewing & Classifying Your Audio"},
            {"t": "ul", "items": [
                "Listen to the room-tone recording first, twice. You must know what the baseline sounds like.",
                "Listen to the session at least three times: once straight through, once with headphones, once slowed to 0.75x.",
                "Mark anything that sounds speech-like with its timestamp and the question it follows.",
                "Compare each candidate against the room tone — if the 'voice' matches a hum or hiss pattern, it is not EVP.",
                "Classify the survivors with the A/B/C system and keep the log with the audio file.",
            ]},
            {"t": "h2", "id": "avoiding-false-positives", "text": "Avoiding False Positives"},
            {"t": "ul", "items": [
                "Pareidolia is real: the brain fabricates speech from noise. This is why the room-tone baseline is mandatory.",
                "Radio sweeps pick up actual radio snippets — a spirit box saying 'weather today' is often just the weather.",
                "Two recorders cross-confirm: if one device captured it and the other did not, treat it as interference.",
                "Never enhance audio until after you have classified the raw file. Enhancement creates patterns that did not exist.",
            ]},
            {"t": "p", "text": "The difference between a hobbyist and an investigator is the log. A <a href=\"../apps/eerieroads.html\">paranormal suite app</a> like Eerie Roads keeps the session structure — timestamps, questions, and capture notes in one place — so your evidence file is actually evidence."},
        ],
        "faq": [
            ["What is the difference between EVP and a spirit box?", "EVP is recorded after the fact — the voice is found in review. A spirit box sweeps radio frequencies live and attempts real-time communication. Both use the same environment and review discipline."],
            ["What does Class A EVP mean?", "Class A is a clear, intelligible capture that needs no enhancement — the only class worth presenting as potential evidence."],
            ["How long should an EVP session last?", "15-30 minutes is the sweet spot. Fatigue degrades attention, and every minute after the first 30 adds noise faster than it adds signal."],
        ],
    },
    {
        "slug": "astral-projection-for-beginners",
        "title": "Astral Projection for Beginners: Step-by-Step Guide (2026)",
        "index_title": "Astral Projection for Beginners: Step-by-Step Guide",
        "desc": "Astral projection for beginners: the step-by-step method — hypnagogic state, sleep paralysis gateway, rope, roll-out and rising exit techniques, reality.",
        "keywords": "astral projection for beginners, how to astral project step by step, astral projection techniques, out of body experience for beginners, astral projection exit techniques",
        "og_alt": "Astral projection beginner steps",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 14,
        "category": "astral",
        "excerpt": "New to astral projection? Here is the full beginner path: reach the hypnagogic state, ride the sleep paralysis gateway, and exit with the rope, roll-out, or rising method — then ground safely.",
        "cta_apps": [["astral-lab", "Astral Lab"]],
        "related": [
            ["astral-projection-beginners-30-day-program", "Astral Projection for Beginners: A 30-Day Step-by-Step Training Program (2026)"],
            ["best-lucid-dreaming-apps-android-2026", "Best Lucid Dreaming Apps for Android (2026): Tested &amp; Compared"],
            ["binaural-beats-lucid-dreaming-guide", "Binaural Beats for Lucid Dreaming: Complete Frequency Guide"],
            ["reality-check-techniques-best-lucidity-methods", "Reality Check Techniques: Best Methods for Increasing Lucidity Rate (2026)"],
        ],
        "references": [
            "Monroe, R. — Journeys Out of the Body (1971).",
            "Buhlman, W. — Adventures Beyond the Body.",
            "Muldoon, S. & Carrington, H. — The Projection of the Astral Body.",
        ],
        "howto": [
            {"name": "Choose your time", "text": "The best window is early morning after 4-6 hours of sleep, or a mid-afternoon nap — times when your body is relaxed but your mind is still awake."},
            {"name": "Relax completely", "text": "Lie still and relax every muscle group, from toes to forehead, without falling asleep."},
            {"name": "Reach the hypnagogic state", "text": "Keep your mind gently focused while your body sleeps; hypnagogic imagery signals you are close."},
            {"name": "Use an exit technique", "text": "Pick the rope, roll-out, or rising method and perform it the moment you feel the gateway open."},
            {"name": "Ground yourself", "text": "Return deliberately and ground with water, food, and movement before going about your day."},
        ],
        "toc": [
            ["what-astral-projection-is", "What Astral Projection Is"],
            ["the-gateway", "The Sleep Paralysis Gateway"],
            ["hypnagogic-state", "Reaching the Hypnagogic State"],
            ["exit-techniques", "The Three Exit Techniques"],
            ["after-exit", "After the Exit: What to Do"],
            ["reality-checks", "Reality Checks & Verification"],
            ["safety-grounding", "Safety & Grounding"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "what-astral-projection-is", "text": "What Astral Projection Is"},
            {"t": "p", "text": "Astral projection — out-of-body experience, or OBE — is the sensation of your awareness separating from your physical body and moving through a projected environment. Whatever you believe about what it 'really' is, the experiential path is well documented: you relax the body, keep the mind awake, and cross a threshold where awareness operates independently."},
            {"t": "p", "text": "For beginners, the key insight is that projection is a SKILL with repeatable steps, not a gift. The steps below are the standard beginner sequence, ordered so each builds on the last."},
            {"t": "h2", "id": "the-gateway", "text": "The Sleep Paralysis Gateway"},
            {"t": "p", "text": "The most reliable doorway is sleep paralysis — the natural state where your body is asleep and immobile but your mind is awake. It happens to everyone during REM sleep; practitioners simply learn to enter it deliberately. During sleep paralysis, the physical body is offline, which is exactly what projection requires."},
            {"t": "p", "text": "If you wake up paralyzed, resist the urge to fight it. Relax into it — the paralysis is the gateway opening, and forcing movement closes it."},
            {"t": "h2", "id": "hypnagogic-state", "text": "Reaching the Hypnagogic State"},
            {"t": "p", "text": "Hypnagogia is the liminal state between waking and sleep, marked by drifting imagery, sounds, and the body feeling heavy or floating. It is the beginner's on-ramp to projection. To reach it: lie still in a comfortable position, relax completely, and keep a light mental focus — counting, visualizing, or repeating a phrase — without letting your mind drop into full sleep."},
            {"t": "p", "text": "Signals you are in the state: your body feels like it is sinking or vibrating, you see spontaneous imagery behind closed eyes, and your breathing deepens on its own. Do not move — the state is fragile."},
            {"t": "h2", "id": "exit-techniques", "text": "The Three Exit Techniques"},
            {"t": "p", "text": "When the gateway opens — sleep paralysis, vibration, or deep hypnagogia — use one of three standard exits. Pick ONE and commit to it; switching mid-attempt is the most common beginner failure."},
            {"t": "h3", "text": "1. The Rope Technique"},
            {"t": "p", "text": "Visualize a rope hanging above you. Reach up with your astral hands — not your physical ones — and hand-over-hand pull yourself up it. The motion of climbing tends to separate awareness from the body within a minute or two."},
            {"t": "h3", "text": "2. The Roll-Out Technique"},
            {"t": "p", "text": "Imagine rolling your whole awareness to one side, as if rolling off a bed. Feel the physical sensation of tipping sideways — then roll again, harder, and let the second roll carry you free of the body."},
            {"t": "h3", "text": "3. The Rising Technique"},
            {"t": "p", "text": "Float upward. Imagine you are rising out of your body like helium — through the chest, out of the crown, straight up. This is the gentlest exit and pairs well with the vibration stage."},
            {"t": "h2", "id": "after-exit", "text": "After the Exit: What to Do"},
            {"t": "ul", "items": [
                "Stabilize first: rub your projected hands together or spin slowly — this stops the exit from collapsing.",
                "Set a goal: explore your room, test a physical detail, or fly. Aimless exits end fast.",
                "Expect fog. New projectors often see a hazy environment; clarity improves with practice.",
                "If you feel yourself snapping back, re-spin or re-rub and continue.",
            ]},
            {"t": "h2", "id": "reality-checks", "text": "Reality Checks & Verification"},
            {"t": "ul", "items": [
                "Look at your hands: in projection they often appear distorted or extra-fingered.",
                "Try to push a finger through your palm — in projection it passes through.",
                "Read text twice: in projection, text usually shifts between glances.",
                "Pinch your nose and breathe — if you can still breathe, you are not in the physical body.",
            ]},
            {"t": "p", "text": "Reality checks do double duty: they verify the projection and, practiced during the day, they program lucidity for both projection and dreaming."},
            {"t": "h2", "id": "safety-grounding", "text": "Safety & Grounding"},
            {"t": "ul", "items": [
                "Projection is not dangerous, but anxiety is: if a session feels wrong, return deliberately and stop.",
                "Set an intention to return to your physical body — it works, and it calms first-timers.",
                "After returning, ground: drink water, eat something, and move your body.",
                "Keep a journal. Sessions build on each other, and notes are the difference between practice and repetition.",
            ]},
            {"t": "p", "text": "The mechanics — hypnagogic tracking, exit timing, and session logging — are where beginners lose the thread. A dedicated <a href=\"../apps/astral-lab.html\">astral projection app</a> like Astral Lab walks you through the state induction and tracks your attempts, so the technique stays consistent while your skill grows."},
        ],
        "faq": [
            ["Is astral projection dangerous?", "No documented physical danger exists, but anxiety can produce unpleasant experiences. Set clear intentions, use the grounding routine, and stop if a session feels wrong."],
            ["How long does it take to project?", "Most beginners need 2-6 weeks of regular practice. The skill is about consistency — the sleep paralysis gateway opens for people who practice the relaxation and hypnagogic steps reliably."],
            ["Is astral projection the same as lucid dreaming?", "No. Lucid dreaming happens inside a dream you control; projection is the sense of awareness operating outside the physical body. They are related but distinct skills — though each trains the same attention muscles."],
        ],
    },
    {
        "slug": "fools-journey-tarot-roadmap",
        "title": "The Fool's Journey: A Tarot Roadmap Through the Major Arcana (2026)",
        "index_title": "The Fool's Journey: A Tarot Roadmap Through the Major Arcana",
        "desc": "The Fool's Journey explained: the 22 Major Arcana as a life roadmap — from the Fool's leap to the World's completion, act by act, with the meaning of every.",
        "keywords": "fool's journey tarot explained, fool's journey major arcana, tarot roadmap for beginners, major arcana life journey, the fool tarot journey, major arcana in order",
        "og_alt": "The Fool's Journey through the Major Arcana",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 15,
        "category": "tarot",
        "excerpt": "The Fool's Journey is the Major Arcana told as one story: 22 cards, three acts, one life. Here is the complete roadmap — what each card means, and where you are on the path.",
        "cta_apps": [["unofficial-rider-waite-tarot", "Unofficial Rider Waite Tarot"]],
        "related": [
            ["tarot-card-meanings-major-arcana-complete-guide", "Complete Guide to Tarot Card Meanings: Major Arcana Explained for Beginners"],
            ["rider-waite-tarot-beginners-guide", "Rider Waite Tarot for Beginners: Complete Guide to..."],
            ["rider-waite-tarot-beginners-guide", "Rider Waite Tarot for Beginners: Complete Guide to..."],
            ["best-tarot-apps-android-2026", "10 Best Tarot Apps for Android in 2026: Honest Comparison Guide"],
        ],
        "references": [
            "Waite, A. E. — The Pictorial Key to the Tarot (1910).",
            "Pollack, R. — Seventy-Eight Degrees of Wisdom.",
            "Nichols, S. — Jung and Tarot: An Archetypal Journey.",
        ],
        "howto": [
            {"name": "Learn the 22 cards", "text": "The Major Arcana runs 0-XXI, from the Fool to the World — 22 cards that map a complete life cycle."},
            {"name": "See the three acts", "text": "The journey divides into acts: the conscious world, the inner world, and the return."},
            {"name": "Locate yourself", "text": "Ask which card matches your current situation; the journey is a map, not a script."},
            {"name": "Read the arc", "text": "When drawing Major Arcana in readings, read them as the larger narrative arc around the question."},
        ],
        "toc": [
            ["what-is-the-journey", "What the Fool's Journey Is"],
            ["act-one", "Act One: The World (Cards 0-7)"],
            ["act-two", "Act Two: The Inner Turn (Cards 8-14)"],
            ["act-three", "Act Three: The Return (Cards 15-21)"],
            ["using-the-roadmap", "Using the Roadmap in Readings"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "what-is-the-journey", "text": "What the Fool's Journey Is"},
            {"t": "p", "text": "The Fool's Journey reads the 22 Major Arcana cards as a single narrative: the Fool starts at zero and walks through every card until the World completes the cycle. It is the tarot's answer to 'what is this life about?' — a map of the stages every person cycles through, sometimes many times."},
            {"t": "p", "text": "The journey has three acts: the Fool's outward adventure in the world (cards 0-7), the turn inward toward meaning (cards 8-14), and the confrontation with shadow followed by the return (cards 15-21)." },
            {"t": "h2", "id": "act-one", "text": "Act One: The World (Cards 0-7)"},
            {"t": "p", "text": "The first act is the external journey: identity, mastery, and relationship."},
            {"t": "table", "headers": ["Card", "Stage of the Journey"],
             "rows": [
                ["0 The Fool", "The leap of faith — the journey begins with trust and inexperience"],
                ["I The Magician", "Waking up to your tools — will, skill, and the power to act"],
                ["II The High Priestess", "Meeting intuition — the knowledge beneath the surface"],
                ["III The Empress", "Abundance and creation — nurturing what you have started"],
                ["IV The Emperor", "Structure and authority — building order from chaos"],
                ["V The Hierophant", "Learning the rules — tradition, mentorship, and belonging"],
                ["VI The Lovers", "The first great choice — values, union, and alignment"],
                ["VII The Chariot", "Victory through control — willpower driving the self forward"],
             ]},
            {"t": "p", "text": "By the Chariot, the Fool has built an identity, learned the world's rules, and won. But the outer game is only half the story — and the second act begins the moment the Fool realizes it."},
            {"t": "h2", "id": "act-two", "text": "Act Two: The Inner Turn (Cards 8-14)"},
            {"t": "p", "text": "The second act turns inward. The outer victories stop satisfying, and the journey goes below the surface."},
            {"t": "table", "headers": ["Card", "Stage of the Journey"],
             "rows": [
                ["VIII Strength", "Meeting your inner animal — courage, patience, and self-command"],
                ["IX The Hermit", "The retreat — seeking truth alone, carrying your own light"],
                ["X Wheel of Fortune", "Seeing the cycles — fate, luck, and the turn of the wheel"],
                ["XI Justice", "Taking responsibility — causes, effects, and balance"],
                ["XII The Hanged Man", "The surrender — seeing the world upside down by letting go"],
                ["XIII Death", "The necessary ending — transformation, not catastrophe"],
                ["XIV Temperance", "The integration — blending opposites into a new wholeness"],
             ]},
            {"t": "p", "text": "Temperance is the prize of the inner journey: the Fool has balanced the outer world and the inner one. But the third act waits — because what was integrated must now survive the shadow."},
            {"t": "h2", "id": "act-three", "text": "Act Three: The Return (Cards 15-21)"},
            {"t": "table", "headers": ["Card", "Stage of the Journey"],
             "rows": [
                ["XV The Devil", "Facing the shadow — attachment, illusion, and the chains you chose"],
                ["XVI The Tower", "The collapse — what was built on false ground comes down"],
                ["XVII The Star", "Hope after ruin — healing, flow, and the new vision"],
                ["XVIII The Moon", "Walking in the dark — the last illusions, fear, and dream"],
                ["XIX The Sun", "Clarity and joy — the self reborn in full light"],
                ["XX Judgement", "The calling — the reckoning, forgiveness, and awakening"],
                ["XXI The World", "The completion — wholeness, and the spiral ready to begin again"],
             ]},
            {"t": "p", "text": "The World does not end the journey — it completes the cycle, and the Fool steps into the next leap with everything they have learned. That is why the Fool is 0 and the World is XXI: the end feeds the beginning."},
            {"t": "h2", "id": "using-the-roadmap", "text": "Using the Roadmap in Readings"},
            {"t": "ul", "items": [
                "When a Major Arcana card appears, locate it on the journey — it tells you the life-stage of the question, not just the situation.",
                "Cards before it in the sequence show what has already happened; cards after it show the likely next chapter.",
                "A cluster of early cards means a beginning; a cluster near the World means a completion or major shift.",
                "Repeatedly drawing the same Major card across readings marks the stage the journey keeps returning to.",
            ]},
            {"t": "p", "text": "The roadmap is only useful if you can read the cards themselves. A complete <a href=\"../apps/unofficial-rider-waite-tarot.html\">Rider Waite tarot app</a> keeps all 78 cards — the 22 Major and the 56 Minor — with their imagery and meanings at hand, so the journey stays legible at every stage."},
        ],
        "faq": [
            ["Why is the Fool numbered 0?", "The Fool stands outside the numbered sequence: the pure potential before and after every cycle. Zero is both nothing and everything — the journey's starting point and its fuel."],
            ["Do I have to go through the cards in order?", "No. The journey is a map of stages, not a script. You can experience the Hermit's retreat at 20 and the Chariot's conquest at 50 — the cards describe patterns, not calendars."],
            ["Is the Fool's Journey the same in every tarot deck?", "The sequence of Major Arcana is nearly universal across Western decks. Imagery varies — Thoth, Marseille, modern decks — but the 22-card arc and its stages hold."],
        ],
    },
    {
        "slug": "best-offline-lucid-dreaming-app-2026",
        "title": "Best Offline Lucid Dreaming App for 2026: No Subscription, No Ads",
        "index_title": "Best Offline Lucid Dreaming App for 2026: No Subscription, No Ads",
        "desc": "Most lucid dreaming apps bury features behind subscriptions. The best offline lucid dreaming apps for 2026 — Dream Machine and Lucid Dream — work without.",
        "keywords": "best offline lucid dreaming app, lucid dreaming app without subscription, lucid dream app one time payment, offline lucid dreaming app android, lucid dreaming app no ads",
        "og_alt": "Best offline lucid dreaming apps comparison",
        "date_iso": "2026-08-16",
        "date_display": "August 16, 2026",
        "lastmod": "2026-08-16",
        "read_min": 13,
        "category": "lucid-dreaming",
        "excerpt": "Lucid dreaming apps keep moving features behind subscriptions. Here are the best OFFLINE lucid dreaming apps for 2026 — Dream Machine and Lucid Dream — with no subscription, no ads, and no internet required.",
        "cta_apps": [["dream-machine", "Dream Machine"], ["lucid-dream", "Lucid Dream"]],
        "related": [
            ["best-lucid-dreaming-apps-android-2026", "Best Lucid Dreaming Apps for Android (2026): Tested &amp; Compared"],
            ["reality-check-techniques-best-lucidity-methods", "Reality Check Techniques: Best Methods for Increasing Lucidity Rate (2026)"],
            ["best-lucid-dreaming-apps-android-2026", "Best Lucid Dreaming Apps for Android (2026): Tested &amp; Compared"],
            ["best-lucid-dreaming-apps-android-2026", "Best Lucid Dreaming Apps for Android (2026): Tested &amp; Compared"],
        ],
        "references": [
            "LaBerge, S. — Exploring the World of Lucid Dreaming.",
            "Waggoner, R. — Lucid Dreaming: Gateway to the Inner Self.",
            "Aspy, D. et al. — 'Reality testing and the MILD technique' (Dreaming, 2017).",
        ],
        "howto": [
            {"name": "Pick a reality-check habit", "text": "Choose 3-5 reality checks (nose pinch, hands, text) and tie them to daily triggers."},
            {"name": "Start a dream journal", "text": "Log dreams immediately on waking; recall is the foundation of lucidity."},
            {"name": "Choose your technique", "text": "Use MILD before sleep for beginners, or WILD for experienced dreamers."},
            {"name": "Stay consistent", "text": "Lucid dreaming is a training habit — 2-3 weeks of daily practice beats occasional intensity."},
        ],
        "toc": [
            ["the-subscription-problem", "The Subscription Problem"],
            ["what-you-need", "What a Lucid Dreaming App Should Do"],
            ["dream-machine", "Dream Machine: The All-Rounder"],
            ["lucid-dream", "Lucid Dream: The Minimalist Trainer"],
            ["comparison", "Side-by-Side Comparison"],
            ["which-to-choose", "Which One Should You Pick?"],
            ["getting-started", "Getting Started Tonight"],
            ["faq", "Frequently Asked Questions"],
        ],
        "sections": [
            {"t": "h2", "id": "the-subscription-problem", "text": "The Subscription Problem"},
            {"t": "p", "text": "The mainstream lucid dreaming apps — Awoken, Lucid Reality, and the rest of the Play Store crowd — have settled into a predictable pattern: the dream journal is free, and everything that matters — reality check reminders, audio cues, advanced techniques — lives behind a $4-10/month subscription or an ad wall."},
            {"t": "p", "text": "That is a bad deal for a training tool you need every single day. Lucid dreaming is a habit skill; it requires months of nightly use. A subscription turns a practice into a bill. The offline, one-time-payment apps below exist precisely because of this."},
            {"t": "h2", "id": "what-you-need", "text": "What a Lucid Dreaming App Should Do"},
            {"t": "ul", "items": [
                "A dream journal that works offline — you log at 3 AM, not at the office.",
                "Reality check reminders — scheduled notifications that train the checking habit.",
                "Technique guidance — MILD and WILD instructions, not just a timer.",
                "No ads in the sleep interface — nothing ruins the hypnagogic state like a banner.",
                "No account required — your dreams are your data, not their product.",
            ]},
            {"t": "h2", "id": "dream-machine", "text": "Dream Machine: The All-Rounder"},
            {"t": "p", "text": "Dream Machine is the full-featured offline option: dream journal with tags and statistics, reality check reminders, MILD and WILD coaching, sleep hygiene tracking, and a completely offline mode — everything works in airplane mode. One-time purchase, no subscription, no ads."},
            {"t": "p", "text": "It is the right choice if you want one app that covers the whole practice — journal, checks, techniques, and progress analytics — without ever asking for a recurring payment."},
            {"t": "h2", "id": "lucid-dream", "text": "Lucid Dream: The Minimalist Trainer"},
            {"t": "p", "text": "Lucid Dream takes the opposite approach: a lean, focused trainer. It centers on the reality check habit and dream recall with a clean interface and zero clutter. Offline by default, one-time payment, and small enough that it never gets in the way of the actual practice."},
            {"t": "p", "text": "It is the right choice if you already know the techniques and want a no-friction tool that reinforces the daily checks and journaling without managing your whole sleep life."},
            {"t": "h2", "id": "comparison", "text": "Side-by-Side Comparison"},
            {"t": "table", "headers": ["Feature", "Dream Machine", "Lucid Dream"],
             "rows": [
                ["Price model", "One-time payment", "One-time payment"],
                ["Subscription", "None", "None"],
                ["Ads", "None", "None"],
                ["Offline mode", "Full", "Full"],
                ["Dream journal", "Tagged, with statistics", "Simple, focused"],
                ["Reality check reminders", "Yes", "Yes"],
                ["MILD / WILD coaching", "Yes", "Core techniques"],
                ["Sleep hygiene tracking", "Yes", "Minimal"],
                ["Account required", "No", "No"],
             ]},
            {"t": "h2", "id": "which-to-choose", "text": "Which One Should You Pick?"},
            {"t": "ul", "items": [
                "New to lucid dreaming and want the full toolkit → Dream Machine.",
                "Experienced, want checks + journal with zero clutter → Lucid Dream.",
                "Care about long-term habit tracking and statistics → Dream Machine.",
                "Want the smallest, fastest app that does the job → Lucid Dream.",
            ]},
            {"t": "h2", "id": "getting-started", "text": "Getting Started Tonight"},
            {"t": "ol", "items": [
                "Install your chosen app and enable reality check reminders for 3-5 daily trigger times.",
                "Tonight, set the intention: 'I will notice I am dreaming' as you fall asleep (the MILD technique).",
                "Keep the phone beside the bed and log your first dream in the app the moment you wake.",
                "Repeat nightly for two weeks — recall improves first, lucidity follows.",
            ]},
            {"t": "p", "text": "The tool matters less than the habit — which is exactly why the offline, no-subscription options win. Try <a href=\"../apps/dream-machine.html\">Dream Machine</a> for the complete practice, or <a href=\"../apps/lucid-dream.html\">Lucid Dream</a> for the minimal trainer; both are one-time purchases that will not bill you at 3 AM."},
        ],
        "faq": [
            ["Do I need internet to use a lucid dreaming app?", "No — the apps recommended here work fully offline, including the journal and reminders. Offline matters because you log dreams at odd hours in bed, not at a desk."],
            ["Are free lucid dreaming apps actually free?", "Most are freemium: the journal is free and the useful features — reminders, cues, techniques — sit behind a subscription. A one-time-payment app is cheaper after the first month of serious use."],
            ["How long until I have my first lucid dream?", "With consistent reality checks and journaling, most people report their first lucid dream within 2-4 weeks. The habit is the whole game."],
        ],
    },
]
