# -*- coding: utf-8 -*-
# Article 27: Two-Card Tarot Spread → unofficial-rider-waite-tarot
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "two-card-tarot-spread",
    "title": "Two-Card Tarot Spread: The Quick Answer Method (2026)",
    "index_title": "Two-Card Tarot Spread: The Quick Answer Method",
    "desc": "The two-card tarot spread answers fast: situation + advice, or self + other. Learn 5 layouts, how to read them, and what two cards together mean.",
    "keywords": "two card tarot spread, 2 card tarot spread, two card spread meaning, quick tarot reading",
    "og_alt": "Two tarot cards laid side by side on a dark cloth beside a single candle",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "tarot",
    "excerpt": "Need an answer in under a minute? The two-card spread — situation and advice — is the fastest full reading in tarot.",
    "cta_apps": [["unofficial-rider-waite-tarot", "Unofficial Rider Waite Tarot"]],
    "related": [
        [RT["tarot-spreads-beginners-guide"], RT["tarot-spreads-beginners-guide"]],
        [RT["celtic-cross-tarot-spread-meaning-positions"], RT["celtic-cross-tarot-spread-meaning-positions"]],
        [RT["tarot-card-combinations-reading-techniques"], RT["tarot-card-combinations-reading-techniques"]],
        [RT["rider-waite-tarot-beginners-guide"], RT["rider-waite-tarot-beginners-guide"]],
    ],
    "references": [
        "Waite, A. E. (1910). The Pictorial Key to the Tarot.",
        "Pollack, R. (1980). Seventy-Eight Degrees of Wisdom.",
        "Greer, M. K. (2002). Tarot for Your Self.",
    ],
    "howto": [
        {"name": "Frame the question", "text": "Decide what the two positions mean before drawing: situation and advice, or self and other."},
        {"name": "Shuffle with intent", "text": "Shuffle while holding the question in mind; stop when it feels right, no fixed number of cuts."},
        {"name": "Draw two cards", "text": "Take card one for position one and card two for position two; keep their order."},
        {"name": "Read together", "text": "Interpret each card in its position, then read them as one story before noting how they interact."},
    ],
    "toc": [
        ("why-two-cards", "Why Two Cards"),
        ("five-layouts", "Five Two-Card Layouts"),
        ("situation-and-advice", "Situation and Advice"),
        ("self-and-other", "Self and Other"),
        ("past-and-future", "Past and Future"),
        ("yes-no-two-card", "Yes or No in Two Cards"),
        ("obstacle-and-help", "Obstacle and Help"),
        ("reading-pairs", "Reading the Pair"),
        ("common-mistakes", "Common Mistakes"),
        ("faq", "FAQ"),
    ],
    "sections": [
        {"t": "p", "text": "Most readers learn on the Celtic Cross, then discover the truth: the tightest readings come from the smallest spreads. The two-card tarot spread is the fastest complete reading in the deck — two positions, one story, under a minute once you know it."},
        {"t": "h2", "id": "why-two-cards", "text": "Why Two Cards"},
        {"t": "p", "text": "A single card gives you one piece of information. A two-card spread gives you a relationship: the thing and its context, the problem and the way through, you and the other person. That relationship is where the actual reading happens."},
        {"t": "ul", "items": [
            "Fast — no shuffling through ten positions while the question goes cold",
            "Focused — two cards force you to say something specific, not general",
            "Portable — drawable anywhere, even with an app during a coffee break",
            "Learnable — ideal for beginners because pair logic is simpler than spread logic",
        ]},
        {"t": "h2", "id": "five-layouts", "text": "Five Two-Card Layouts"},
        {"t": "p", "text": "The two cards stay in the same physical layout; what changes is the meaning you assign to each position. Pick the pair of lenses that fits the question before you draw."},
        {"t": "table", "headers": ["Layout", "Card 1", "Card 2", "Best For"], "rows": [
            ["Situation and advice", "Where things stand", "What to do about it", "Most questions"],
            ["Self and other", "You", "The other person", "Relationships"],
            ["Past and future", "What led here", "Where it's heading", "Timelines"],
            ["Yes or no", "The answer", "The reason", "Direct questions"],
            ["Obstacle and help", "What blocks you", "What moves you forward", "Stuck situations"],
        ]},
        {"t": "h2", "id": "situation-and-advice", "text": "Situation and Advice"},
        {"t": "p", "text": "The default layout. Card one describes the energy of the situation as it stands; card two tells you what to do with it. If you draw the Fool as situation and the Eight of Pentacles as advice, you already have the whole story: a fresh start that needs steady work."},
        {"t": "h2", "id": "self-and-other", "text": "Self and Other"},
        {"t": "p", "text": "For relationships, draw yourself and the other person — not as a verdict on them, but as the energy you are each bringing. Compare the suits: cups to cups, or wands against cups, tells you more than either card alone."},
        {"t": "h2", "id": "past-and-future", "text": "Past and Future"},
        {"t": "p", "text": "Card one is the cause, card two is the trajectory. Keep it to near-term questions — weeks, not years — because two cards lack the depth for long forecasts. It is a snapshot of momentum, not a life reading."},
        {"t": "h2", "id": "yes-no-two-card", "text": "Yes or No in Two Cards"},
        {"t": "p", "text": "Card one answers; card two explains. Cups and Pentacles lean yes, swords lean no, wands lean 'yes but only with effort'. The second card tells you the condition attached to that yes or no."},
        {"t": "h2", "id": "obstacle-and-help", "text": "Obstacle and Help"},
        {"t": "p", "text": "When you feel stuck: card one is the blockage, card two is the leverage point. The second card is your instruction — the thing to do, not the thing to fear. Act on card two within a few days."},
        {"t": "h2", "id": "reading-pairs", "text": "Reading the Pair"},
        {"t": "ul", "items": [
            "Same suit = one theme: all cups is emotional, all pentacles practical",
            "Opposite suits = tension: wands vs cups is desire against feeling",
            "Major arcana in either slot = the situation outweighs day-to-day detail",
            "Reversals: read the shadow of that position, not a new meaning",
        ]},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Reading the two cards as unrelated facts instead of one relationship",
            "Assigning positions after the draw instead of before",
            "Swapping the order to make the reading more comfortable",
            "Over-asking: one question, one draw, then let it work",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "What do two cards mean together?"},
        {"t": "p", "text": "They form one statement: card one in its position, card two answering or completing it. Read them as a single sentence, not two separate answers."},
        {"t": "h3", "text": "Is a two-card spread accurate?"},
        {"t": "p", "text": "Accuracy comes from the question and your honesty, not the number of cards. Two cards are excellent for decisions; they are too thin for deep life overviews."},
        {"t": "h3", "text": "Can I use a two-card spread in the app?"},
        {"t": "p", "text": "Yes. Draw freely and log the pair in your journal; position meanings are yours to assign. The <a href=\"../apps/unofficial-rider-waite-tarot.html\">Unofficial Rider Waite Tarot</a> keeps every reading in your history for review."},
    ],
    "faq": [
        ["Do the two cards need to match in suit?", "No. Mismatched suits are information — they show the tension or balance between the two energies you asked about."],
        ["How long should I wait before drawing again?", "For a two-card reading, one question per draw, and no repeat of the same question before a few days pass. Immediate redraws just recycle the same energy."],
        ["Is two cards enough for a love reading?", "Yes for a quick check: self and other, or situation and advice. For deeper relationship questions use a three- or five-card spread instead."],
    ],
}
