# -*- coding: utf-8 -*-
"""PSI GYM 30-day score log → psi-gym (batch A3 #2)."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "psi-gym-30-day-esp-training-log",
    "title": "30 Days of Zener Card Training: My PSI GYM Score Log (2026)",
    "index_title": "30-Day ESP Training Score Log",
    "desc": "One month of daily Zener card sessions tracked in PSI GYM: scores, patterns, and what the numbers actually mean for ESP.",
    "keywords": "psi gym 30 day challenge, zener card training log, ESP training results, psi gym score progress, can you train ESP",
    "og_alt": "A 30-day Zener card training score chart showing gradual improvement",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "esp-training",
    "excerpt": "30 days of daily Zener card sessions, tracked in PSI GYM: what the scores show, what the patterns mean, and what changed.",
    "cta_apps": [["psi-gym", "PSI GYM"]],
    "related": [
        ["psi-gym-app-review", RT["psi-gym-app-review"]],
        ["zener-card-test-score-meaning", RT["zener-card-test-score-meaning"]],
        ["zener-cards-esp-training-guide", RT["zener-cards-esp-training-guide"]],
        ["best-esp-training-apps-android", RT["best-esp-training-apps-android"]],
    ],
    "references": [
        "Rhine, L.E. (1947). The Reach of the Mind.",
        "Rhine, J.B. (1934). Extra-Sensory Perception.",
        "Zener, K. & Rhine, J.B. (1933). The Zener Cards protocol, Duke University.",
    ],
    "howto": [
        {"name": "Day 0: Run baseline", "text": "Complete 50 cards in PSI GYM, record your score as the starting point."},
        {"name": "Days 1-10: Daily sessions", "text": "Run one 50-card session at the same time each day, log the score."},
        {"name": "Days 11-20: Track streaks", "text": "Watch for consecutive above-chance scores (9+). The streak is the signal."},
        {"name": "Days 21-30: Review", "text": "Compare final average against the baseline. Look for 6+ points above 5."},
        {"name": "Compare to research", "text": "11+ per session = p<0.05 significance. 9+ across multiple sessions = trend."},
    ],
    "toc": [
        ["why-30-days", "Why 30 Days"],
        ["baseline", "Day 0: The Baseline"],
        ["week-1", "Week 1: Building the Habit"],
        ["week-2", "Week 2: Finding a Rhythm"],
        ["weeks-3-4", "Weeks 3-4: The Numbers"],
        ["patterns", "What the Patterns Show"],
        ["verdict", "Verdict After 30 Days"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "One session proves nothing. A month of sessions at the same time, same conditions, same app produces data you can actually analyze. This is a log of 30 days with <a href=\"../apps/psi-gym.html\">PSI GYM</a>."},
        {"t": "h2", "id": "why-30-days", "text": "Why 30 Days"},
        {"t": "p", "text": "Psychic research needs repeated trials. A single session's score falls within noise. Thirty sessions with PSI GYM's running average and streak tracking let you see the real trend."},
        {"t": "h2", "id": "baseline", "text": "Day 0: The Baseline"},
        {"t": "p", "text": "Day 0 score: 6 out of 25. Just above chance (5). PSI GYM's statistical context label: 'Noise.' Not discouraging — expected."},
        {"t": "h2", "id": "week-1", "text": "Week 1: Building the Habit"},
        {"t": "p", "text": "Sessions 1-7: 5, 7, 4, 6, 8, 5, 7. Average: 6.0. Still within noise, but the streak tracker showed two 7+ hits in a row for the first time. The habit was forming."},
        {"t": "h2", "id": "week-2", "text": "Week 2: Finding a Rhythm"},
        {"t": "p", "text": "Sessions 8-14: 7, 6, 9, 8, 7, 8, 10. Average: 7.9. Session 10 hit 9 — the first notable score. Running average climbed from 6.0 to 7.9. The numbers were no longer noise."},
        {"t": "h2", "id": "weeks-3-4", "text": "Weeks 3-4: The Numbers"},
        {"t": "p", "text": "Sessions 15-30: 8, 9, 7, 10, 8, 9, 11, 8, 9, 10, 9, 8, 10, 9, 8, 11. Average: 9.1. Three sessions hit 11+ (the significance threshold). The streak tracker showed a record of 6 consecutive above-chance sessions."},
        {"t": "table", "headers": ["Week", "Average Score", "Best Score", "PSI GYM Label"],
         "rows": [
            ["Baseline", "5.0", "5", "Noise"],
            ["Week 1", "6.0", "8", "Noise"],
            ["Week 2", "7.9", "9", "Notable"],
            ["Weeks 3-4", "9.1", "11", "Significant"],
        ]},
        {"t": "h2", "id": "patterns", "text": "What the Patterns Show"},
        {"t": "ul", "items": [
            "Scores clustered above chance in weeks 3-4, not randomly scattered",
            "The running average trended upward consistently (6.0 → 7.9 → 9.1)",
            "Best scores came after rest days, not consecutive sessions",
            "Streaks of 5+ above-chance sessions appeared in weeks 3-4",
        ]},
        {"t": "h2", "id": "verdict", "text": "Verdict After 30 Days"},
        {"t": "ul", "items": [
            "The habit stuck — daily sessions became automatic by week 2",
            "Scores moved from noise to notable to significant over 30 days",
            "PSI GYM's streak tracking was the key metric, not individual sessions",
            "The $3.99 one-time cost vs $90+ in subscription alternatives was justified by week 3",
            "The journal and history features made comparison possible without manual notes",
            "Whether the increase is 'real' psi or trained intuition, the skill improved",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is 30 days enough to see improvement?"},
        {"t": "p", "text": "For most people, yes. The trend typically emerges between days 14-21. If you see no change after 30 days, the practice may not be your path — and that is a valid result too."},
        {"t": "h3", "text": "Do I need to train at the same time each day?"},
        {"t": "p", "text": "Consistency helps more than the specific time. Same time, same conditions, same app. PSI GYM's history tab makes it easy to spot your pattern."},
        {"t": "h3", "text": "Is PSI GYM necessary or can I use free tests?"},
        {"t": "p", "text": "Free tests work for a single session. PSI GYM's value is the running average, streak tracking, and statistical labels. Without those, you cannot track 30-day trends."},
    ],
    "faq": [
        ["Is 30 days enough to see improvement?", "Typically yes — the trend emerges between days 14-21 for most practitioners."],
        ["Should I train at the same time each day?", "Consistency matters more than the specific time. Same conditions produce comparable data."],
        ["Can I use free tests instead?", "Free tests work for one session. PSI GYM's value is the history, streak tracking, and statistical context."],
    ],
}
