# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "dream-machine-dream-journal-guide",
    "title": "How to Use the Dream Journal in Dream Machine: Complete Guide (2026)",
    "index_title": "Dream Machine Dream Journal: Complete Guide",
    "desc": "A complete walkthrough of the Dream Machine dream journal: tagging, dream signs, recall scoring, and turning entries into lucidity triggers.",
    "keywords": "dream machine dream journal, dream journal app, dream machine app guide, lucid dreaming journal, dream recall journal",
    "og_alt": "A phone showing the Dream Machine dream journal with a lucid dream entry tagged with dream signs",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "lucid-dreaming",
    "excerpt": "The journal is the engine of lucidity. Here is how to use Dream Machine's journal to double your dream recall in two weeks.",
    "cta_apps": [["dream-machine", "Dream Machine"]],
    "related": [
        ["dream-machine-app-review", RT["dream-machine-app-review"]],
        ["how-to-lucid-dream-tonight", RT["how-to-lucid-dream-tonight"]],
        ["dream-journaling-lucid-dreaming-complete-guide", RT["dream-journaling-lucid-dreaming-complete-guide"]],
        ["dream-machine-vs-awoken-comparison", RT["dream-machine-vs-awoken-comparison"]],
    ],
    "references": [
        "LaBerge, S. (1985). Lucid Dreaming: The Power of Being Awake and Aware in Your Dreams.",
        "LaBerge, S. & Rheingold, H. (1990). Exploring the World of Lucid Dreaming.",
        "Aspy, D. J. et al. (2017). Reality testing and the mnemonic induction of lucid dreams: Findings from the national Australian lucid dream induction study.",
    ],
    "howto": [
        {"name": "Write the moment you wake", "text": "Keep the app one tap away and log before anything else, even before moving much."},
        {"name": "Tag every entry", "text": "Add dream signs, emotions, and settings so patterns become searchable."},
        {"name": "Score your recall", "text": "Rate how vivid the dream was from 1 to 5 to track improvement over time."},
        {"name": "Review your dream signs weekly", "text": "Pick the three most frequent signs and turn them into reality checks."},
        {"name": "Repeat for two weeks", "text": "Consistency, not length, is what raises recall and lucidity rates."},
    ],
    "toc": [
        ["why-journaling-works", "Why Journaling Works"],
        ["first-entry", "Your First Entry"],
        ["tagging-and-dream-signs", "Tagging & Dream Signs"],
        ["recall-scoring", "Recall Scoring"],
        ["finding-your-patterns", "Finding Your Patterns"],
        ["journal-to-lucidity", "From Journal to Lucidity"],
        ["nightmare-and-recurring", "Nightmares & Recurring Dreams"],
        ["common-mistakes", "Common Mistakes"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Lucid dreaming research keeps pointing at one unglamorous tool: the dream journal. In the 2017 Australian study led by Denholm Aspy, participants who combined reality testing with a journal and the MILD technique saw a lucid dream rate of around 17 percent in a single week — far above the control group. The journal is not a diary; it is the database your brain learns from."},
        {"t": "h2", "id": "why-journaling-works", "text": "Why Journaling Works"},
        {"t": "p", "text": "Every time you record a dream, you send your brain a signal: these experiences matter. That signal raises dream recall, and recall is the gatekeeper of lucidity — you cannot become aware inside a dream you do not remember. Journaling also builds the habit of paying attention to inner experience, which transfers directly into the dream state."},
        {"t": "h2", "id": "first-entry", "text": "Your First Entry"},
        {"t": "p", "text": "Open Dream Machine, tap the journal, and write whatever you remember — even a single image or feeling counts. The app saves locally on your device, so there is no account to create and no cloud dependency. Write in the morning, in bed, before you scroll anything."},
        {"t": "ul", "items": [
            "Log within five minutes of waking for the best recall.",
            "Write in fragments if that is all you have; length comes later.",
            "Note the emotion, not just the plot.",
            "Do not edit or judge the entry; raw memory is the goal.",
        ]},
        {"t": "h2", "id": "tagging-and-dream-signs", "text": "Tagging & Dream Signs"},
        {"t": "p", "text": "Dream signs are recurring elements inside your dreams — a person, place, situation, or even a color. They are the fingerprints of your dream world. Dream Machine lets you tag entries so these signs become searchable."},
        {"t": "ul", "items": [
            "Tag locations, people, and recurring objects.",
            "Tag the emotion of the dream (anxious, joyful, confused).",
            "Tag whether it was lucid or not.",
            "After a week, open the tag view and count frequencies.",
        ]},
        {"t": "h2", "id": "recall-scoring", "text": "Recall Scoring"},
        {"t": "p", "text": "Dream Machine's 1-5 recall score gives you a measurable trend. A 1 is a vague feeling; a 5 is a detailed, movie-like sequence. Tracking the number turns recall from a vague impression into a metric you can improve."},
        {"t": "h2", "id": "finding-your-patterns", "text": "Finding Your Patterns"},
        {"t": "ol", "items": [
            "After seven nights, open the journal archive.",
            "Sort by tags and note your top three dream signs.",
            "Cross-reference: do signs cluster on certain days or emotions?",
            "Choose one sign to reality-check against tomorrow.",
        ]},
        {"t": "p", "text": "For example, if 'back at school' appears in three of your last seven dreams, that is your cue. Every time you see a school in waking life, do a reality check — and the habit will bleed into dreams."},
        {"t": "h2", "id": "journal-to-lucidity", "text": "From Journal to Lucidity"},
        {"t": "p", "text": "Once patterns are visible, the journal feeds directly into the MILD technique: before sleep, repeat the phrase 'I will remember to recognize I am dreaming,' and visualize yourself becoming lucid inside your most common dream scene. Dream Machine pairs the journal with built-in reality check reminders and a WBTB timer, so the whole loop lives in one app."},
        {"t": "h2", "id": "nightmare-and-recurring", "text": "Nightmares & Recurring Dreams"},
        {"t": "p", "text": "Recurring nightmares respond well to journaling because the pattern becomes visible and therefore addressable. Tag a nightmare, identify its trigger scene, then use the journal to rewrite the ending while awake — imagery rehearsal — which has solid evidence for reducing nightmare frequency. Dream Machine includes a dedicated nightmare mode for exactly this work."},
        {"t": "h2", "id": "common-mistakes", "text": "Common Mistakes"},
        {"t": "ul", "items": [
            "Skipping days: recall drops fast when the habit breaks.",
            "Writing too long: a wall of text you dread revisiting.",
            "Ignoring tags: without tags, patterns stay invisible.",
            "Journaling only lucid dreams: non-lucid entries carry the signs.",
            "Forgetting to review: entries only help if you actually read them.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Do I need a separate dream journal app?"},
        {"t": "p", "text": "No. Dream Machine bundles the journal with reality check reminders, a WBTB timer, MILD coaching, and nightmare tools — everything in one place, fully offline, for a single one-time payment."},
        {"t": "h3", "text": "How long until my recall improves?"},
        {"t": "p", "text": "Most people see a measurable jump within two weeks of daily logging, and studies of the MILD + journal combo show results in as little as one week."},
        {"t": "h3", "text": "Is my journal private?"},
        {"t": "p", "text": "Yes. Entries are stored locally on your device. There is no account and no cloud upload — which also means you can journal in airplane mode."},
    ],
    "faq": [
        ["Does Dream Machine require a subscription?", "No. Dream Machine is a one-time purchase with no subscriptions, no ads, and no account requirements."],
        ["Can I export my dream journal?", "The app keeps everything on your device, so your data is always yours; export before uninstalling is supported."],
        ["Does the journal work offline?", "Yes, the entire journal — writing, tagging, and reviewing — works without internet."],
    ],
}
