# -*- coding: utf-8 -*-
"""A125: The 72 Goetia Spirits: Complete Ranked List"""
from related_titles import RELATED_TITLES as RT

A125 = {
    'slug': 'the-72-goetia-spirits-complete-ranked-list',
    'title': 'The 72 Goetia Spirits: Complete Ranked List (2026)',
    'index_title': 'The 72 Goetia Spirits: Complete Ranked List',
    'desc': 'All 72 spirits of the Goetia in one ranked reference: their numbers, names, roles, and seals. Bookmark this page for working reference.',
    'keywords': 'goetia spirits, 72 spirits, goetia list, solomon spirits, ars goetia, spirit seals, lesser key of solomon',
    'date_iso': '2026-08-16',
    'date_display': 'August 16, 2026',
    'lastmod': '2026-08-16',
    'read_min': 10,
    'category': 'Goetia & Spirits',
    'excerpt': (
        'The Goetia, first book of the Lesser Key of Solomon, catalogs 72 spirits ranked from king '
        'to president. Each has a number, a name, a function, and a seal. This is the complete '
        'reference list for serious practitioners and curious readers alike.'
    ),
    'cta_apps': [
        ['arcana-goetia', 'Arcana Goetia']
    ],
    'related': [
        ['arcana-goetia-app-review', RT['arcana-goetia-app-review']],
        ['goetia-beginners-ritual', RT['goetia-beginners-ritual']],
        ['which-goetia-spirit-for-love-money-knowledge', RT['which-goetia-spirit-for-love-money-knowledge']],
        ['goetia-seals-and-sigils-guide', RT['goetia-seals-and-sigils-guide']],
    ],
    'references': [
        'Peterson, J. H. (Ed.). (1999). The Lesser Key of Solomon: Detailing the Ceremonial Art of Commanding Spirits Both Good and Evil. Weiser Books.',
        'Rudd, T. (2012). The Goetia of Dr Rudd. Golden Hoard Press.',
        'Mathers, S. L. M., & Crowley, A. (1904). The Goetia: The Lesser Key of Solomon the King. Society for the Propagation of Religious Truth.',
    ],
    'howto': [
        {'name': 'Learn the four ranks', 'text': 'Spirits are ranked as Kings, Dukes, Princes, Marquises, Counts, Knights, and Presidents. Rank affects precedence in ritual, not power level.'},
        {'name': 'Study the numbers', 'text': 'Each spirit has a number 1-72. The number links to its seal and its position in the evocation order.'},
        {'name': 'Read the functions', 'text': 'Each spirit has a specific domain: love, knowledge, protection, or hidden treasure. Match the function to your need.'},
        {'name': 'Handle the seals', 'text': 'The seal is the visual anchor of the working. Use the correct seal for the spirit you evoke, never a generic one.'},
        {'name': 'Use the app', 'text': 'Arcana Goetia keeps the full catalog, seals, and step-by-step ritual guidance in your pocket with zero ads.'},
    ],
    'toc': [
        ['start', 'The 72 Goetia Spirits'],
        ['the-four-ranks', 'The Four Ranks'],
        ['the-first-four-kings', 'The First Four Kings'],
        ['the-full-list', 'The Full List'],
        ['how-to-use-this-list', 'How to Use This List'],
        ['faq', 'FAQ'],
    ],
    'sections': [
        {'t': 'p', 'text': 'The Goetia is the first book of The Lesser Key of Solomon, a 17th-century grimoire that catalogs 72 spirits. For over three centuries it has been the standard working text for evocation practice. This reference condenses the catalog into one readable list.'},
        {'t': 'h2', 'text': 'The Four Ranks', 'id': 'the-four-ranks'},
        {'t': 'p', 'text': 'The 72 spirits are organized by rank, which determines their precedence in the evocation circle. Rank describes authority in the hierarchy, not moral goodness or power.'},
        {'t': 'table', 'headers': ['Rank', 'Number of Spirits', 'Typical Domain'], 'rows': [
            ['King', '4', 'High-level authority, broad domains'],
            ['Duke', '16', 'Battle, philosophy, love, treasure'],
            ['Prince', '8', 'Concealment, discovery, knowledge'],
            ['Marquis', '15', 'War, love, hidden things'],
            ['Count / Earl', '8', 'Beauty, love, persuasion'],
            ['Knight', '2', 'War, enmity, destruction'],
            ['President', '14', 'Teaching, treasure, healing, theft'],
        ]},
        {'t': 'h2', 'text': 'The First Four Kings', 'id': 'the-first-four-kings'},
        {'t': 'p', 'text': 'The four ruling kings govern the four cardinal directions and are often treated as the entry points to the hierarchy. They are Bael, Paimon, Beleth, and Asmoday.'},
        {'t': 'table', 'headers': ['Number', 'Name', 'Rank', 'Direction', 'Core Function'], 'rows': [
            ['1', 'Bael', 'King', 'East', 'Invisibility, wisdom'],
            ['9', 'Paimon', 'King', 'West', 'Knowledge, arts, honor'],
            ['13', 'Beleth', 'King', 'North', 'Love, favor, loyalty'],
            ['32', 'Asmoday', 'King', 'East', 'Divination, treasure, protection'],
        ]},
        {'t': 'h2', 'text': 'The Full List', 'id': 'the-full-list'},
        {'t': 'p', 'text': 'The complete catalog condensed: number, name, rank, and one-line function. This is the reference table for lookup during study or ritual.'},
        {'t': 'table', 'headers': ['No.', 'Name', 'Rank', 'One-Line Function'], 'rows': [
            ['1', 'Bael', 'King', 'Invisibility and wisdom'],
            ['2', 'Agares', 'Duke', 'Language, movement, earthquakes'],
            ['3', 'Vassago', 'Prince', 'Past, present, future'],
            ['4', 'Samigina', 'Marquis', 'Corpses, spirits of the dead'],
            ['5', 'Marbas', 'President', 'Healing, mechanics, true answers'],
            ['6', 'Valefor', 'Duke', 'Thievery and trust'],
            ['7', 'Amon', 'Marquis', 'Love, reconciliation, truth'],
            ['8', 'Barbatos', 'Duke', 'Animals, languages, hidden things'],
            ['9', 'Paimon', 'King', 'Knowledge, arts, honor'],
            ['10', 'Buer', 'President', 'Healing, philosophy, logic'],
            ['11', 'Gusion', 'Duke', 'Honor, friendship, answers'],
            ['12', 'Sitri', 'Prince', 'Love and desire'],
            ['13', 'Beleth', 'King', 'Love, favor, loyalty'],
            ['14', 'Leraje', 'Marquis', 'Archery and battle'],
            ['15', 'Eligos', 'Duke', 'War, battles, outcomes'],
            ['16', 'Zepar', 'Duke', 'Love, lust, barrenness'],
            ['17', 'Botis', 'President', 'Reconciliation, past and future'],
            ['18', 'Bathin', 'Duke', 'Travel, herbs, precious stones'],
            ['19', 'Sallos', 'Duke', 'Love and attraction'],
            ['20', 'Purson', 'King', 'Secrets, treasure, hidden things'],
            ['21', 'Marax', 'Count', 'Astronomy, herbs, knowledge'],
            ['22', 'Ipos', 'Prince', 'Courage, wit, future events'],
            ['23', 'Aim', 'Duke', 'Fire, bravery, boldness'],
            ['24', 'Naberius', 'Marquis', 'Arts, eloquence, restoration'],
            ['25', 'Glasya-Labolas', 'President', 'Knowledge, violence, love'],
            ['26', 'Bune', 'Duke', 'Wealth, eloquence, death'],
            ['27', 'Ronove', 'Marquis', 'Languages, friendship, favor'],
            ['28', 'Berith', 'Duke', 'Alchemy, metals, past'],
            ['29', 'Astaroth', 'Duke', 'Past and future, liberal sciences'],
            ['30', 'Forneus', 'Marquis', 'Languages, reputation, teaching'],
            ['31', 'Foras', 'President', 'Logic, ethics, health, treasure'],
            ['32', 'Asmoday', 'King', 'Divination, treasure, protection'],
            ['33', 'Gaap', 'President', 'Philosophy, love, ceremonies'],
            ['34', 'Furfur', 'Count', 'Love, storms, truth'],
            ['35', 'Marchosias', 'Marquis', 'Battle and strength'],
            ['36', 'Stolas', 'Prince', 'Astronomy, herbs, precious stones'],
            ['37', 'Phenex', 'Marquis', 'Poetry, science, transformation'],
            ['38', 'Halphas', 'Earl', 'War, weapons, supplies'],
            ['39', 'Malphas', 'President', 'Buildings, towers, discovery'],
            ['40', 'Raum', 'Earl', 'Treasure, love, destruction'],
            ['41', 'Focalor', 'Duke', 'Seas, winds, drowning'],
            ['42', 'Vepar', 'Duke', 'Waters, navigation, storms'],
            ['43', 'Sabnock', 'Marquis', 'Buildings, camps, wounds'],
            ['44', 'Shax', 'Marquis', 'Blinding, speech, treasures'],
            ['45', 'Vine', 'King', 'Knowledge, discovery, storms'],
            ['46', 'Bifrons', 'Earl', 'Astrology, knowledge, death'],
            ['47', 'Uvall', 'Duke', 'Love, friendship, past and future'],
            ['48', 'Haagenti', 'President', 'Alchemy, transformation, wisdom'],
            ['49', 'Crocell', 'Duke', 'Knowledge, rhetoric, waters'],
            ['50', 'Furcas', 'Knight', 'Philosophy, astronomy, rhetoric'],
            ['51', 'Balam', 'King', 'Past, present, future'],
            ['52', 'Alloces', 'Duke', 'Astronomy, learning, hidden things'],
            ['53', 'Caim', 'President', 'Judgment, birds, understanding'],
            ['54', 'Murmur', 'Duke', 'Philosophy, spirits of the dead'],
            ['55', 'Orobas', 'Prince', 'Divination, favor, truth'],
            ['56', 'Gremory', 'Duke', 'Love, treasure, past and future'],
            ['57', 'Ose', 'President', 'Transformation, illusions'],
            ['58', 'Amy', 'President', 'Astronomy, knowledge, safe passage'],
            ['59', 'Orias', 'Marquis', 'Astrology, transformation, favor'],
            ['60', 'Vapula', 'Duke', 'Handicrafts, philosophy, knowledge'],
            ['61', 'Zagan', 'King', 'Alchemy, transformation, wisdom'],
            ['62', 'Valac', 'President', 'Serpents, hidden treasure'],
            ['63', 'Andras', 'Marquis', 'Discord, enmity, destruction'],
            ['64', 'Flauros', 'Duke', 'Past and future, enemies'],
            ['65', 'Andrealphus', 'Marquis', 'Geometry, measurement, perception'],
            ['66', 'Cimejes', 'Marquis', 'Rhetoric, languages, discovery'],
            ['67', 'Amdusias', 'Duke', 'Music, sound, manifestation'],
            ['68', 'Belial', 'King', 'Favor, influence, honors'],
            ['69', 'Decarabia', 'Marquis', 'Birds, herbs, stones, transformation'],
            ['70', 'Seere', 'Prince', 'Swift travel, discovery, truth'],
            ['71', 'Dantalion', 'Duke', 'Thought, dreams, knowledge'],
            ['72', 'Andromalius', 'Earl', 'Theft, justice, reconciliation'],
        ]},
        {'t': 'h2', 'text': 'How to Use This List', 'id': 'how-to-use-this-list'},
        {'t': 'ul', 'items': [
            'Look up a spirit by number when you know the seal but not the name.',
            'Match the one-line function to your working before choosing a spirit.',
            'Note the rank: Kings and Dukes are addressed with more formal protocol.',
            'Pair the reference with the correct seal before any evocation.',
            'Keep a log of which spirits you have studied so far.',
        ]},
        {'t': 'h2', 'text': 'FAQ', 'id': 'faq'},
    ],
    'faq': [
        ('Are all 72 spirits dangerous?', 'No. The grimoire tradition treats them as entities with specific functions, not as uniformly hostile forces. Risk comes from sloppy protocol, not from the spirit itself. Study, correct seals, and clean procedure keep working safe.'),
        ('Which spirit should a beginner contact first?', 'Most practitioners start with a President like Buer or Marbas for healing or answers, or with Bune for practical wealth work. These have gentler reputations than the martial spirits. Avoid the four Kings until you have ritual experience.'),
        ('Is this list historically accurate?', 'The catalog comes from the 17th-century Lesser Key of Solomon, itself a compilation of earlier grimoires. Names and functions vary slightly across manuscript traditions; this list follows the Peterson edition, the standard scholarly reference.'),
    ],
}