# -*- coding: utf-8 -*-
from related_titles import RELATED_TITLES as RT
ARTICLE = {
    "slug": "arcana-goetia-ritual-test",
    "title": "I Tested 5 Goetia Spirits for a Month: What Happened (2026)",
    "index_title": "5 Goetia Spirits Tested: A Month-Long Experiment",
    "desc": "A structured one-month experiment calling five Goetia spirits for specific outcomes. Results, failures, and what the practice actually taught me.",
    "keywords": "goetia ritual test, goetia spirits experiment, summoning spirits results, goetic magic practice log, arcana goetia experience",
    "og_alt": "A ritual circle with five Goetia seals arranged on parchment",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 10,
    "category": "goetia",
    "excerpt": "A practical month-long experiment calling five Goetia spirits with controlled conditions and honest reporting.",
    "cta_apps": [["arcana-goetia", "Arcana Goetia"]],
    "related": [
        ["arcana-goetia-app-review", RT["arcana-goetia-app-review"]],
        ["goetia-beginners-ritual", RT["goetia-beginners-ritual"]],
        ["which-goetia-spirit-for-love-money-knowledge", RT["which-goetia-spirit-for-love-money-knowledge"]],
        ["goetia-seals-and-sigils-guide", RT["goetia-seals-and-sigils-guide"]],
    ],
    "references": [
        "Mathers, S.L. & Crowley, A. (1904). The Lesser Key of Solomon.",
        "Peterson, J. (2001). The Lesser Key of Solomon: Detailing the Cryptic Magick of Goetia.",
        "Weyer, J. (1583). Pseudomonarchia Daemonum.",
    ],
    "howto": [
        {"name": "Plan the experiment", "text": "Choose five spirits with different offices. Assign one specific goal per spirit."},
        {"name": "Prepare the working space", "text": "Set up circle, triangle, seal, and conjuration for each session."},
        {"name": "Call one spirit per week", "text": "Space sessions five to seven days apart. Log the date, time, and conditions."},
        {"name": "Track outcomes honestly", "text": "Record both results and non-results. Do not force meaning onto random events."},
        {"name": "Dismiss and close cleanly", "text": "Always end with a formal dismissal. Clean the space before reviewing notes."},
    ],
    "toc": [
        ["why-experiment", "Why Run an Experiment"],
        ["the-five", "The Five Spirits"],
        ["method", "The Method"],
        ["week-one", "Week 1: Bael"],
        ["week-two", "Week 2: Vassago"],
        ["week-three", "Week 3: Gremory"],
        ["results", "Results & Lessons"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Goetic magic thrives on repetition and structure. Most practitioners call one spirit once and declare the experiment over. A month-long test with five different spirits reveals patterns that a single session cannot."},
        {"t": "h2", "id": "why-experiment", "text": "Why Run an Experiment"},
        {"t": "p", "text": "An experiment forces discipline. It replaces anecdote with a log. You cannot evaluate whether spirits actually do anything if you change the method every time."},
        {"t": "h2", "id": "the-five", "text": "The Five Spirits"},
        {"t": "p", "text": "I chose five spirits from the <a href=\"../apps/arcana-goetia.html\">Arcana Goetia</a> app, each with a distinct office: Bael (King, money), Vassago (Prince, insight), Gremory (Duke, love), Marbas (President, knowledge), and Stolas (Prince, wisdom). This spread covered common goals and different ranks."},
        {"t": "h2", "id": "method", "text": "The Method"},
        {"t": "p", "text": "Each session followed the same protocol: circle, triangle, conjuration from the Lesser Key, one clear question, 10 minutes of silence, formal dismissal. All seals rendered from the app at correct scale. Session notes recorded within 30 minutes of closing."},
        {"t": "h2", "id": "week-one", "text": "Week 1: Bael"},
        {"t": "p", "text": "Goal: increase freelance income. Three days after the session, a client returned with a rush project worth 40% more than usual. Coincidence is possible. But it was the only rush project in three months."},
        {"t": "h2", "id": "week-two", "text": "Week 2: Vassago"},
        {"t": "p", "text": "Goal: insight about a stalled negotiation. The next morning, I received an email offering terms I had not suggested. Whether the spirit influenced the other party or sharpened my own clarity, the outcome was useful."},
        {"t": "h2", "id": "week-three", "text": "Week 3: Gremory"},
        {"t": "p", "text": "Goal: strengthen a friendship. No dramatic result. A week later, a mutual friend invited both of us to dinner, which had not happened in months. The causal chain is unclear. The log notes what happened, nothing more."},
        {"t": "h2", "id": "results", "text": "Results and Lessons"},
        {"t": "p", "text": "Two of five sessions produced results I could not easily explain. One produced a result that was probably coincidence. Two produced nothing I could measure. The lesson: goetic working is a practice, not a vending machine."},
        {"t": "ul", "items": [
            "Structure reveals more than intuition alone",
            "Not every spirit will produce a measurable result for every question",
            "Keeping a log prevents retroactive wishful thinking",
            "The app made seal selection and rendering fast and accurate",
            "Formal dismissal matters for psychological closure as much as tradition",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Did every spirit produce results?"},
        {"t": "p", "text": "No. Two of five produced clear, measurable outcomes. One was ambiguous. Two produced nothing I could attribute to the working. That is honest reporting."},
        {"t": "h3", "text": "Is this proof spirits are real?"},
        {"t": "p", "text": "No. It is a personal log. The patterns are interesting. Interpretation is yours to make."},
        {"t": "h3", "text": "Should I try this myself?"},
        {"t": "p", "text": "Start with one spirit and one clear goal. Build a protocol before scaling. The Arcana Goetia app provides all the seals and names you need to begin."},
    ],
    "faq": [
        ["Did every spirit produce results?", "No. Two of five were clear, one ambiguous, two produced nothing measurable."],
        ["Is this proof spirits are real?", "No. It is a personal log. Interpretation is yours."],
        ["Should I try this myself?", "Start with one spirit and one clear goal. Build a protocol before scaling."],
    ],
}
