# -*- coding: utf-8 -*-
# Article 13: Zener Card Telepathy Test — classic ESP experiment protocol.
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "zener-card-telepathy-test",
    "title": "Zener Card Telepathy Test: How to Run the Classic ESP Experiment (2026)",
    "index_title": "Zener Card Telepathy Test: The Classic ESP Experiment",
    "desc": "How to run a Zener card telepathy test: sender and receiver roles, the 25-card run, scoring, the distance effect, and how to tell psi-hitting from chance.",
    "keywords": "zener card telepathy test, telepathy test with zener cards, ESP experiment protocol, sender receiver telepathy test, card guessing experiment",
    "og_alt": "A sender and receiver seated apart with a Zener card and a score sheet",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 9,
    "category": "esp",
    "excerpt": "Run the classic Zener card telepathy test: sender looks, receiver guesses, and the score sheet decides. Full protocol, scoring, and the distance effect explained.",
    "cta_apps": [["psi-gym", "PSI GYM: Zener Cards & ESP"]],
    "related": [
        ["zener-cards-esp-training-guide", RT["zener-cards-esp-training-guide"]],
        ["zener-card-test-score-meaning", RT["zener-card-test-score-meaning"]],
        ["psi-gym-app-review", RT["psi-gym-app-review"]],
        ["scientific-studies-zener-cards-esp-validation", RT["scientific-studies-zener-cards-esp-validation"]],
    ],
    "references": [
        "Rhine, J.B. Extra-Sensory Perception. Boston Society for Psychical Research, 1934.",
        "Rhine, J.B. The Reach of the Mind. William Sloane Associates, 1947.",
        "Zener, K. & Rhine, J.B. Standardized ESP card test protocols, Duke University Parapsychology Laboratory.",
    ],
    "howto": [
        {"name": "Set the roles", "text": "One person is the sender (perceiver of the card), one is the receiver (the guesser). Swap roles between runs for balance."},
        {"name": "Separate the two", "text": "The receiver must not see the cards or the sender's face. Screen between them, or have the sender look away from the receiver entirely."},
        {"name": "Use a quiet room", "text": "Remove noise and distractions. A focused environment matters more than any ritual."},
        {"name": "Run 25 trials", "text": "The sender draws one card at a time and looks at it for a few seconds. The receiver names their guess; record it immediately."},
        {"name": "Score and repeat", "text": "Score hits vs misses, then run at least three full decks of 25 to see whether results are stable."},
    ],
    "toc": [
        ["what-is-telepathy-test", "What Is a Zener Card Telepathy Test?"],
        ["telepathy-vs-clairvoyance", "Telepathy vs Clairvoyance in the Cards"],
        ["classic-setup", "The Classic Rhine Setup"],
        ["step-by-step", "Step-by-Step Protocol"],
        ["scoring", "How to Score the Test"],
        ["distance-effect", "Does Distance Matter?"],
        ["controlled-vs-casual", "Casual Test vs Controlled Experiment"],
        ["common-errors", "Common Errors That Inflate Scores"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "The Zener card telepathy test is the most famous parapsychology experiment ever run: five symbols, a sender, a receiver, and a score sheet. It was born at Duke University in the 1930s, and it is still the fastest way to test whether two minds can pass information without the senses. This guide gives you the full protocol — including the parts most online tutorials leave out."},
        {"t": "h2", "id": "what-is-telepathy-test", "text": "What Is a Zener Card Telepathy Test?"},
        {"t": "p", "text": "A standard Zener deck has 25 cards: five each of circle, cross, waves, square, and star. In the telepathy variant, the sender looks at one card and mentally projects it; the receiver tries to name it. Pure chance predicts 5 correct out of 25. Scores above that are where the interesting questions begin."},
        {"t": "h2", "id": "telepathy-vs-clairvoyance", "text": "Telepathy vs Clairvoyance in the Cards"},
        {"t": "p", "text": "The same deck tests two different abilities depending on who looks at the card. In clairvoyance, nobody sees the card — the receiver must pick it from the deck without any visual contact. In telepathy, the sender sees it and attempts to transmit it. The distinction mattered enormously to Rhine: it separated mind-to-mind transmission from mind-to-object perception. Run them as separate sessions and compare your scores."},
        {"t": "h2", "id": "classic-setup", "text": "The Classic Rhine Setup"},
        {"t": "p", "text": "Rhine's lab used a screen between sender and receiver, an experimenter who shuffled and drew the cards, and a strict recording procedure. You can approximate it with a cardboard screen or an open door between rooms. The key points: no visual or auditory leakage, immediate recording of each guess, and no feedback until the run ends — feedback mid-run is a known bias."},
        {"t": "h2", "id": "step-by-step", "text": "Step-by-Step Protocol"},
        {"t": "ol", "items": [
            "Shuffle a 25-card Zener deck (or use a digital deck). Set the screen between sender and receiver.",
            "The sender draws one card at a time and stares at it for 3-5 seconds, holding the symbol clearly in mind.",
            "The receiver says their guess out loud. Neither party comments until the whole run is done.",
            "A third person (or the sender, after) records each guess on a score sheet with checkmarks.",
            "At 25 trials, total the hits. Repeat the run two more times with the roles swapped.",
        ]},
        {"t": "h2", "id": "scoring", "text": "How to Score the Test"},
        {"t": "table", "headers": ["Score (out of 25)", "What It Suggests"], "rows": [
            ["0-4", "Below chance — psi-missing or a bad run; rerun before concluding anything"],
            ["5", "Exactly chance — the baseline you expect from luck"],
            ["6-8", "Above chance but within noise; promising, not proof"],
            ["9-10", "Notable — worth taking seriously if it repeats"],
            ["11+", "Beyond p < 0.05 territory for a 25-card deck — statistically interesting"],
        ]},
        {"t": "p", "text": "A single good run proves little; streaks of consistent scores across three or more decks are what deserve attention. This is where a digital trainer helps: the PSI GYM app automates the card display and scoring, so you can log run after run without score-sheet errors."},
        {"t": "h2", "id": "distance-effect", "text": "Does Distance Matter?"},
        {"t": "p", "text": "Rhine's distance tests found no clear decline in scores as sender and receiver moved farther apart — across rooms, across buildings, even across countries in later replication attempts. That counter-intuitive result is one of the reasons telepathy research stayed controversial. For your own tests: try the same protocol at 3 meters and at 30, and compare."},
        {"t": "h2", "id": "controlled-vs-casual", "text": "Casual Test vs Controlled Experiment"},
        {"t": "p", "text": "A casual session is for fun and practice; a controlled experiment is for evidence. The differences: pre-recorded guesses, sealed envelopes, blind scoring, no mid-run feedback, and enough trials to matter. If your goal is to know whether you have an ability, run controlled sessions. If your goal is training, casual speed runs with immediate feedback build skill faster."},
        {"t": "h2", "id": "common-errors", "text": "Common Errors That Inflate Scores"},
        {"t": "ul", "items": [
            "Mid-run feedback: seeing the card after every guess lets the receiver adapt to patterns — score only at the end.",
            "Card peeking: sender reflections, screen gaps, or loose shuffling leak information.",
            "Shared preference bias: both people subconsciously favor the same symbol, inflating matches above chance.",
            "Selective memory: remembering the hits and forgetting the misses. The score sheet fixes this — use it.",
        ]},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "What score proves telepathy?"},
        {"t": "p", "text": "No single score proves it. Consistent scores of 9-10 or higher across multiple 25-card runs are what researchers take seriously; one lucky run of 8 is common enough to be noise."},
        {"t": "h3", "text": "How long should a session last?"},
        {"t": "p", "text": "One 25-card run takes about 5 minutes. Plan three runs with breaks — focus fades fast, and tired guessing collapses back to chance or worse."},
        {"t": "h3", "text": "Can I practice telepathy alone?"},
        {"t": "p", "text": "Solo practice trains clairvoyance and general ESP rather than telepathy, since no sender is present. Use a digital trainer like PSI GYM for solo sessions and save the two-person protocol for telepathy days."},
    ],
    "faq": [
        ["What score proves telepathy?", "No single score proves it. Consistent scores of 9-10 or higher across multiple 25-card runs are what researchers take seriously."],
        ["How long should a session last?", "One run takes about 5 minutes; plan three runs with breaks. Tired guessing collapses back to chance."],
        ["Can I practice telepathy alone?", "Solo practice trains clairvoyance and general ESP, not telepathy — you need a sender. Use PSI GYM for solo sessions and the two-person protocol for telepathy."],
    ],
}
