# -*- coding: utf-8 -*-
"""Article 19: dark-moon-meaning-witchcraft -> lunar-phase-calculator."""
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "dark-moon-meaning-witchcraft",
    "title": "Dark Moon Meaning in Witchcraft: The Hidden 5th Phase (2026)",
    "index_title": "Dark Moon in Witchcraft: Meaning & Practice",
    "desc": "What the dark moon actually is, how it differs from the new moon, and the divination, rest, and shadow work that belong to this hidden phase.",
    "keywords": "dark moon meaning, dark moon witchcraft, dark moon vs new moon, dark moon phase",
    "og_alt": "A fully dark moon sky with a thin silver rim and stars",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "moon",
    "excerpt": "The dark moon is the night the moon is invisible. It is not the new moon, and the difference matters for your practice.",
    "cta_apps": [["lunar-phase-calculator", "Lunar Phase Calculator"]],
    "related": [
        ["moon-phases-spell-timing-guide", RT["moon-phases-spell-timing-guide"]],
        ["lunar-phase-magic-guide", RT["lunar-phase-magic-guide"]],
        ["new-moon-vs-full-moon-ritual-guide", RT["new-moon-vs-full-moon-ritual-guide"]],
        ["lunar-phase-calculator-app-review", RT["lunar-phase-calculator-app-review"]],
    ],
    "references": [
        "Cunningham, Scott. Wicca: A Guide for the Solitary Practitioner (1988).",
        "Kynes, Sandra. Lunar Magic: Unlock Your Inner Power with the Energy of the Moon (2018).",
        "U.S. Naval Observatory Astronomical Applications. Phases of the Moon (2026).",
    ],
    "howto": [
        {"name": "Identify the dark moon window", "text": "The dark moon is the roughly three days before the new moon conjunction, when the moon is unilluminated and below the horizon around midnight. Use a lunar calculator to confirm the exact window."},
        {"name": "Choose a dark-moon practice", "text": "Pick divination, shadow journaling, or deliberate rest. Do not plant intentions in this phase; the soil is for fallow, not seeds."},
        {"name": "Work in low light", "text": "Keep the space dim, avoid screens where possible, and let the darkness set the tone rather than fighting it."},
        {"name": "Close by naming the cycle", "text": "End the practice by acknowledging the new moon that follows, marking the transition from inward to outward work."},
    ],
    "toc": [
        ["what-is-dark-moon", "What Is the Dark Moon?"],
        ["dark-vs-new", "Dark Moon vs New Moon"],
        ["dark-moon-work", "What to Do in the Dark Moon"],
        ["divination", "Divination in Darkness"],
        ["rest-and-shadow", "Rest and Shadow Work"],
        ["what-to-avoid", "What to Avoid"],
        ["finding-the-window", "Finding the Window"],
        ["faq", "FAQ"],
    ],
    "sections": [
        {"t": "p", "text": "Most calendars show only four lunar phases, but practitioners who work with the full cycle recognize a fifth: the dark moon. It is the handful of nights when the moon is essentially invisible, between the waning crescent and the new moon. It is not a duplicate of the new moon, and treating it as one is how rituals end up feeling flat."},
        {"t": "h2", "id": "what-is-dark-moon", "text": "What Is the Dark Moon?"},
        {"t": "p", "text": "Astronomically, the dark moon is the period when the illuminated fraction of the moon approaches zero, just before the new moon conjunction. The new moon itself is a single moment (when moon and sun align); the dark moon is the stretch of days around it when the sky offers no lunar light at night. Magically, that absence is the point: nothing is visible, nothing is manifesting, nothing is being demanded of you."},
        {"t": "h2", "id": "dark-vs-new", "text": "Dark Moon vs New Moon"},
        {"t": "table", "headers": ["Aspect", "Dark Moon", "New Moon"], "rows": [
            ["Timing", "~3 days before the conjunction", "The exact conjunction moment"],
            ["Sky", "Moon invisible at night", "Moon aligns with the sun"],
            ["Energy", "Inward, fallow, rest", "Outward, seed-planting"],
            ["Work", "Divination, shadow, release", "Manifestation, beginnings"],
            ["Mistake", "Planting intentions here", "Resting when you should plant"],
        ]},
        {"t": "p", "text": "The dark moon is the pause; the new moon is the start. If you have been combining them into one night of ritual, split them and feel the difference: one night of stillness, then one night of intention."},
        {"t": "h2", "id": "dark-moon-work", "text": "What to Do in the Dark Moon"},
        {"t": "ul", "items": [
            "Scrying and divination, where the absence of light sharpens the inner eye.",
            "Shadow journaling: what surfaced this cycle, what is unresolved, what you avoided.",
            "Cord-cutting and release work for what the waning moon has already loosened.",
            "Deliberate rest: sleep early, sit in silence, let the nervous system downshift.",
        ]},
        {"t": "h2", "id": "divination", "text": "Divination in Darkness"},
        {"t": "p", "text": "The dark moon is the best night of the month for divination that does not depend on light: pendulums, scrying mirrors, rune draws done by touch, tarot read in near-darkness. The reduced visual input pushes the reading toward the intuitive rather than the analytical, which is exactly the register the dark moon supports."},
        {"t": "h2", "id": "rest-and-shadow", "text": "Rest and Shadow Work"},
        {"t": "p", "text": "The dark moon is a fallow field. Farmers do not plant in the dead of winter, and the dark moon is the dead of the lunar winter. Use it for the work that requires the lights off: the honest journal page, the uncomfortable conversation with yourself, the nap you have been postponing. Shadow work performed here has a depth that the bright phases cannot reach."},
        {"t": "h2", "id": "what-to-avoid", "text": "What to Avoid"},
        {"t": "ul", "items": [
            "New-moon manifestation rituals (wrong phase; wait for the conjunction).",
            "High-energy social magic or launches (the phase does not support outward push).",
            "Pushing through exhaustion to 'get more done' (the cycle is asking for less).",
            "Fear-based banishing (the dark moon is restful, not threatening).",
        ]},
        {"t": "h2", "id": "finding-the-window", "text": "Finding the Window"},
        {"t": "p", "text": "The dark moon window shifts every month, which is why a <a href=\"../apps/lunar-phase-calculator.html\">Lunar Phase Calculator</a> is the practical tool here: it shows the exact phase for any date, so you know whether tonight is a dark-moon night, a new-moon moment, or a waxing crescent. Plug in the date, check the phase, and let the sky set the schedule."},
        {"t": "h2", "id": "faq", "text": "FAQ"},
        {"t": "h3", "text": "Is the dark moon the same as the new moon?"},
        {"t": "p", "text": "No. The new moon is a single astronomical moment; the dark moon is the ~3-day window before it when the moon is invisible. Different energy, different work."},
        {"t": "h3", "text": "Can I do manifestation rituals in the dark moon?"},
        {"t": "p", "text": "Technically yes, but you are pushing against the phase. Manifestation belongs to the new moon and waxing moon. The dark moon is for release, divination, and rest."},
        {"t": "h3", "text": "Why does my ritual feel different in the dark moon?"},
        {"t": "p", "text": "Because the phase has no outward pull. Rituals that depend on light, growth, and visibility have nothing to grip. Lean into what the phase actually supports instead of fighting it."},
    ],
    "faq": [
        ["Is the dark moon the same as the new moon?", "No. The new moon is a single moment; the dark moon is the ~3-day invisible window before it. Different energy, different work."],
        ["Can I do manifestation rituals in the dark moon?", "You can, but you are pushing against the phase. Manifestation belongs to the new and waxing moon; the dark moon is for release, divination, and rest."],
        ["Why does my ritual feel different in the dark moon?", "The phase has no outward pull, so light-and-growth rituals have nothing to grip. Lean into what the phase supports instead."],
    ],
}
