# -*- coding: utf-8 -*-
# Article 32 — PSI GYM vs Free Online Zener Tests
from related_titles import RELATED_TITLES as RT

ARTICLE = {
    "slug": "psi-gym-vs-free-zener-test",
    "title": "PSI GYM vs Free Online Zener Tests (2026): Why Scoring Matters",
    "index_title": "PSI GYM vs Free Zener Tests",
    "desc": "Free Zener tests are fun, but they can't track real progress. PSI GYM adds session scoring, streaks, and statistics that free online tests leave out.",
    "keywords": "psi gym vs free, zener test accuracy, ESP trainer comparison, free zener card test vs app, ESP training app",
    "og_alt": "A phone screen showing a Zener card test session with score statistics beside a simple browser test",
    "date_iso": "2026-08-16",
    "date_display": "August 16, 2026",
    "lastmod": "2026-08-16",
    "read_min": 8,
    "category": "esp",
    "excerpt": "Free online Zener tests are fine for a few minutes of fun. But if you actually want to train ESP, scoring and session history matter more than the card images.",
    "cta_apps": [["psi-gym", "PSI GYM: Zener Cards & ESP"]],
    "related": [
        ["psi-gym-app-review", RT["psi-gym-app-review"]],
        ["zener-cards-esp-training-guide", RT["zener-cards-esp-training-guide"]],
        ["zener-card-test-score-meaning", RT["zener-card-test-score-meaning"]],
        ["best-esp-training-apps-android", RT["best-esp-training-apps-android"]],
    ],
    "references": [
        "J.B. Rhine, Extra-Sensory Perception (1934).",
        "J.B. Rhine, The Reach of the Mind (1947).",
        "K. Zener & J.B. Rhine, Duke University ESP card protocols (1930s).",
    ],
    "howto": [
        {"name": "Define your goal", "text": "Decide whether you want casual fun or measurable training. This determines which tool fits."},
        {"name": "Compare scoring depth", "text": "Check whether the tool tracks session history, averages, streaks, and statistical significance."},
        {"name": "Test the same protocol", "text": "Run 25 cards on both the free test and the app, then compare how each reports the result."},
        {"name": "Check distraction level", "text": "Notice whether the tool runs in a clean session or fills the screen with ads and buttons."},
        {"name": "Commit for a week", "text": "Use whichever you pick daily for 7 days. Progress tracking is what builds the habit."},
    ],
    "toc": [
        ["why-compare", "Why Compare a Free Test and an App?"],
        ["what-free-tests-offer", "What Free Online Zener Tests Offer"],
        ["where-free-tests-fall-short", "Where Free Tests Fall Short"],
        ["what-psi-gym-adds", "What PSI GYM Adds"],
        ["score-tracking-matters", "Why Score Tracking Matters"],
        ["feature-table", "Feature Comparison Table"],
        ["which-to-choose", "Which One Should You Choose?"],
        ["faq", "Frequently Asked Questions"],
    ],
    "sections": [
        {"t": "p", "text": "A free online Zener card test is the fastest way to try ESP testing. You open a page, guess five symbols a few dozen times, and get a score. It takes three minutes and costs nothing. For a lot of people that is exactly what they need."},
        {"t": "p", "text": "But there is a difference between testing yourself once and training yourself over time. That difference is scoring. Free tests give you a number. A training tool like <a href=\"../apps/psi-gym.html\">PSI GYM</a> gives you a record."},
        {"t": "h2", "id": "what-free-tests-offer", "text": "What Free Online Zener Tests Offer"},
        {"t": "p", "text": "The typical free Zener test is a simple loop: a card appears face down, you click one of five symbols, it flips, and a counter ticks up. After 25 rounds it shows something like \u201cYou scored 8 out of 25.\u201d"},
        {"t": "ul", "items": ["Zero setup: no install, no account", "Instant result in minutes", "Good enough to get a first impression", "Works on any device with a browser"]},
        {"t": "h2", "id": "where-free-tests-fall-short", "text": "Where Free Tests Fall Short"},
        {"t": "ul", "items": ["No session history: yesterday's score is gone", "No averages, streaks, or trends", "Randomness is rarely explained (is 8/25 good?)", "Ads and pop-ups break concentration", "No protocol control (run length, delay, pacing)"]},
        {"t": "p", "text": "The biggest problem is context. A single score of 8 out of 25 means nothing by itself. Chance alone produces that regularly. What matters is your average across many sessions, whether your best runs cluster, and whether you improve with practice. Free tests throw all of that away."},
        {"t": "h2", "id": "what-psi-gym-adds", "text": "What PSI GYM Adds"},
        {"t": "p", "text": "<a href=\"../apps/psi-gym.html\">PSI GYM: Zener Cards &amp; ESP</a> is a one-time-purchase Android app built around the same five Zener symbols, but it treats ESP as something you train, not something you check once."},
        {"t": "ul", "items": ["Every session is saved with a timestamp", "Running average and trend across all sessions", "Streak tracking to keep the habit alive", "Clean, ad-free training screen", "Session length and pacing you control", "No account, no cloud, no subscription"]},
        {"t": "h2", "id": "score-tracking-matters", "text": "Why Score Tracking Matters"},
        {"t": "p", "text": "In the original Duke University protocols, a run of 25 cards has a chance baseline of 5 correct guesses (one in five). Scores of 9 or 10 happen occasionally by luck. Consistent scores of 11 or higher across sessions are what researchers flagged as notable. You can only see that pattern with a history."},
        {"t": "p", "text": "A free test cannot tell you whether today's good run is a fluke or a real shift. A logged training app can. That is the difference between guessing and practicing."},
        {"t": "h2", "id": "feature-table", "text": "Feature Comparison Table"},
        {"t": "table", "headers": ["Feature", "Free Online Test", "PSI GYM"], "rows": [
            ["Price", "Free (ad-supported)", "One-time payment"],
            ["Session history", "No", "Yes, timestamped"],
            ["Running average", "No", "Yes"],
            ["Streak tracking", "No", "Yes"],
            ["Statistical context", "Rarely", "Built-in"],
            ["Ads during sessions", "Often", "Never"],
            ["Account required", "Sometimes", "No"],
            ["Works offline", "No", "Yes"],
        ]},
        {"t": "h2", "id": "which-to-choose", "text": "Which One Should You Choose?"},
        {"t": "ul", "items": ["Curious for three minutes? Use any free test.", "Training ESP seriously? You need history and scoring.", "Want to avoid subscriptions forever? PSI GYM is a one-time purchase with no ads.", "Testing on someone else's computer? A browser test works anywhere."]},
        {"t": "h2", "id": "faq", "text": "Frequently Asked Questions"},
        {"t": "h3", "text": "Are free Zener tests accurate?"},
        {"t": "p", "text": "The card generation is usually random enough, but accuracy of measurement is different. Without session history and statistical context, a single score is noise."},
        {"t": "h3", "text": "What is a good score on a Zener test?"},
        {"t": "p", "text": "Chance is 5 in 25 (20%). 6-8 is unremarkable, 9-10 is notable, and consistent 11+ is where researchers started paying attention."},
        {"t": "h3", "text": "Is PSI GYM really one-time payment?"},
        {"t": "p", "text": "Yes. No subscription, no in-app purchases, no ads. You buy it once and it is yours."},
    ],
    "faq": [
        ["Are free Zener tests accurate?", "The card generation is usually random enough, but accuracy of measurement is different. Without session history and statistical context, a single score is noise."],
        ["What is a good score on a Zener test?", "Chance is 5 in 25 (20%). 6-8 is unremarkable, 9-10 is notable, and consistent 11+ is where researchers started paying attention."],
        ["Is PSI GYM really one-time payment?", "Yes. No subscription, no in-app purchases, no ads. You buy it once and it is yours."],
    ],
}
