# -*- coding: utf-8 -*-
# Exact <title> strings of existing blog articles, for `related` link anchor text.
# Extracted from blog/*.html on 2026-08-16. Key = slug, value = full <title>.
RELATED_TITLES = {
    "arcana-goetia-app-review": "Arcana Goetia App Review: Summon the 72 Spirits on Android",
    "goetia-beginners-ritual": "How to Safely Invoke a Goetic Spirit for Beginners: Step-by-Step Ritual 2026",
    "which-goetia-spirit-for-love-money-knowledge": "Which Goetia Spirit Should You Call? Love, Money & Knowledge (2026)",
    "best-goetia-books-essential-reading-2026": "Best Goetia Books: Essential Reading for Solomonic Magic Practitioners 2026",
    "goetic-magic-beginners-guide": "Goetic Magic for Beginners: Complete Guide to the 72 Spirits",
    "zener-cards-esp-training-guide": "How to Use Zener Cards for ESP Training | Complete Guide",
    "zener-card-test-score-meaning": "Zener Card Test Score Meaning: What Your ESP Score Really Says (2026)",
    "scientific-studies-zener-cards-esp-validation": "5 Scientific Studies That Validate Zener Card ESP Testing (2026)",
    "psi-gym-app-review": "PSI GYM App Review 2026: Train Your ESP with Zener Cards",
    "how-to-charge-sigil-correctly": "How to Charge a Sigil Correctly: 7 Proven Methods",
    "austin-osman-spare-sigil-method": "Austin Osman Spare Sigilization: The Original Method Explained",
    "sigil-maker-ultimate-guide": "The Ultimate Sigil Maker Guide: Create Powerful Sigils",
    "bindrune-wealth-protection-fehu-algiz-othala": "Bindrune for Wealth Protection | Fehu Algiz Othala Explained",
    "how-to-charge-sigil-without-meditation": "How to Charge a Sigil Without Meditation: 7 Fast Methods (2026)",
    "sigil-magic-complete-theory-practice": "Sigil Magic: Complete Theory and Practice Guide for Chaos Magick",
    "chaos-sigil-generator-app-review": "Chaos Sigil Generator App Review: Digital Sigil Making",
    "norse-runes-beginners-guide": "Norse Runes Guide: Elder Futhark Divination for Beginners",
    "free-online-rune-reading-guide": "Free Online Rune Reading: Instant Viking Divination (2026)",
    "norse-rune-oracle-app-review": "Norse Rune Oracle App Review: Best Viking Rune Reader",
    "rune-spreads-for-beginners": "Rune Spreads for Beginners: 5 Simple Layouts That Actually Work (2026)",
    "tarot-spreads-for-love-relationships": "5 Best Tarot Spreads for Love and Relationships: Deepen Your Connection",
    "new-moon-vs-full-moon-ritual-guide": "New Moon vs Full Moon Rituals: Which Phase for Which Magic",
    "moon-phases-spell-timing-guide": "Moon Phases & Spell Timing: Complete Magical Calendar Guide",
    "moon-phase-calculator-for-spells": "Moon Phase Calculator for Spells: Cast on the Right Night (2026)",
    "lunar-phase-calculator-app-review": "Lunar Phase Calculator App Review: Best Moon Tracker for",
    "lunar-phase-magic-guide": "Moon Magic: Complete Guide to Lunar Phases for Rituals",
    "how-to-cast-iching-digitally": "How to Cast the I Ching Digitally: Coin Method Explained (2026)",
    "i-ching-hexagram-meanings-complete-guide": "I Ching Hexagram Meanings: Complete 64 Hexagram Guide (2026)",
    "i-ching-oracle-app-review": "I Ching Oracle App Review: Best Book of Changes App for",
    "tarot-card-meanings-major-arcana-complete-guide": "Complete Guide to Tarot Card Meanings: Major Arcana Explained for Beginners",
    "divination-methods-beyond-tarot-guide": "10 Divination Methods Beyond Tarot: From Tea Leaves to Bone Casting (2026)",
    "evp-spirit-box-session-setup": "EVP & Spirit Box Session Setup: A Complete Guide (2026)",
    "evp-vs-spirit-box-comparison-guide": "EVP vs Spirit Box: Understanding Paranormal Audio Investigation Methods",
    "evp-recording-complete-guide": "EVP Recording: The Complete Guide to Capturing Electronic Voice Phenomena",
    "best-ghost-hunting-apps-android-2026": "5 Best Ghost Hunting Apps for Android in 2026: EVP & Spirit Box Tools",
    "paranormal-investigation-step-by-step-guide": "How to Conduct a Paranormal Investigation: Step-by-Step Guide for Beginners",
    "ghost-hunting-apps-comparison-android": "Best Ghost Hunting Apps for Android: A Complete Comparison Guide",
    "haunted-roads-guide": "Haunted Roads Guide: The Best Haunted Road Trip Itineraries & Urban Legends",
    "astral-projection-for-beginners": "Astral Projection for Beginners: Step-by-Step Guide (2026)",
    "astral-projection-techniques-rope-roll-out-phasing-compared": "Astral Projection Techniques: Rope, Roll-Out & Phasing Methods Compared (2026)",
    "astral-lab-app-review": "Astral Lab App Review 2026: The Best Natal Chart App for Android",
    "vibrational-state-obe-precursor-recognition": "The Vibrational State: Recognizing and Using the OBE Precursor (2026)",
    "binaural-beats-lucid-dreaming-guide": "Binaural Beats for Lucid Dreaming: Complete Frequency Guide",
    "theta-waves-lucid-dreaming-brainwave-science": "Theta Waves for Lucid Dreaming: Brainwave Entrainment Science Guide (2026)",
    "tarot-card-reversed-meanings-guide": "Understanding Reversed Tarot Cards: Meanings and Interpretation Techniques",
    "yes-no-tarot-spread-guide": "Yes or No Tarot Reading: How to Get Clear Answers from the Cards",
    "rider-waite-tarot-beginners-guide": "Rider Waite Tarot for Beginners: Complete Guide to the 78 Cards",
    "tarot-spreads-beginners-guide": "Tarot Spreads for Beginners: Celtic Cross, 3-Card & More",
    "tarot-card-combinations-reading-techniques": "Tarot Card Combinations: How to Read Multiple Cards Together in a Spread",
    "celtic-cross-tarot-spread-meaning-positions": "Celtic Cross Tarot Spread: Complete Guide to All 10 Positions",
    "lucid-dreaming-techniques-beginners-2026": "Lucid Dreaming Techniques for Beginners 2026: WILD, DILD & Digital Dream Tools",
    "reality-check-techniques-best-lucidity-methods": "Reality Check Techniques: Best Methods for Increasing Lucidity Rate (2026)",
    "wake-back-to-bed-protocol-step-by-step-wbtb": "Wake Back to Bed Protocol: Step-by-Step WBTB Lucid Dreaming Method (2026)",
    "dream-machine-app-review": "Dream Machine App Review 2026: The Best Lucid Dreaming App for Android",
    "lucid-dream-app-review": "Lucid Dream App Review 2026: The Best Lucid Dreaming App for Android",
    "best-lucid-dreaming-apps-android-2026": "Best Lucid Dreaming Apps for Android (2026): Tested & Compared",
    "best-offline-lucid-dreaming-app-2026": "Best Offline Lucid Dreaming App for 2026: No Subscription, No Ads",
    "clairvoyance-test-online": "Clairvoyance Test Online: Measure Your Psychic Ability",
    "how-to-lucid-dream-tonight": "How to Lucid Dream Tonight: 5 Fast Techniques That Work (2026)",
    "best-esp-training-apps-android": "Best ESP Training Apps for Android 2026: Tested & Reviewed",
    "best-tarot-apps-android-2026": "10 Best Tarot Apps for Android in 2026: Honest Comparison Guide",
    "free-sigil-generator-online-guide": "Free Sigil Generator Online: Create Chaos Magick Sigils",
    "free-i-ching-online-guide": "Free I Ching Online: Cast the Book of Changes (2026)",
    "free-lunar-phase-calculator-guide": "Free Lunar Phase Calculator: Track Moon Cycles Online (2026)",
    "why-stop-paying-subscription-occult-apps": "Why I Stopped Paying for Subscription Occult Apps (2026)",
    "true-cost-tarot-app-subscription-vs-onetime": "The True Cost of a Tarot App: Subscription vs One-Time Payment (2026)",
    "dream-journaling-lucid-dreaming-complete-guide": "Dream Journaling for Lucid Dreaming: Complete Guide with Templates (2026)",
    "dream-machine-vs-awoken-comparison": "Dream Machine vs Awoken (2026): Which Lucid Dreaming App Wins?",
    "spirit-box-frequency-settings": "Spirit Box Frequency Settings: Best Sweep Rates for Clear EVP (2026)",
    "noctem-tools-app-review": "NOCTEM App Review 2026: The Best Ghost Hunting App for Android",
    "goetia-seals-and-sigils-guide": "Goetia Seals & Sigils: How to Use the 72 Seals of Solomon (2026)",
    "best-goetia-app-comparison": "Best Goetia App for Android (2026): Arcana Goetia vs the Alternatives",
    "how-long-sigil-takes-to-work": "How Long Does a Sigil Take to Work? Timelines Explained (2026)",
}